### ISSUE TITLE
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#102]
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$  node benchmark/simple/main.js -c config-fabric-kafka.json -n fabric-kafka.json
TAP version 13
# #######Caliper Test######
# create mychannel......
ok 1 created mychannel successfully
# Sleep 5s......
# Join channel......
# join mychannel
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:583:15
E0619 19:50:29.135480000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:29.136101000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:29.137642000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:29.143612000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:583:15
E0619 19:50:30.131582000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:30.137312000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:31.994305000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:31.996199000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:583:15
E0619 19:50:34.902132000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:34.903814000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:38.605351000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:38.607226000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:46.409797000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:46.411316000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:57.231567000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0619 19:50:57.233355000 140735644013440 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
not ok 2 TypeError: Cannot read property 'stack' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'stack' of undefined]
    at: process.onetime (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'stack' of undefined
          at channels.reduce.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:216:56)
          at <anonymous>
  ...

1..2
# tests 2
# pass  1
# fail  1

guolidong:/opt/gopath/src/github.com/hyperledger/caliper$

**Comment by JulienGuo** [comment]
fabric network is available

**Comment by JulienGuo** [comment]
# joinChannel 7
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:583:15
# joinChannel 8
error: [E2E testing]: install proposal was bad
not ok 3 Failed to install chaincodes, Error: Failed to send install Proposal or receive valid response: Error: 14 UNAVAILABLE: Connect Failed at Client.newDefaultKeyValueStore.then.then.then (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/e2eUtils.js:139:19) at <anonymous>
  ---
    operator: fail
    at: chaincodes.reduce.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/install-chaincode.js:65:19)
    stack: |-
      Error: Failed to install chaincodes, Error: Failed to send install Proposal or receive valid response: Error: 14 UNAVAILABLE: Connect Failed
          at Client.newDefaultKeyValueStore.then.then.then (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/e2eUtils.js:139:19)
          at <anonymous>
          at Test.assert [as _assert] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at chaincodes.reduce.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/install-chaincode.js:65:19)
          at <anonymous>
  ...
fabric.installSmartContract() failed, Error: Failed to send install Proposal or receive valid response: Error: 14 UNAVAILABLE: Connect Failed
    at Client.newDefaultKeyValueStore.then.then.then (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/e2eUtils.js:139:19)
    at <anonymous>
not ok 4 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/opt/gopath/src/github.com/hyperledger/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/opt/gopath/src/github.com/hyperledger/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
  ...
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:583:15
# joinChannel 10
(node:8675) UnhandledPromiseRejectionWarning: undefined
(node:8675) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:8675) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

1..4
# tests 4
# pass  2
# fail  2

**Comment by JulienGuo** [comment]
2018-06-20 06:49:34.950 UTC [common/deliver] deliverBlocks -> DEBU 411 [channel: mychannel] Received seekInfo (0xc420b8b800) start:<specified:<number:1 > > stop:<specified:<number:18446744073709551615 > >  from 172.20.0.6:40732
2018-06-20 06:49:34.950 UTC [fsblkstorage] waitForBlock -> DEBU 412 Going to wait for newer blocks. maxAvailaBlockNumber=[0], waitForBlockNum=[1]
2018-06-20 06:58:03.033 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 413 client/metadata fetching metadata for all topics from broker kafka2:9092
2018-06-20 06:58:03.511 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 414 client/metadata fetching metadata for all topics from broker kafka3:9092
2018-06-20 06:59:23.764 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 415 client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 06:59:24.251 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 416 client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 07:08:03.032 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 417 client/metadata fetching metadata for all topics from broker kafka2:9092
2018-06-20 07:08:03.511 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 418 client/metadata fetching metadata for all topics from broker kafka3:9092
2018-06-20 07:09:23.763 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 419 client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 07:09:24.251 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 41a client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 07:11:30.513 UTC [orderer/consensus/kafka/sarama] subscriptionConsumer -> DEBU 41b consumer/broker/1 disconnecting due to error processing FetchRequest: read tcp 172.20.0.12:48750->172.20.0.10:9092: i/o timeout
2018-06-20 07:11:30.521 UTC [orderer/consensus/kafka/sarama] subscriptionConsumer -> DEBU 41c consumer/broker/1 disconnecting due to error processing FetchRequest: read tcp 172.20.0.12:48760->172.20.0.10:9092: i/o timeout
2018-06-20 07:11:30.523 UTC [orderer/consensus/kafka/sarama] Close -> DEBU 41d Closed connection to broker 6e41cad75a6c:9092
2018-06-20 07:11:30.523 UTC [orderer/consensus/kafka] processMessagesToBlocks -> ERRO 41e [channel: testchainid] Error during consumption: kafka: error while consuming testchainid/0: read tcp 172.20.0.12:48750->172.20.0.10:9092: i/o timeout
2018-06-20 07:11:30.523 UTC [orderer/consensus/kafka] processMessagesToBlocks -> WARN 41f [channel: testchainid] Deliver sessions will be dropped if consumption errors continue.
2018-06-20 07:11:30.524 UTC [orderer/consensus/kafka/sarama] Close -> DEBU 420 Closed connection to broker 6e41cad75a6c:9092
2018-06-20 07:11:30.524 UTC [orderer/consensus/kafka] processMessagesToBlocks -> ERRO 421 [channel: mychannel] Error during consumption: kafka: error while consuming mychannel/0: read tcp 172.20.0.12:48760->172.20.0.10:9092: i/o timeout
2018-06-20 07:11:30.525 UTC [orderer/consensus/kafka] processMessagesToBlocks -> WARN 422 [channel: mychannel] Deliver sessions will be dropped if consumption errors continue.
2018-06-20 07:11:29.867 UTC [orderer/consensus/kafka/sarama] dispatcher -> DEBU 423 consumer/testchainid/0 finding new broker
2018-06-20 07:11:29.867 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 424 client/metadata fetching metadata for [testchainid] from broker kafka3:9092
2018-06-20 07:11:29.869 UTC [orderer/consensus/kafka/sarama] dispatcher -> DEBU 425 consumer/mychannel/0 finding new broker
2018-06-20 07:11:29.869 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 426 client/metadata fetching metadata for [mychannel] from broker kafka0:9092
2018-06-20 07:11:29.872 UTC [orderer/consensus/kafka/sarama] Validate -> DEBU 427 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018-06-20 07:11:29.873 UTC [orderer/consensus/kafka/sarama] updateSubscriptions -> DEBU 428 consumer/broker/1 added subscription to testchainid/0
2018-06-20 07:11:29.873 UTC [orderer/consensus/kafka] processMessagesToBlocks -> WARN 429 [channel: testchainid] Consumption will resume.
2018-06-20 07:11:29.874 UTC [orderer/consensus/kafka/sarama] func1 -> DEBU 42a Connected to broker at 6e41cad75a6c:9092 (registered as #1)
2018-06-20 07:11:29.876 UTC [orderer/consensus/kafka/sarama] Validate -> DEBU 42b ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018-06-20 07:11:29.877 UTC [orderer/consensus/kafka/sarama] updateSubscriptions -> DEBU 42c consumer/broker/1 added subscription to mychannel/0
2018-06-20 07:11:29.877 UTC [orderer/consensus/kafka] processMessagesToBlocks -> WARN 42d [channel: mychannel] Consumption will resume.
2018-06-20 07:11:29.877 UTC [orderer/consensus/kafka/sarama] func1 -> DEBU 42e Connected to broker at 6e41cad75a6c:9092 (registered as #1)
2018-06-20 07:18:00.375 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 42f client/metadata fetching metadata for all topics from broker kafka2:9092
2018-06-20 07:18:00.854 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 430 client/metadata fetching metadata for all topics from broker kafka3:9092
2018-06-20 07:19:21.106 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 431 client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 07:19:21.594 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 432 client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 07:28:00.375 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 433 client/metadata fetching metadata for all topics from broker kafka2:9092
2018-06-20 07:28:00.854 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 434 client/metadata fetching metadata for all topics from broker kafka3:9092
2018-06-20 07:29:21.105 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 435 client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 07:29:21.593 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 436 client/metadata fetching metadata for all topics from broker kafka0:9092
2018-06-20 07:38:00.375 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 437 client/metadata fetching metadata for all topics from broker kafka2:9092
2018-06-20 07:38:00.854 UTC [orderer/consensus/kafka/sarama] tryRefreshMetadata -> DEBU 438 client/metadata fetching metadata for all topics from broker kafka3:9092

**Comment by JulienGuo** [comment]
the request port is wrong

**Comment by nktuan286** [comment]
@JulienGuo  Did you resolve this bug? I have a same problem.

**Comment by JulienGuo** [comment]
@nktuan286 Yes, I did. my grpc request  ports were wrong. keep them right , json config same to yaml config

**Comment by dineshdsv3** [comment]
@JulienGuo  Can you please share clear steps on how you fixed this issue?

**Comment by aklenik** [comment]
@dineshdsv3 TLS handshake errors typically occur when:
- The Fabric nodes are bootstrapped with wrong certs (like old ones from your previous run), so they naturally won't match the newly generated client-side crypto stuff
- One side expects TLS, the other not (sides: Caliper network config file, Fabric node settings)

Can you elaborate on your issue a bit?
