### ISSUE TITLE
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#104]
Client 29744: error Error: could not find context's information in config file
    at Fabric.getContext (/home/ubuntu/caliper/src/fabric/fabric.js:84:35)
    at Blockchain.getContext (/home/ubuntu/caliper/src/comm/blockchain.js:87:27)
    at doTest (/home/ubuntu/caliper/src/comm/client/local-client.js:164:23)
    at process.<anonymous> (/home/ubuntu/caliper/src/comm/client/local-client.js:218:17)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:29744) UnhandledPromiseRejectionWarning: Error: could not find context's information in config file
    at Fabric.getContext (/home/ubuntu/caliper/src/fabric/fabric.js:84:35)
    at Blockchain.getContext (/home/ubuntu/caliper/src/comm/blockchain.js:87:27)
    at doTest (/home/ubuntu/caliper/src/comm/client/local-client.js:164:23)
    at process.<anonymous> (/home/ubuntu/caliper/src/comm/client/local-client.js:218:17)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:29744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0

**Comment by JulienGuo** [comment]
good in Mac OS  , wrong in ubuntu

**Comment by Caoxuyang** [comment]
Hi Julien,
The problem is that the code can't find one of the contexts in your Fabric config file.
The error message is quite clear about this: 

> UnhandledPromiseRejectionWarning: Error: could not find context's information in config file
> at Fabric.getContext (/home/ubuntu/caliper/src/fabric/fabric.js:84:35)

Go and check the path or the variable name of that specific context in your config file.

**Comment by JulienGuo** [comment]
@Caoxuyang Thanks, I changed rounds.label from "open"n to "invoke" , but didn't change it in code

**Comment by Caoxuyang** [comment]
@JulienGuo NP.
