### ISSUE TITLE
Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.

### ISSUE THREAD

**Issue by zhulingyanc** [hyperledger/caliper#105]
[root@cbc-231 caliper-master]# node benchmark/simple/main.js -c config-fabric.json -n fabric.json            
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d
ca_peerOrg1_ is up-to-date
ca_peerOrg2_ is up-to-date
Starting simplenetwork_peer_1 ... 
simplenetwork_ca_1 is up-to-date
orderer.example.com is up-to-date
peer0.org2.example.com is up-to-date
peer0.org1.example.com is up-to-date
peer1.org2.example.com is up-to-date
Starting simplenetwork_peer_1 ... done
# create mychannel......
E0626 18:28:08.258706805    2720 ssl_transport_security.cc:1063] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: Connect Failed\n    at Object.exports.createStatusError (/home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/common.js:87:15)\n    at ClientDuplexStream._emitStatusIfDone (/home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client.js:235:26)\n    at ClientDuplexStream._readsDone (/home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client.js:201:8)\n    at /home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:679:15"
not ok 1 Failed to create channels Error: SERVICE_UNAVAILABLE at ClientDuplexStream.<anonymous> (/home/hurf/caliper-master/node_modules/fabric-client/lib/Orderer.js:136:21) at ClientDuplexStream.emit (events.js:180:13) at ClientDuplexStream._emitStatusIfDone (/home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client.js:236:12) at ClientDuplexStream._readsDone (/home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client.js:201:8) at /home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:679:15
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/home/hurf/caliper-master/src/fabric/create-channel.js:160:19)
    stack: |-
      Error: Failed to create channels Error: SERVICE_UNAVAILABLE
          at ClientDuplexStream.<anonymous> (/home/hurf/caliper-master/node_modules/fabric-client/lib/Orderer.js:136:21)
          at ClientDuplexStream.emit (events.js:180:13)
          at ClientDuplexStream._emitStatusIfDone (/home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client.js:236:12)
          at ClientDuplexStream._readsDone (/home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client.js:201:8)
          at /home/hurf/caliper-master/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:679:15
          at Test.assert [as _assert] (/home/hurf/caliper-master/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/hurf/caliper-master/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/hurf/caliper-master/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/hurf/caliper-master/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/home/hurf/caliper-master/src/fabric/create-channel.js:160:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:118:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/hurf/caliper-master/src/fabric/create-channel.js:161:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
not ok 2 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/home/hurf/caliper-master/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/home/hurf/caliper-master/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/home/hurf/caliper-master/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/home/hurf/caliper-master/src/comm/bench-flow.js:347:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:118:7)
  ...

1..2
# tests 2
# pass  0
# fail  2

**Comment by JulienGuo** [comment]
Please try this operation :  
1. exec command "docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d "
2. delete start command from config-xxx.json
3. wait seconds. (10s )
4. exec command "node benchmark/simple/main.js -c config-fabric.json -n fabric.json"

**Comment by zhulingyanc** [comment]
Follow your steps(1~4), still return the same errors。

**Comment by JulienGuo** [comment]
Did you change the port of peer or orderer? Are the ports same with .json file?

**Comment by zhulingyanc** [comment]
in fabric.json file,  ip,port and server-hostname in orderer,peer and ca had been modified, but it still returned the same errors

**Comment by EG-easy** [comment]
I have a similar error

**Comment by EG-easy** [comment]
im using caliper/network/fabric-v11/3-org-3-peer/docker-compose.yaml and change the mychannel.tx, twoorgs.genesis.block, crypto-config  in my environment...
Then i have a similar error.

$ node benchmark/simple/main.js -n fabric.json
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric-v11/3-org-3-peer/docker-compose.yaml up -d
Creating couchdb.peer1.org3.example.com ... done
Creating couchdb.peer2.org1.example.com ... done
Creating orderer.example.com            ... done
Creating couchdb.peer1.org1.example.com ... done
Creating couchdb.peer2.org3.example.com ... done
Creating ca.org1.example.com            ... done
Creating couchdb.peer1.org2.example.com ... done
Creating couchdb.peer2.org2.example.com ... done
Creating ca.org2.example.com            ... done
Creating couchdb.peer0.org1.example.com ... done
Creating ca.org3.example.com            ... done
Creating couchdb.peer0.org3.example.com ... done
Creating couchdb.peer0.org2.example.com ... done
Creating peer0.org3.example.com         ... done
Creating peer1.org2.example.com         ... done
Creating peer1.org3.example.com         ... done
Creating peer0.org1.example.com         ... done
Creating peer0.org2.example.com         ... done
Creating peer2.org3.example.com         ... done
Creating peer1.org1.example.com         ... done
Creating peer2.org2.example.com         ... done
Creating peer2.org1.example.com         ... done
# create mychannel......
E0629 21:10:57.958212000 140736024703872 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0629 21:10:57.980125000 140736024703872 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: Connect Failed\n    at createStatusError (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)\n    at ClientDuplexStream._emitStatusIfDone (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:270:19)\n    at ClientDuplexStream._readsDone (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:236:8)\n    at readCallback (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:296:12)"
not ok 1 Failed to create channels Error: SERVICE_UNAVAILABLE at ClientDuplexStream.<anonymous> (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/lib/Orderer.js:138:21) at ClientDuplexStream.emit (events.js:127:13) at ClientDuplexStream._emitStatusIfDone (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:271:12) at ClientDuplexStream._readsDone (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:236:8) at readCallback (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:296:12)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/Users/shizuka/caliper1/caliper/src/fabric/create-channel.js:160:19)
    stack: |-
      Error: Failed to create channels Error: SERVICE_UNAVAILABLE
          at ClientDuplexStream.<anonymous> (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/lib/Orderer.js:138:21)
          at ClientDuplexStream.emit (events.js:127:13)
          at ClientDuplexStream._emitStatusIfDone (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:271:12)
          at ClientDuplexStream._readsDone (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:236:8)
          at readCallback (/Users/shizuka/caliper1/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:296:12)
          at Test.assert [as _assert] (/Users/shizuka/caliper1/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/Users/shizuka/caliper1/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/Users/shizuka/caliper1/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/Users/shizuka/caliper1/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/Users/shizuka/caliper1/caliper/src/fabric/create-channel.js:160:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:160:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/Users/shizuka/caliper1/caliper/src/fabric/create-channel.js:161:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
not ok 2 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/Users/shizuka/caliper1/caliper/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/Users/shizuka/caliper1/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/Users/shizuka/caliper1/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/Users/shizuka/caliper1/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:160:7)
  ...

1..2
# tests 2
# pass  0
# fail  2

is it possible to increase Peers in caliper benchmark test? Thanks!

**Comment by lotty02cho** [comment]
I have same issue with EG-easy. Does anyone know about this issues?

**Comment by nagarajasr** [comment]
in my case it was a misconfigured network-config.yaml which had the wrong port number for fabric-ca and peers. resolved after correcting the port numbers.

**Comment by fivepapertigers** [comment]
In case this helps anyone: I was running into handshake issues with fabric on Mac OSX using node 10.X, but 8.X seems to work alright.

**Comment by zsh122958** [comment]
Have you solved your problem?I have the same problem

**Comment by aklenik** [comment]
If someone is still encountering this issue after the proposed fixes, take a look at [my comment](https://github.com/hyperledger/caliper/issues/93#issuecomment-436253920) in a similar issue.

**Comment by fady-a-m-ibrahim** [comment]
One of the reasons is using unsuitable node version.
To add the Long Term Support (LTS) subversion of Node.js v8, we can use these commands:
```
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
source ~/.profile 
nvm ls-remote
nvm install v8.16.0
nvm list
nvm use v8.16.0
node --version
```

**Comment by csquan** [comment]
I had face same problem.
refer to https://jira.hyperledger.org/browse/BE-799#,but no answer. I do everythins as official said ,but still error.
Fabric have so many problems in deploy process,may be ....
