### ISSUE TITLE
how to solve it?

### ISSUE THREAD

**Issue by hehui0316** [hyperledger/caliper#1094]
I installed the chaincode in the network and test the caliper 
i modify the install-chaincode.js and instantiate-chaincode.js
add this
 if (chaincode.deployed){
                    return Promise.resolve();
                }
if(chaincode.deployed){
                    return Promise.resolve();
                }
the result of the test as following
I skip the step of create channel, I don't know how to solve it

node benchmark/simple/main.js
TAP version 13
# #######Caliper Test######
fabric.init() failed, Error: Util.resolvePath: Parameter is undefined
    at Function.resolvePath (/home/node1/Hyperledger-caliper/src/comm/util.js:53:19)
    at /home/node1/Hyperledger-caliper/src/fabric/create-channel.js:56:46
    at new Promise (<anonymous>)
    at Object.run (/home/node1/Hyperledger-caliper/src/fabric/create-channel.js:52:12)
    at Fabric.init (/home/node1/Hyperledger-caliper/src/fabric/fabric.js:40:28)
    at Blockchain.init (/home/node1/Hyperledger-caliper/src/comm/blockchain.js:60:27)
    at startPromise.then (/home/node1/Hyperledger-caliper/src/comm/bench-flow.js:304:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Util.resolvePath: Parameter is undefined
    at Function.resolvePath (/home/node1/Hyperledger-caliper/src/comm/util.js:53:19)
    at /home/node1/Hyperledger-caliper/src/fabric/create-channel.js:56:46
    at new Promise (<anonymous>)
    at Object.run (/home/node1/Hyperledger-caliper/src/fabric/create-channel.js:52:12)
    at Fabric.init (/home/node1/Hyperledger-caliper/src/fabric/fabric.js:40:28)
    at Blockchain.init (/home/node1/Hyperledger-caliper/src/comm/blockchain.js:60:27)
    at startPromise.then (/home/node1/Hyperledger-caliper/src/comm/bench-flow.js:304:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

1..0
# tests 0
# pass  0

# ok

**Comment by nklincoln** [comment]
what version of caliper?
what operating system?
local or remote network?
what system under test? (fabric, ethereum, besu, .. ?)

**Comment by hehui0316** [comment]
> what version of caliper?
> what operating system?
> local or remote network?
> what system under test? (fabric, ethereum, besu, .. ?)

I solved the problem, thanks

**Comment by nklincoln** [comment]
Thanks for update, closing issue

**Comment by noobmdev** [comment]
How do you resolve the problem? I have a same problem when change web3j-eea to web3js-quorum
