### ISSUE TITLE
Failed to create channels Error: create status is BAD_REQUEST

### ISSUE THREAD

**Issue by yodash** [hyperledger/caliper#111]
I have same error with this issue.
https://github.com/hyperledger/caliper/issues/81

Although I stopped old containers, I still have error. How can I solve it??

docker-compose -f network/fabric-v11/3-org-3-peer/docker-compose.yaml up -d
Creating couchdb.peer0.org3.example.com ... done
Creating couchdb.peer2.org1.example.com ... done
Creating orderer.example.com            ... done
Creating couchdb.peer1.org2.example.com ... done
Creating couchdb.peer2.org3.example.com ... done
Creating ca.org2.example.com            ... done
Creating couchdb.peer2.org2.example.com ... done
Creating couchdb.peer1.org1.example.com ... done
Creating ca.org3.example.com            ... done
Creating couchdb.peer1.org3.example.com ... done
Creating couchdb.peer0.org2.example.com ... done
Creating ca.org1.example.com            ... done
Creating couchdb.peer0.org1.example.com ... done
Creating peer1.org3.example.com         ... done
Creating peer0.org3.example.com         ... done
Creating peer0.org1.example.com         ... done
Creating peer0.org2.example.com         ... done
Creating peer1.org2.example.com         ... done
Creating peer2.org3.example.com         ... done
Creating peer1.org1.example.com         ... done
Creating peer2.org2.example.com         ... done
Creating peer2.org1.example.com         ... done
# create mychannel......
not ok 1 Failed to create channels Error: create status is BAD_REQUEST at channel.organizations.reduce.then.then.then (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/fabric/create-channel.js:146:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:160:7)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/fabric/create-channel.js:160:19)
    stack: |-
      Error: Failed to create channels Error: create status is BAD_REQUEST
          at channel.organizations.reduce.then.then.then (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/fabric/create-channel.js:146:43)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:160:7)
          at Test.assert [as _assert] (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/fabric/create-channel.js:160:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:160:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/fabric/create-channel.js:161:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
not ok 2 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/Users/yo-dash/Blockchain/HyperLedger/caliper3/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:160:7)
  ...

1..2
# tests 2
# pass  0
# fail  2

**Comment by yodash** [comment]
solved

**Comment by bitpeng** [comment]
@yodash the same error, how to solve this issue?

**Comment by shichangzhi** [comment]
@yodash hello，i get the same error,but i don not know how to solve this problem,can you share your solution?Thanks
