### ISSUE TITLE
Caliper will fail if I don't manually start the ethereum container before running the benchmark test.

### ISSUE THREAD

**Issue by hkiridera** [hyperledger/caliper#1148]
## Context

Caliper will fail if you do not manually start the ethereum container before running the benchmark test.
I think web3 connecter try to connect before starting ethereum container. 
I expect web3 to connect after executing the start command specified in networkconfig.json

## log

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ npx caliper launch manager --caliper-bind-sut besu:latest --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig ./networks/ethereum/1node-clique/networkconfig.json --caliper-workspace .
2021.07.08-12:35:40.331 info  [caliper] [cli-launch-manager]    Binding specification is present, performing binding for "besu:latest"
2021.07.08-12:35:40.335 warn  [caliper] [bind]  Working directory not specified. Using "/home/vagrant/caliper-benchmarks"
2021.07.08-12:35:40.335 info  [caliper] [bind]  Binding for besu@latest. This might take some time...
2021.07.08-12:35:40.336 info  [caliper] [bind]  Using working directory: /home/vagrant/caliper-benchmarks
2021.07.08-12:35:40.336 info  [caliper] [bind]  Calling npm with: install web3@1.2.2

> web3@1.2.2 postinstall /home/vagrant/caliper-benchmarks/node_modules/web3
> node angular-patch.js

npm WARN saveError ENOENT: no such file or directory, open '/home/vagrant/caliper-benchmarks/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/caliper-benchmarks/package.json'
npm WARN caliper-benchmarks No description
npm WARN caliper-benchmarks No repository field.
npm WARN caliper-benchmarks No README data
npm WARN caliper-benchmarks No license field.

+ web3@1.2.2
updated 1 package in 4.404s

8 packages are looking for funding
  run `npm fund` for details

2021.07.08-12:35:45.450 info  [caliper] [cli-launch-manager]    Set workspace path: /home/vagrant/caliper-benchmarks
2021.07.08-12:35:45.451 info  [caliper] [cli-launch-manager]    Set benchmark configuration path: /home/vagrant/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2021.07.08-12:35:45.451 info  [caliper] [cli-launch-manager]    Set network configuration path: /home/vagrant/caliper-benchmarks/networks/ethereum/1node-clique/networkconfig.json
2021.07.08-12:35:45.451 info  [caliper] [cli-launch-manager]    Set SUT type: ethereum
2021.07.08-12:35:45.756 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2021.07.08-12:35:45.757 info  [caliper] [caliper-engine]        Starting benchmark flow
2021.07.08-12:35:45.765 info  [caliper] [caliper-utils]         Executing command: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml up -d && sleep 60s
Creating network "1node-clique_default" with the default driver
Creating ethereum_clique ... 
Creating ethereum_clique ... done
2021.07.08-12:36:48.616 info  [caliper] [caliper-engine]        Executed start command in 62.851 seconds
connection not open on send()
2021.07.08-12:36:48.630 error [caliper] [caliper-engine]        Error while performing "init" step: Error: connection not open
2021.07.08-12:36:48.630 info  [caliper] [caliper-engine]        Executed "init" step in 0.013 seconds
2021.07.08-12:36:48.631 info  [caliper] [caliper-utils]         Executing command: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml down
Stopping ethereum_clique ... 
Stopping ethereum_clique ... done
Removing ethereum_clique ... 
Removing ethereum_clique ... done
Removing network 1node-clique_default
2021.07.08-12:36:50.667 info  [caliper] [caliper-engine]        Executed end command in 2.036 seconds
2021.07.08-12:36:50.668 error [caliper] [cli-launch-manager]    Benchmark failed with error code 4
Usage:
 caliper launch manager --caliper-bind-sut fabric:1.4 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 4
    at Function.handler (/home/vagrant/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:70:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
$ cd networks/ethereum/1node-clique/
$ docker-compose up -d

$ cd caliper-benchmarks
$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
39b1c09c1ccd        caliper-ethereum-clique   "geth --unlock 0xc0A…"   38 seconds ago      Up 36 seconds       8545/tcp, 30303/tcp, 0.0.0.0:8546->8546/tcp, 30303/udp   ethereum_clique

$ npx caliper launch manager --caliper-bind-sut besu:latest --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig ./networks/ethereum/1node-clique/networkconfig.json --caliper-workspace .

............

2021.07.08-12:47:28.120 info  [caliper] [round-orchestrator]    Finished round 3 (transfer) in 15.176 seconds
2021.07.08-12:47:28.120 info  [caliper] [monitor.js]    Stopping all monitors
2021.07.08-12:47:28.120 info  [caliper] [report-builder]        ### All test results ###
2021.07.08-12:47:28.122 info  [caliper] [report-builder] 
+----------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
| Name     | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| open     | 1000 | 0    | 58.3            | 29.16           | 2.09            | 16.12           | 22.2             |
|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| query    | 1000 | 0    | 100.1           | 0.01            | 0.00            | 0.00            | 100.1            |
|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| transfer | 50   | 0    | 10.6            | 6.91            | 2.07            | 4.49            | 5.0              |
+----------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+

2021.07.08-12:47:28.146 info  [caliper] [report-builder]        Generated report with path /home/vagrant/caliper-benchmarks/report.html
2021.07.08-12:47:28.146 info  [caliper] [monitor.js]    Stopping all monitors
2021.07.08-12:47:28.146 info  [caliper] [worker-orchestrator]   Sending exit message to connected workers
2021.07.08-12:47:28.147 info  [caliper] [worker-message-handler]        Worker#0 is exiting
2021.07.08-12:47:28.148 info  [caliper] [round-orchestrator]    Benchmark finished in 105.329 seconds. Total rounds: 3. Successful rounds: 3. Failed rounds: 0.
2021.07.08-12:47:28.148 info  [caliper] [caliper-utils]         Executing command: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml down
Stopping ethereum_clique ... 
Stopping ethereum_clique ... done
Removing ethereum_clique ... 
Removing ethereum_clique ... done
Removing network 1node-clique_default
2021.07.08-12:47:29.936 info  [caliper] [caliper-engine]        Executed end command in 1.788 seconds
2021.07.08-12:47:29.936 info  [caliper] [cli-launch-manager]    Benchmark successfully finished

```

## Possible Fix

I think move `connector = await this.adapterFactory(-1);`  to before `await connector.init();`  
like that.
https://github.com/hkiridera/caliper/commit/732d2a0c3da9d66046872332e9c01018a2ed3380

## Steps to Reproduce

1. ethereum container is stopped.
2. run the caliper benchmark at ethereum mode.
3. The benchmark test was failed
4. but In advance, I started ethereum container, and run the caliper is success.

## Your Environment

* Version used: latest(commit id: 3106657c1917ba515f3b8e5caa66e9d260f0763b)
* Environment name and version
** nodejs: v12.16.1
* Operating System and version (desktop or mobile): ubuntu20.04 server

**Comment by aklenik** [comment]
@hkiridera The start command is always executed first, and it can also _include a sleep time_ to delay the connection attempt. 

You are right, the connector could be more robust regarding (re)connection attempts, but the start script is only a convenience feature for local development and testing. _Caliper expects your SUT to be ready_ to accept connections. Similar convenience features (like network initialization) will be deprecated in the long run. Along this reasoning, I'm closing this issue, since it's not a Caliper bug.
