### ISSUE TITLE
Caliper generator tests are currently broken

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1157]
The following shows the output of the generator tests
```
# Run benchmark generator using generator defaults (specify invalid values for options)
${GENERATOR_METHOD} -- --workspace 'myWorkspace' --contractId 'mymarbles' --contractVersion 'v0' --contractFunction 'queryMarblesByOwner' --contractArguments '["Alice"]' --workers 'marbles' --benchmarkName 'A name for the marbles benchmark' --benchmarkDescription 'A description for the marbles benchmark' --label 'A label for the round' --rateController 'fixed-rate' --txType 'txDuration' --txDuration 'marbles'
/opt/hostedtoolcache/node/10.24.1/x64/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`, `${prefix}/*/index.cjs`, `${prefix}/*/index.mjs`]),
                          ^

TypeError: lookups.flatMap is not a function
    at Environment.resolver.lookup (/opt/hostedtoolcache/node/10.24.1/x64/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70:27)
    at init (/opt/hostedtoolcache/node/10.24.1/x64/lib/node_modules/yo/lib/cli.js:130:7)
    at Immediate.pre (/opt/hostedtoolcache/node/10.24.1/x64/lib/node_modules/yo/lib/cli.js:89:3)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
# start network and run benchmark test
```
Possible causes are that dependencies have changed and maybe only support newer versions of node

**Comment by aklenik** [comment]
Temporarily fixed by #1176 (Re-bump yo version after node version bump)
