### ISSUE TITLE
"../chaincode/fabcar/go/fabcar.go" is outside of "/chaincode/input"

### ISSUE THREAD

**Issue by BigBang019** [hyperledger/caliper#1163]
node ./caliper/src/main.js -n caliper/fabric_network.json -c inventory/fabcar/config.yaml

```
info: [bench-flow.js]: ####### Caliper Test #######
info: [create-channel.js]: Sleeping 5s...
info: [join-channel.js]: Joining channels...
info: [install-chaincode.js]: installing all chaincodes......
info: [install-chaincode.js]: Installing chaincode fabcar...
info: [install-chaincode.js]: Installing chaincode fabcar...
info: [install-chaincode.js]: Installed chaincode fabcar successfully in all peers
info: [instantiate-chaincode.js]: Instantiating chaincodes...
warn: [e2eUtils.js]: instantiate proposal was bad: Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): "../chaincode/fabcar/go/fabcar.go" is outside of "/chaincode/input"
warn: [e2eUtils.js]: instantiate proposal was bad: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
warn: [e2eUtils.js]: instantiate proposal was bad: Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): "../chaincode/fabcar/go/fabcar.go" is outside of "/chaincode/input"
warn: [e2eUtils.js]: instantiate proposal was bad: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
warn: [e2eUtils.js]: [{"message":"error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): \"../chaincode/fabcar/go/fabcar.go\" is outside of \"/chaincode/input\"","stack":"Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): \"../chaincode/fabcar/go/fabcar.go\" is outside of \"/chaincode/input\"\n    at /Users/zhuxingyu/vscode/testbed/node_modules/fabric-client/lib/Peer.js:144:36\n    at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1212:9)\n    at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24)","status":500,"payload":{"type":"Buffer","data":[]},"peer":{"url":"grpcs://localhost:7051","name":"localhost:7051","options":{"grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1,"grpc.keepalive_time_ms":120000,"grpc.http2.min_time_between_pings_ms":120000,"grpc.keepalive_timeout_ms":20000,"grpc.http2.max_pings_without_data":0,"grpc.keepalive_permit_without_calls":1,"clientCert":"-----BEGIN CERTIFICATE-----\nMIICIjCCAcmgAwIBAgIUGI8mk6wmORVfLFpV8S1dzNz47AwwCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh\nbiBGcmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMT\nE2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwOTE2MDc0OTAwWhcNMjIwOTE2MDc1\nNDAwWjAhMQ8wDQYDVQQLEwZjbGllbnQxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEiWn/l23l9lALrVCUn06Pg/ZxDBQ+AVu7DjV6GnvC\n1owhelyh3z++c6l3E/awRgrgQw/G0ERVnvVLPi7AVn/MUKOBjDCBiTAOBgNVHQ8B\nAf8EBAMCA6gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB\n/wQCMAAwHQYDVR0OBBYEFMsEWmxLTxlDckvAsZlAsln8VNIHMCsGA1UdIwQkMCKA\nIOzIDLLNkUAHleI8UMN29ItyuBo6QbjI094gZEEOOr7NMAoGCCqGSM49BAMCA0cA\nMEQCIHN2j1vTPYWu1j97XT1aJ9E/leGx2JTFitmBJ2+W4RHgAiBMac8+0Q+QD74B\nRtWaooB24sjtomm58pQwc0o4/wZSNQ==\n-----END CERTIFICATE-----\n","grpc.ssl_target_name_override":"peer0.org1.example.com","grpc.default_authority":"peer0.org1.example.com"}},"isProposalResponse":true},{"message":"2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]","stack":"Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]\n    at Object.exports.createStatusError (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24)","code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"access denied: channel [mychannel] creator org [Org1MSP]"},{"message":"error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): \"../chaincode/fabcar/go/fabcar.go\" is outside of \"/chaincode/input\"","stack":"Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): \"../chaincode/fabcar/go/fabcar.go\" is outside of \"/chaincode/input\"\n    at /Users/zhuxingyu/vscode/testbed/node_modules/fabric-client/lib/Peer.js:144:36\n    at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1212:9)\n    at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24)","status":500,"payload":{"type":"Buffer","data":[]},"peer":{"url":"grpcs://localhost:9051","name":"localhost:9051","options":{"grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1,"grpc.keepalive_time_ms":120000,"grpc.http2.min_time_between_pings_ms":120000,"grpc.keepalive_timeout_ms":20000,"grpc.http2.max_pings_without_data":0,"grpc.keepalive_permit_without_calls":1,"clientCert":"-----BEGIN CERTIFICATE-----\nMIICIjCCAcmgAwIBAgIUGI8mk6wmORVfLFpV8S1dzNz47AwwCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh\nbiBGcmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMT\nE2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwOTE2MDc0OTAwWhcNMjIwOTE2MDc1\nNDAwWjAhMQ8wDQYDVQQLEwZjbGllbnQxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEiWn/l23l9lALrVCUn06Pg/ZxDBQ+AVu7DjV6GnvC\n1owhelyh3z++c6l3E/awRgrgQw/G0ERVnvVLPi7AVn/MUKOBjDCBiTAOBgNVHQ8B\nAf8EBAMCA6gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB\n/wQCMAAwHQYDVR0OBBYEFMsEWmxLTxlDckvAsZlAsln8VNIHMCsGA1UdIwQkMCKA\nIOzIDLLNkUAHleI8UMN29ItyuBo6QbjI094gZEEOOr7NMAoGCCqGSM49BAMCA0cA\nMEQCIHN2j1vTPYWu1j97XT1aJ9E/leGx2JTFitmBJ2+W4RHgAiBMac8+0Q+QD74B\nRtWaooB24sjtomm58pQwc0o4/wZSNQ==\n-----END CERTIFICATE-----\n","grpc.ssl_target_name_override":"peer0.org2.example.com","grpc.default_authority":"peer0.org2.example.com"}},"isProposalResponse":true},{"message":"2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]","stack":"Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]\n    at Object.exports.createStatusError (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24)","code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"access denied: channel [mychannel] creator org [Org1MSP]"}]
error: [instantiate-chaincode.js]: Failed to instantiate chaincodes: Error: All proposals were not good
    at instantiate (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/e2eUtils.js:399:15)
    at async Object.instantiateChaincode (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/e2eUtils.js:652:9)
    at async Object.run (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/instantiate-chaincode.js:39:13)
    at async Fabric.installSmartContract (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/fabric.js:57:13)
    at async Blockchain.installSmartContract (/Users/zhuxingyu/vscode/testbed/caliper/src/comm/blockchain.js:96:9)
    at async Object.module.exports.run (/Users/zhuxingyu/vscode/testbed/caliper/src/comm/bench-flow.js:357:9)
    at async main (/Users/zhuxingyu/vscode/testbed/caliper/src/main.js:53:9)
error: [fabric.js]: Fabric chaincode install failed: Error: All proposals were not good
    at instantiate (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/e2eUtils.js:399:15)
    at async Object.instantiateChaincode (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/e2eUtils.js:652:9)
    at async Object.run (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/instantiate-chaincode.js:39:13)
    at async Fabric.installSmartContract (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/fabric.js:57:13)
    at async Blockchain.installSmartContract (/Users/zhuxingyu/vscode/testbed/caliper/src/comm/blockchain.js:96:9)
    at async Object.module.exports.run (/Users/zhuxingyu/vscode/testbed/caliper/src/comm/bench-flow.js:357:9)
    at async main (/Users/zhuxingyu/vscode/testbed/caliper/src/main.js:53:9)
error: [bench-flow.js]: Error: Error: All proposals were not good
    at instantiate (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/e2eUtils.js:399:15)
    at async Object.instantiateChaincode (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/e2eUtils.js:652:9)
    at async Object.run (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/instantiate-chaincode.js:39:13)
    at async Fabric.installSmartContract (/Users/zhuxingyu/vscode/testbed/caliper/src/adapters/fabric/fabric.js:57:13)
    at async Blockchain.installSmartContract (/Users/zhuxingyu/vscode/testbed/caliper/src/comm/blockchain.js:96:9)
    at async Object.module.exports.run (/Users/zhuxingyu/vscode/testbed/caliper/src/comm/bench-flow.js:357:9)
    at async main (/Users/zhuxingyu/vscode/testbed/caliper/src/main.js:53:9)
```

**Comment by BigBang019** [comment]
Sorry to put such a long error report. I find the result returned by SDK, which is generated by the statement:
```
results = await channel.sendInstantiateProposal(request);
```
The result is: 
```
[
  [
    Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): "../chaincode/fabcar/go/fabcar.go" is outside of "/chaincode/input"
        at /Users/zhuxingyu/vscode/testbed/node_modules/fabric-client/lib/Peer.js:144:36
        at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1212:9)
        at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24) {
      status: 500,
      payload: <Buffer >,
      peer: [Object],
      isProposalResponse: true
    },
    Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
        at Object.exports.createStatusError (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/common.js:91:15)
        at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1209:28)
        at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24) {
      code: 2,
      metadata: [Metadata],
      details: 'access denied: channel [mychannel] creator org [Org1MSP]'
    },
    Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error uploading input to container: API error (500): Error processing tar file(exit status 1): "../chaincode/fabcar/go/fabcar.go" is outside of "/chaincode/input"
        at /Users/zhuxingyu/vscode/testbed/node_modules/fabric-client/lib/Peer.js:144:36
        at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1212:9)
        at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24) {
      status: 500,
      payload: <Buffer >,
      peer: [Object],
      isProposalResponse: true
    },
    Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
        at Object.exports.createStatusError (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/common.js:91:15)
        at Object.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:1209:28)
        at InterceptingListener._callNext (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/Users/zhuxingyu/vscode/testbed/node_modules/grpc/src/client_interceptors.js:847:24) {
      code: 2,
      metadata: [Metadata],
      details: 'access denied: channel [mychannel] creator org [Org1MSP]'
    }
  ],
  {
    header: ByteBuffer {
      buffer: <Buffer 0a 8a 01 08 03 10 01 1a 0b 08 c5 f1 8b 8a 06 10 80 99 9b 10 22 09 6d 79 63 68 61 6e 6e 65 6c 2a 40 36 39 38 32 61 39 63 63 31 35 61 32 64 32 34 65 38 ... 949 more bytes>,
      offset: 0,
      markedOffset: -1,
      limit: 999,
      littleEndian: false,
      noAssert: false
    },
    payload: ByteBuffer {
      buffer: <Buffer 0a 74 0a 72 08 01 12 06 12 04 6c 73 63 63 1a 66 0a 06 64 65 70 6c 6f 79 0a 09 6d 79 63 68 61 6e 6e 65 6c 0a 1b 0a 19 08 01 12 0d 12 06 66 61 62 63 61 ... 68 more bytes>,
      offset: 0,
      markedOffset: -1,
      limit: 118,
      littleEndian: false,
      noAssert: false
    },
    extension: ByteBuffer {
      buffer: <Buffer >,
      offset: 0,
      markedOffset: -1,
      limit: 0,
      littleEndian: false,
      noAssert: false
    }
  }
]
```
