### ISSUE TITLE
"orderers" is required

### ISSUE THREAD

**Issue by miamhe** [hyperledger/caliper#1251]
### Which Caliper version are you using?

v0.4.2

### Which Node.JS version are you using?

v14.10.0

### Which operating system are you using?

Unbuntu 20.04

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

I just want to test my contract  function tps. 

The error：
```
 npx caliper launch manager --caliper-workspace ./ --caliper-networkconfig networks/calipernetworkconfig.yaml --caliper-benchconfig benchmarks/caliperbenchmarkconfig.yaml --caliper-flow-only-test --caliper-fabric-gateway-enabled
2022.03.05-21:19:21.493 info  [caliper] [cli-launch-manager] 	Set workspace path: /root/go/src/VppChain/capliper
2022.03.05-21:19:21.494 info  [caliper] [cli-launch-manager] 	Set benchmark configuration path: /root/go/src/VppChain/capliper/benchmarks/caliperbenchmarkconfig.yaml
2022.03.05-21:19:21.495 info  [caliper] [cli-launch-manager] 	Set network configuration path: /root/go/src/VppChain/capliper/networks/calipernetworkconfig.yaml
2022.03.05-21:19:21.495 info  [caliper] [cli-launch-manager] 	Set SUT type: fabric
2022.03.05-21:19:21.549 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2022.03.05-21:19:21.550 info  [caliper] [caliper-engine] 	Starting benchmark flow
2022.03.05-21:19:22.320 info  [caliper] [fabric-connector] 	Initializing gateway connector compatible with installed SDK: 2.2.3
2022.03.05-21:19:22.348 error [caliper] [cli-launch-manager] 	Unexpected error during benchmark execution: ValidationError: child "caliper" fails because ["sutOptions" is not allowed]. child "clients" fails because ["clients" is required]. child "channels" fails because ["channels" must be an object]. child "organizations" fails because ["organizations" must be an object]. child "orderers" fails because ["orderers" is required]. child "peers" fails because ["peers" is required]
Usage:
 caliper launch manager --caliper-bind-sut fabric:1.4 [other options]
```
**I think it's "oderers" issue, but I don't know how to config the "orderers", when I add this code in network config ** 
 ```
  "orderers": {
    "orderer0.vpp.com": {
      "url": "grpcs://101.43.195.188:7008",
      "grpcOptions": {
        "ssl-target-name-override": "orderer0.vpp.com"
      },
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nMIICijCCAjCgAwIBAgIUPOQhQd3mQhdmU2dEQ9BhmHyLk7UwCgYIKoZIzj0EAwIw\nYjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRAwDgYDVQQKDAd2cHAuY29tMRYwFAYDVQQDDA10bHNjYS52cHAu\nY29tMB4XDTIyMDMwNTA5MjYwNloXDTMyMDMwMjA5MjYwNlowYjELMAkGA1UEBhMC\nVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAw\nDgYDVQQKDAd2cHAuY29tMRYwFAYDVQQDDA10bHNjYS52cHAuY29tMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEAoxAjUzr2yAxvDKV2sw/hRo3nU0tXUKjOurMcj7U\nbNS7kyvwnQnMFnvSkJnYF1wIN/DV5/+dbU4rJaJC/wh7d6OBwzCBwDAdBgNVHQ4E\nFgQU2pa3lMMDxMsx91mMZGYjy4YQpGQwHwYDVR0jBBgwFoAU2pa3lMMDxMsx91mM\nZGYjy4YQpGQwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l\nBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMD4GA1UdEQQ3MDWHBGUrw7yCDXRsc2Nh\nLnZwcC5jb22CDXRsc2NhLXZwcC1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjO\nPQQDAgNIADBFAiAbVrxzP7uKAGWZP3h1rCEZBhereBSqCbPfAr9y2hjmzwIhAJZg\naf7n/7822GS3wfR5iFQLFTtRbDKHyw4h6Y10TGRT\n-----END CERTIFICATE-----"
      }
    },
    "orderer1.vpp.com": {
      "url": "grpcs://101.43.195.188:7009",
      "grpcOptions": {
        "ssl-target-name-override": "orderer1.vpp.com"
      },
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nMIICijCCAjCgAwIBAgIUPOQhQd3mQhdmU2dEQ9BhmHyLk7UwCgYIKoZIzj0EAwIw\nYjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRAwDgYDVQQKDAd2cHAuY29tMRYwFAYDVQQDDA10bHNjYS52cHAu\nY29tMB4XDTIyMDMwNTA5MjYwNloXDTMyMDMwMjA5MjYwNlowYjELMAkGA1UEBhMC\nVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAw\nDgYDVQQKDAd2cHAuY29tMRYwFAYDVQQDDA10bHNjYS52cHAuY29tMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEAoxAjUzr2yAxvDKV2sw/hRo3nU0tXUKjOurMcj7U\nbNS7kyvwnQnMFnvSkJnYF1wIN/DV5/+dbU4rJaJC/wh7d6OBwzCBwDAdBgNVHQ4E\nFgQU2pa3lMMDxMsx91mMZGYjy4YQpGQwHwYDVR0jBBgwFoAU2pa3lMMDxMsx91mM\nZGYjy4YQpGQwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l\nBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMD4GA1UdEQQ3MDWHBGUrw7yCDXRsc2Nh\nLnZwcC5jb22CDXRsc2NhLXZwcC1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjO\nPQQDAgNIADBFAiAbVrxzP7uKAGWZP3h1rCEZBhereBSqCbPfAr9y2hjmzwIhAJZg\naf7n/7822GS3wfR5iFQLFTtRbDKHyw4h6Y10TGRT\n-----END CERTIFICATE-----"
      }
    }
  },
```
this cause more errors:
```
2022.03.05-21:11:56.816 error [caliper] [cli-launch-manager] 	Unexpected error during benchmark execution: Error: Invalid "vppchannel" channel configuration: child "orderers" fails because ["orderers" is required]. child "peers" fails because ["peers" is required]
```
**The network config is :**
``` {
  "name": "test-vppsite",
  "version": "1.0",
  "info": {
    "details": {
      "Version": "2.2.0",
      "PeerOrgs": "org0.vpp.com,org1.vpp.com,org2.vpp.com",
      "NumberOfPeers": 5,
      "OrdererOrgs": "vpp.com",
      "NumberOfOrderers": 2,
      "Orderer": "Raft",
      "StateDB": "golevel"
    }
  },  
  "caliper": {
    "blockchain": "fabric"
  },
  "clients": {
    "Admin@org2.vpp.com": {
      "client": {
        "credentialStore": {
          "path": "tmp/org1",
          "cryptoStore": {"path": "tmp/org1"}
        },
        "organization": "org2.vpp.com",
        "clientPrivateKey": {
          "path": "../../vars/keyfiles/peerOrganizations/org2.vpp.com/users/Admin@org2.vpp.com/msp/keystore/priv_sk"
        },
        "clientSignedCert": {
          "path": "../../vars/keyfiles/peerOrganizations/org2.vpp.com/users/Admin@org2.vpp.com/msp/signcerts/Admin@org2.vpp.com-cert.pem"
        },
        "connection": {
          "timeout": { "peer": { "endorser": "300" } }
        }
      }
    }
  },
  "channels": {
      "vppchannel": {
          "created" : true,
          "contracts": [
              { "id": "vppcc", "version": "0.0.3" }
          ]
      }
  },
  "organizations":{
    "org2.vpp.com": {
      "mspid": "org2-vpp-com",
      "peers": [
        "peer0.org2.vpp.com"
      ],
      "certificateAuthorities": [
         "ca0.org2.vpp.com"
      ],
      "adminPrivateKey": {
        "path": "../../vars/keyfiles/peerOrganizations/org2.vpp.com/users/Admin@org2.vpp.com/msp/keystore/priv_sk"
      },
      "signedCert": {
        "path": "../../vars/keyfiles/peerOrganizations/org2.vpp.com/users/Admin@org2.vpp.com/msp/signcerts/Admin@org2.vpp.com-cert.pem"
      }
    }
  },
  "peers": {
    "peer0.org2.vpp.com": {
      "url": "grpcs://101.43.195.188:7007",
      "grpcOptions": {
        "ssl-target-name-override": "peer0.org2.vpp.com",
        "hostnameOverride": "peer0.org2.vpp.com"
      },
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nMIICqzCCAlKgAwIBAgIUXLcwrK00XIm9syXrwmbZfk+TaZkwCgYIKoZIzj0EAwIw\nbTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRUwEwYDVQQKDAxvcmcyLnZwcC5jb20xHDAaBgNVBAMME3Rsc2Nh\nMC5vcmcyLnZwcC5jb20wHhcNMjIwMzA1MDkyNTQ5WhcNMzIwMzAyMDkyNTQ5WjBt\nMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcM\nB1JhbGVpZ2gxFTATBgNVBAoMDG9yZzIudnBwLmNvbTEcMBoGA1UEAwwTdGxzY2Ew\nLm9yZzIudnBwLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOYAnRDSpQJ9\nitJV2HYREnpIG0ASzRY0lAMD/xTM1mIsZ2la0pQnq50nBTyJzy02HpidhaVUocqE\nQTy3xl7kTTyjgc8wgcwwHQYDVR0OBBYEFJ86MoSrHICzdxOfGqEK4dsEbd1IMB8G\nA1UdIwQYMBaAFJ86MoSrHICzdxOfGqEK4dsEbd1IMA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBK\nBgNVHREEQzBBhwRlK8O8ghN0bHNjYTAub3JnMi52cHAuY29tghN0bHNjYTAtb3Jn\nMi12cHAtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDRwAwRAIgBApt\ndK0X+1UbuU7/uYdVCEJkOsU0vY4+0Ht08z1HRzgCIDe+P9+OkxRy/ZwxwY8Sa3xD\nHXdSYokIgFnvCa5Spyvs\n-----END CERTIFICATE-----"
      }
    }
  },
  "certificateAuthorities": {
    "ca0.org2.vpp.com": {
      "url": "https://101.43.195.188:7002",
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nMIICnzCCAkagAwIBAgIUCkzfPbUUPXikwzi41FbkgcLyBgAwCgYIKoZIzj0EAwIw\najELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRUwEwYDVQQKDAxvcmcyLnZwcC5jb20xGTAXBgNVBAMMEGNhMC5v\ncmcyLnZwcC5jb20wHhcNMjIwMzA1MDkyNTQ5WhcNMzIwMzAyMDkyNTQ5WjBqMQsw\nCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1Jh\nbGVpZ2gxFTATBgNVBAoMDG9yZzIudnBwLmNvbTEZMBcGA1UEAwwQY2EwLm9yZzIu\ndnBwLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBeUiWX6RQFWrlewL6Iw\n/wnOpFIB725cYVzHVhf0qjZ5krEiuVWfxvMp+oZTV8EHQaIWRMvaGDDOREXaTwdH\nlk+jgckwgcYwHQYDVR0OBBYEFADKT69J5Xhv6YblzgFEUMntaydmMB8GA1UdIwQY\nMBaAFADKT69J5Xhv6YblzgFEUMntaydmMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0P\nAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBEBgNVHREE\nPTA7hwRlK8O8ghBjYTAub3JnMi52cHAuY29tghBjYTAtb3JnMi12cHAtY29tggls\nb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDRwAwRAIgKBdTzRtyyBqKR16Oya/R\n10iM/6ZjvTQdWMkstMY4mv0CIEieTdZ90dnc7yvBBnfm3vYBPwIUU5fjqu1dmD+K\n4YDR\n-----END CERTIFICATE-----"
      },
      "httpOptions": { "verify": "false" },
      "caName": "ca0"
    }
  }
}
```
**The benchmark config is:**
```
test:
    name: vppcc-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      - label: write test
        description: vppcc benchmark
        txNumber: 1000
        #txDuration: 60
        rateControl: 
          type: fixed-rate
          opts:
            tps: 50
        workload:
          module: ../workload/write.js
          arguments:
            contractId: vppcc
            randomSeed: 5000000
            userID: Admin
      - label: read test
        description: vppcc benchmark
        txNumber: 1000
        rateControl: 
          type: fixed-rate
          opts:
            tps: 50
        workload:
          module: ../workload/read.js
          arguments:
            contractId: vppcc
            randomSeed: 5000000
            userID: Admin
```

### What was the observed incorrect behavior?

the network config file isn't correct.

### Please provide the error logs and their surroundings.

```text
root@VM-24-3-ubuntu:~/go/src/VppChain/capliper# npx caliper launch manager --caliper-workspace ./ --caliper-networkconfig networks/calipernetworkconfig.yaml --caliper-benchconfig benchmarks/caliperbenchmarkconfig.yaml --caliper-flow-only-test --caliper-fabric-gateway-enabled
2022.03.05-21:19:21.493 info  [caliper] [cli-launch-manager] 	Set workspace path: /root/go/src/VppChain/capliper
2022.03.05-21:19:21.494 info  [caliper] [cli-launch-manager] 	Set benchmark configuration path: /root/go/src/VppChain/capliper/benchmarks/caliperbenchmarkconfig.yaml
2022.03.05-21:19:21.495 info  [caliper] [cli-launch-manager] 	Set network configuration path: /root/go/src/VppChain/capliper/networks/calipernetworkconfig.yaml
2022.03.05-21:19:21.495 info  [caliper] [cli-launch-manager] 	Set SUT type: fabric
2022.03.05-21:19:21.549 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2022.03.05-21:19:21.550 info  [caliper] [caliper-engine] 	Starting benchmark flow
2022.03.05-21:19:22.320 info  [caliper] [fabric-connector] 	Initializing gateway connector compatible with installed SDK: 2.2.3
2022.03.05-21:19:22.348 error [caliper] [cli-launch-manager] 	Unexpected error during benchmark execution: ValidationError: child "caliper" fails because ["sutOptions" is not allowed]. child "clients" fails because ["clients" is required]. child "channels" fails because ["channels" must be an object]. child "organizations" fails because ["organizations" must be an object]. child "orderers" fails because ["orderers" is required]. child "peers" fails because ["peers" is required]
Usage:
 caliper launch manager --caliper-bind-sut fabric:1.4 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error [ValidationError]: child "caliper" fails because ["sutOptions" is not allowed]. child "clients" fails because ["clients" is required]. child "channels" fails because ["channels" must be an object]. child "organizations" fails because ["organizations" must be an object]. child "orderers" fails because ["orderers" is required]. child "peers" fails because ["peers" is required]
    at Object.exports.process (/root/go/src/VppChain/capliper/node_modules/@hapi/joi/lib/errors.js:202:19)
    at internals.Object._validateWithOptions (/root/go/src/VppChain/capliper/node_modules/@hapi/joi/lib/types/any/index.js:763:31)
    at module.exports.internals.Any.root.validate (/root/go/src/VppChain/capliper/node_modules/@hapi/joi/lib/index.js:145:23)
    at Function._validateTopLevel (/root/go/src/VppChain/capliper/node_modules/@hyperledger/caliper-fabric/lib/configValidator.js:208:26)
    at Function.validateNetwork (/root/go/src/VppChain/capliper/node_modules/@hyperledger/caliper-fabric/lib/configValidator.js:58:25)
    at CaliperEngine.connectorFactory [as adapterFactory] (/root/go/src/VppChain/capliper/node_modules/@hyperledger/caliper-fabric/lib/FabricConnectorFactory.js:127:25)
    at CaliperEngine.run (/root/go/src/VppChain/capliper/node_modules/@hyperledger/caliper-core/lib/manager/caliper-engine.js:93:36)
    at Function.handler (/root/go/src/VppChain/capliper/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:62:43)
    at Object.module.exports.handler (/root/go/src/VppChain/capliper/node_modules/@hyperledger/caliper-cli/lib/launch/launchManagerCommand.js:46:44)
    at Object.runCommand (/root/go/src/VppChain/capliper/node_modules/yargs/lib/command.js:240:40) {
  isJoi: true,
  details: [
    {
      message: '"sutOptions" is not allowed',
      path: [Array],
      type: 'object.allowUnknown',
      context: [Object]
    },
    {
      message: '"clients" is required',
      path: [Array],
      type: 'any.required',
      context: [Object]
    },
    {
      message: '"channels" must be an object',
      path: [Array],
      type: 'object.base',
      context: [Object]
    },
    {
      message: '"organizations" must be an object',
      path: [Array],
      type: 'object.base',
      context: [Object]
    },
    {
      message: '"orderers" is required',
      path: [Array],
      type: 'any.required',
      context: [Object]
    },
    {
      message: '"peers" is required',
      path: [Array],
      type: 'any.required',
      context: [Object]
    }
  ],
  _object: {
    name: 'vppcc test',
    version: '1.0',
    caliper: { blockchain: 'fabric', sutOptions: [Object] },
    channels: [ [Object] ],
    organizations: [ [Object] ]
  },
  annotate: [Function (anonymous)]
}


```
```


### Please provide your benchmark configuration file content, if possible.

_No response_

### Please provide your network configuration file content, if possible.

_No response_

### Please provide your workload module content, if possible.

_No response_

### Please provide any additional information you deem relevant to the error.

_No response_

**Comment by davidkel** [comment]
Looks like you are trying to use the legacy caliper network config for hyperledger fabric which is documented here https://hyperledger.github.io/caliper/v0.4.2/fabric-config/legacy/
I think you haven't described the orderers or peers in the channel block of your configuration, which is what the rather cryptic error messages are saying. Also `sutOptions` isn't part of the legacy format. 

Note that in the next release of caliper this legacy is being dropped for the new network configuration format described here https://hyperledger.github.io/caliper/v0.4.2/fabric-config/new/

Fabric networks should be configured to allow for a client to discover the network and so whoever built the network should also be able to create a connection profile which provides a standard for client applications to be able to connect to that network. So a fabric network that is correctly configured can be discovered and the connection profile only has to list information for a single organisation and a peer (or peers) in that organisation that can be used to discover the network.

**Comment by miamhe** [comment]
> 看起来您正在尝试将旧版 caliper 网络配置用于超级账本结构，此处记录https://hyperledger.github.io/caliper/v0.4.2/fabric-config/legacy/ 我认为您没有描述订购者或配置的通道块中的对等点，这就是相当神秘的错误消息所说的。也不`sutOptions`是传统格式的一部分。
> 
> 请注意，在 caliper 的下一个版本中，此旧版将被删除，以用于此处描述的新网络配置格式https://hyperledger.github.io/caliper/v0.4.2/fabric-config/new/
> 
> Fabric 网络应配置为允许客户端发现网络，因此构建网络的任何人也应该能够创建连接配置文件，该配置文件为客户端应用程序能够连接到该网络提供标准。因此，可以发现正确配置的结构网络，并且连接配置文件只需列出单个组织和该组织中可用于发现网络的对等点（或多个对等点）的信息。

**Comment by miamhe** [comment]
Thanks, I tried it again by  the new network configuration. it did work. And I find all path must be absolute path.Thanks again!
