### ISSUE TITLE
Test runs should not fail if it's not possible to extract prometheus data

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1267]
In the case of prometheus we can specify a monitor to extract data from prometheus, however if prometheus isn't available you get
```
Error: connect ECONNREFUSED 127.0.0.1:9090
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9090
}
```
And caliper terminates. 

This is really annoying because now I can't use a benchmark which defines a monitor for prometheus if I choose not to have prometheus running.

It should not fail the run, just report a warning or at least have an option that stops it from failing the run

**Comment by davidkel** [comment]
there is no issue with a docker monitor and it also looks like from the code that if an attempt to push data to a prometheus push gateway fails then it will just log it, so I think that this is more of a bug than an enhancement, so changing to bug. The only thing is that from an integration test point of view if for some reason it is supposed to work but doesn't (eg url is wrong and so prometheus is not found) then the build would still pass.
