### ISSUE TITLE
Caliper Benchmark failing with latest Fabric Connector

### ISSUE THREAD

**Issue by subarna-SE** [hyperledger/caliper#1307]
### Which Caliper version are you using?

0.5.0-unstable-20220407143902

### Which Node.JS version are you using?

14.19.1

### Which operating system are you using?

Ubuntu 20.04

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

`npx caliper launch manager --caliper-workspace ./ --caliper-networkconfig networks/fabric/test-network.yaml --caliper-benchconfig benchmarks/api/fabric/contract/get-asset.yaml --caliper-flow-only-test --caliper-fabric-gateway-enabled`

After performing benchmark for one round (Round 0) successfully, when caliper is going for next round (Round 1), it is giving error ‘Channel has been shut down’. same error is coming for all gateway transactions.

### What was the observed incorrect behavior?

Benchmark did not complete successfully with latest Fabric Connector

### Please provide the error logs and their surroundings.

```text
2022.04.08-02:52:27.317 info  [caliper] [worker-message-handler] 	Worker#9 is starting Round#1
2022.04.08-02:52:27.320 info  [caliper] [caliper-worker] 	Worker #9 starting workload loop
2022.04.08-02:52:29.295 error [caliper] [connectors/peer-gateway/PeerGateway] 	Failed to perform query transaction [getAsset] using arguments [client0_1000_8],  with error: Error: Channel has been shut down
    at ChannelImplementation.createCall (/root/caliper-workspace/caliper-benchmarks/node_modules/@grpc/grpc-js/build/src/channel.js:514:19)
    at getCall (/root/caliper-workspace/caliper-benchmarks/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:255:26)
    at getBottomInterceptingCall (/root/caliper-workspace/caliper-benchmarks/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:381:18)
    at /root/caliper-workspace/caliper-benchmarks/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:429:26
    at Object.getInterceptingCall (/root/caliper-workspace/caliper-benchmarks/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:430:12)
    at Client.makeUnaryRequest (/root/caliper-workspace/caliper-benchmarks/node_modules/@grpc/grpc-js/build/src/client.js:149:44)
    at /root/caliper-workspace/caliper-benchmarks/node_modules/@hyperledger/fabric-gateway/dist/client.js:42:110
    at new Promise (<anonymous>)
    at GatewayClientImpl.evaluate (/root/caliper-workspace/caliper-benchmarks/node_modules/@hyperledger/fabric-gateway/dist/client.js:42:16)
    at ProposalImpl.evaluate (/root/caliper-workspace/caliper-benchmarks/node_modules/@hyperledger/fabric-gateway/dist/proposal.js:50:96)
```

**Comment by davidkel** [comment]
Addressed by #1310
