### ISSUE TITLE
create channel fail.

### ISSUE THREAD

**Issue by lotty02cho** [hyperledger/caliper#152]
I try to start caliper but there is some problem.

`node benchmark/simple/main.js -c config.json -n fabric.json`

`TAP version 13
# #######Caliper Test######
# create mychannel......
not ok 1 Failed to create channels Error: create status is FORBIDDEN at channel.organizations.reduce.then.then.then (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:145:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:159:19)
    stack: |-
      Error: Failed to create channels Error: create status is FORBIDDEN
          at channel.organizations.reduce.then.then.then (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:145:43)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:159:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

1..1
# tests 1
# pass  0
# fail  1
`

**Comment by sathishNS** [comment]
Try running node main.js -c config.json without giving fabric.json. Make sure you followed all the pre-reqs before running this and cross check the config and fabric.json.

**Comment by houqinghui** [comment]
@lotty02cho   can you list the steps to reproduce, if you have not solved the problem?

**Comment by aklenik** [comment]
@lotty02cho Any progress on this issue?
