### ISSUE TITLE
fabirc 1.1 error

### ISSUE THREAD

**Issue by gantleman** [hyperledger/caliper#155]
sur@ubuntu:~/caliper$ node benchmark/simple/main.js -c config.json -n fabric.json
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d
(node:88593) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Creating network "simplenetwork_default" with the default driver
Creating simplenetwork_ca_1   ... done
Creating ca_peerOrg1            ... done
Creating ca_peerOrg2            ... done
Creating simplenetwork_peer_1   ... done
Creating orderer.example.com  ... done
Creating peer1.org2.example.com ... done
Creating peer1.org1.example.com ... done
Creating peer0.org2.example.com ... done
Creating peer0.org1.example.com ... done
# create mychannel......
ok 1 created mychannel successfully
# Sleep 5s......
# Join channel......
# join mychannel
not ok 2 Failed to join peers, TypeError: Cannot read property 'getConnectivityState' of undefined at EventHub._checkConnection (/home/sur/caliper/node_modules/_fabric-client@1.1.0@fabric-client/lib/EventHub.js:479:39) at EventHub.registerBlockEvent (/home/sur/caliper/node_modules/_fabric-client@1.1.0@fabric-client/lib/EventHub.js:658:8) at Promise (/home/sur/caliper/src/fabric/join-channel.js:139:20) at new Promise (<anonymous>) at eventhubs.forEach (/home/sur/caliper/src/fabric/join-channel.js:136:29) at Array.forEach (<anonymous>) at Client.newDefaultKeyValueStore.then.then.then.then (/home/sur/caliper/src/fabric/join-channel.js:135:19) at <anonymous>
  ---
    operator: fail
    at: channels.reduce.then.catch (/home/sur/caliper/src/fabric/join-channel.js:215:19)
    stack: |-
      Error: Failed to join peers, TypeError: Cannot read property 'getConnectivityState' of undefined
          at EventHub._checkConnection (/home/sur/caliper/node_modules/_fabric-client@1.1.0@fabric-client/lib/EventHub.js:479:39)
          at EventHub.registerBlockEvent (/home/sur/caliper/node_modules/_fabric-client@1.1.0@fabric-client/lib/EventHub.js:658:8)
          at Promise (/home/sur/caliper/src/fabric/join-channel.js:139:20)
          at new Promise (<anonymous>)
          at eventhubs.forEach (/home/sur/caliper/src/fabric/join-channel.js:136:29)
          at Array.forEach (<anonymous>)
          at Client.newDefaultKeyValueStore.then.then.then.then (/home/sur/caliper/src/fabric/join-channel.js:135:19)
          at <anonymous>
          at Test.assert [as _assert] (/home/sur/caliper/node_modules/_tape@4.9.1@tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/sur/caliper/node_modules/_tape@4.9.1@tape/lib/test.js:76:32)
          at Test.fail (/home/sur/caliper/node_modules/_tape@4.9.1@tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/sur/caliper/node_modules/_tape@4.9.1@tape/lib/test.js:76:32)
          at channels.reduce.then.catch (/home/sur/caliper/src/fabric/join-channel.js:215:19)
          at <anonymous>
  ...
fabric.init() failed, Error: Fabric: Join channel failed
    at channels.reduce.then.catch (/home/sur/caliper/src/fabric/join-channel.js:216:31)
    at <anonymous>
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: Join channel failed
    at channels.reduce.then.catch (/home/sur/caliper/src/fabric/join-channel.js:216:31)
    at <anonymous>
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
/home/sur/caliper/node_modules/_fabric-client@1.1.0@fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                    ^

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/sur/caliper/node_modules/_fabric-client@1.1.0@fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/sur/caliper/node_modules/_grpc@1.13.1@grpc/src/client_interceptors.js:1276:19)
    at InterceptingListener.recvMessageWithContext (/home/sur/caliper/node_modules/_grpc@1.13.1@grpc/src/client_interceptors.js:603:19)
    at /home/sur/caliper/node_modules/_grpc@1.13.1@grpc/src/client_interceptors.js:702:14

**Comment by fooock** [comment]
@gantleman install grpc version 1.10.1 instead of 1.13.1

```
npm install grpc@1.10.1
```

**Comment by panyu4** [comment]
@fooock you are right.
And long time no activity, I think this is fixed. I am closing this issue.
