### ISSUE TITLE
How to disable TLS?

### ISSUE THREAD

**Issue by rupc** [hyperledger/caliper#195]
Hi, I want to run benchmark on test network which has non-TLS enabled.
I configured TLS_ENABLE options for each ca, orderer and peer in docker-compose.yaml in 
 network/fabric/simplenetwork. 
But after launching "node benchmark/simplenetwork/main, I got following errors.

```
 Creating peer1.org1.example.com ... done
# create mychannel......
E1018 10:57:49.422421682    2748 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: Connect Failed\n    at createStatusError (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)\n    at ClientDuplexStream._emitStatusIfDone (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:270:19)\n    at ClientDuplexStream._readsDone (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:236:8)\n    at readCallback (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:296:12)"
not ok 1 Failed to create channels Error: SERVICE_UNAVAILABLE at ClientDuplexStream.<anonymous> (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/Orderer.js:136:21) at emitOne (events.js:116:13) at ClientDuplexStream.emit (events.js:211:7) at ClientDuplexStream._emitStatusIfDone (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:271:12) at ClientDuplexStream._readsDone (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:236:8) at readCallback (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:296:12)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/home/jyr/go/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:159:19)
    stack: |-
      Error: Failed to create channels Error: SERVICE_UNAVAILABLE
          at ClientDuplexStream.<anonymous> (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/Orderer.js:136:21)
          at emitOne (events.js:116:13)
          at ClientDuplexStream.emit (events.js:211:7)
          at ClientDuplexStream._emitStatusIfDone (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:271:12)
          at ClientDuplexStream._readsDone (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:236:8)
          at readCallback (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:296:12)
          at Test.assert [as _assert] (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/jyr/go/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/home/jyr/go/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:159:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/jyr/go/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/jyr/go/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

It seems that client side will be needed to be configured not to use TLS. 
How do I succeed at using non-TLS network in caliper?

**Comment by aklenik** [comment]
@rupc See [this file](https://github.com/hyperledger/caliper/blob/master/network/fabric/2-org-1-peer/docker-compose.yaml) for an example docker-compose network definition that has TLS disabled.

**Comment by rupc** [comment]
@aklenik I tried, but it still gets an error. I attached logs from orderer

```
2018-10-18 20:42:26.909 UTC [orderer/common/server] Start -> INFO 0c5 Starting orderer:
 Version: 1.1.0
 Go version: go1.9.2
 OS/Arch: linux/amd64
 Experimental features: false
2018-10-18 20:42:26.909 UTC [orderer/common/server] Start -> INFO 0c6 Beginning to serve requests
2018-10-18 20:42:34.248 UTC [grpc] Printf -> DEBU 0c7 transport: http2Server.HandleStreams received bogus greeting from client: "\x16\x03\x01\x00\xc1\x01\x00\x00\xbd\x03\x03\x97-\x03[\x13\x95#\xf47{\xee\xb1\xe2"
2018-10-18 20:42:35.247 UTC [grpc] Printf -> DEBU 0c8 transport: http2Server.HandleStreams received bogus greeting from client: "\x16\x03\x01\x00\xc1\x01\x00\x00\xbd\x03\x03i\x8b8(\xdc\xca\xe2\x83\a\x04nU\xea"

```

**Comment by aklenik** [comment]
@rupc How are you endpoints specified in the `fabric.json` network configuration? `grpcs/https` or `grpc/http`? Try the latter. If it doesn't solve your problem, share your configuration files (preferably as GitHub gist) and I'll try to reproduce your problem.

**Comment by aklenik** [comment]
@rupc Did you resolve the issue?

**Comment by rupc** [comment]
Actually, no.  After I modified the instructions that you mentioned, an error from different place which seems to be irrelevant came out. The error is about docker network settings, indicating network namespace issues. I think the error is related in some way, but I can't figure how. (I just switched to TLS-enabled version.) But thanks for your concern.

**Comment by deenario** [comment]
Disabling TLS in hyperledger fabric was a hassle to figure out but i did for BYFN in fabric samples.
If you want to read that in detail. I did also write a blog on it.
https://www.devprovider.com/hyperledger-fabric-tls-disabled/
