### ISSUE TITLE
How to change MaxMessageCount

### ISSUE THREAD

**Issue by kulics** [hyperledger/caliper#210]
I want to change the block size for testing, but I tried to modify the configuration without success.

## Context
I changed the configuration and regenerated the corresponding file, but an exception occurred when I tried to rerun. Detailed documentation should be provided on how to modify the configuration for testing. Now I can't tell where the exception is causing the problem.

## Expected Behavior
Run correctly

## Actual Behavior
There are two errors

1. not ok 1 Failed to create channels Error: create status is SERVICE_UNAVAILABLE at channel.organizations.reduce.then.then.then (/home/fabric/caliper/src/fabric/create-channel.js:145:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
1. not ok 2 Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate proposal due to error: Error: Failed to initialize the channelError: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP] at /home/fabric/caliper/node_modules/fabric-client/lib/Channel.js:159:28 at <anonymous> at Client.newDefaultKeyValueStore.then.then.then (/home/fabric/caliper/src/fabric/e2eUtils.js:316:15) at <anonymous> at Client.newDefaultKeyValueStore.then.then.then.then (/home/fabric/caliper/src/fabric/e2eUtils.js:375:15) at <anonymous> at Client.newDefaultKeyValueStore.then.then.then.then.then (/home/fabric/caliper/src/fabric/e2eUtils.js:385:15) at <anonymous>

## Steps to Reproduce
1. change MaxMessageCount value from caliper/network/fabric/simplenetwork/.configtx.yaml
2. run 
```
configtxgen -profile TwoOrgsOrdererGenesis -outputBlock twoorgs.genesis.block
configtxgen -profile TwoOrgsChannel -outputCreateChannelTx mychannel.tx -channelID mychannel 
```
3. run main.js in caliper/benchmark/simple
```
node main.js 
```
4. then appear 
```
not ok 1 Failed to create channels Error: create status is SERVICE_UNAVAILABLE at channel.organizations.reduce.then.then.then (/home/fabric/caliper/src/fabric/create-channel.js:145:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/home/fabric/caliper/src/fabric/create-channel.js:159:19)
    stack: |-
      Error: Failed to create channels Error: create status is SERVICE_UNAVAILABLE
          at channel.organizations.reduce.then.then.then (/home/fabric/caliper/src/fabric/create-channel.js:145:43)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/home/fabric/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/fabric/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/fabric/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/fabric/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/home/fabric/caliper/src/fabric/create-channel.js:159:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
```
5. then I set this in fabric.json
```
    "channel": [
      {
        "name": "mychannel",
        "config": "network/fabric/simplenetwork/mychannel.tx",
        "organizations": ["org1", "org2"],
        "deployed": true // from false to true
      }
    ]
```
6.run again, appear that
```
ok 1 Installed chaincode simple successfully in all peers
# Instantiate chaincode......
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
    at new createStatusError (/home/fabric/caliper/node_modules/grpc/src/client.js:64:15)
    at /home/fabric/caliper/node_modules/grpc/src/client.js:583:15
error: [Channel.js]: getChannelConfig - Failed getting channel config. Error: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
    at new createStatusError (/home/fabric/caliper/node_modules/grpc/src/client.js:64:15)
    at /home/fabric/caliper/node_modules/grpc/src/client.js:583:15
error: [Channel.js]: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
    at new createStatusError (/home/fabric/caliper/node_modules/grpc/src/client.js:64:15)
    at /home/fabric/caliper/node_modules/grpc/src/client.js:583:15
not ok 2 Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate proposal due to error: Error: Failed to initialize the channelError: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP] at /home/fabric/caliper/node_modules/fabric-client/lib/Channel.js:159:28 at <anonymous> at Client.newDefaultKeyValueStore.then.then.then (/home/fabric/caliper/src/fabric/e2eUtils.js:316:15) at <anonymous> at Client.newDefaultKeyValueStore.then.then.then.then (/home/fabric/caliper/src/fabric/e2eUtils.js:375:15) at <anonymous> at Client.newDefaultKeyValueStore.then.then.then.then.then (/home/fabric/caliper/src/fabric/e2eUtils.js:385:15) at <anonymous>
  ---
    operator: fail
    at: chaincodes.reduce.then.catch (/home/fabric/caliper/src/fabric/instantiate-chaincode.js:60:19)
    stack: |-
      Error: Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate proposal due to error: Error: Failed to initialize the channelError: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
```

## Your Environment
* Version used: Fabric v1.1; Caliper vCurrent; configtxgen v1.1;
* Environment name and version: Node v8.11.3;
* Operating System and version:CentOS;

**Comment by weijinxy** [comment]
same question?  any solution? +1

**Comment by nklincoln** [comment]
@weijinxy - same answer as above. When you regenerate the crypto material, the PEM files change name. In the `generate.sh` script, there is a step in there that normalises these random file names so that caliper can use them during the setup and performance runs

**Comment by kulics** [comment]
@nklincoln I did not regenerate  crypto material, only genesis blocks and channels are generated.

**Comment by nklincoln** [comment]
@kulics did you change the relevant paths/variables in the docker compose files too (i see you renamed the genesis block etc)?

You will get *lots* more information if you perform a `docker logs <container>` that should help diagnose what is going wrong

**Comment by kulics** [comment]
@nklincoln no, I didn't change the docker compose file.
This is the git status -s
```
 M network/fabric/simplenetwork/generate.sh
 M network/fabric/simplenetwork/mychannel.tx
 M network/fabric/simplenetwork/twoorgs.genesis.block
```
The generate.sh diff
```
old mode 100644
new mode 100755
index 9289d88..c8d848b
--- a/network/fabric/simplenetwork/generate.sh
+++ b/network/fabric/simplenetwork/generate.sh
@@ -1,4 +1,4 @@
 #!/usr/bin/env bash
-~/go/src/github.com/hyperledger/fabric/build/bin/cryptogen generate --config=./
-~/go/src/github.com/hyperledger/fabric/build/bin/configtxgen -profile TwoOrgsOr
-~/go/src/github.com/hyperledger/fabric/build/bin/configtxgen -profile TwoOrgsCh
\ No newline at end of file
+#cryptogen generate --config=./crypto-config.yaml
+configtxgen -profile TwoOrgsOrdererGenesis -outputBlock twoorgs.genesis.block
+configtxgen -profile TwoOrgsChannel -outputCreateChannelTx mychannel.tx -channe
(END)
```
This is the full `node main.js` log
```
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d
Creating network "simplenetwork_default" with the default driver
Creating simplenetwork_peer_1_e5ff01a712d9 ... done
Creating ca_peerOrg1                       ... done
Creating ca_peerOrg2                       ... done
Creating simplenetwork_ca_1_7266490d51da   ... done
Creating orderer.example.com               ... done
Creating peer1.org1.example.com            ... done
Creating peer0.org2.example.com            ... done
Creating peer0.org1.example.com            ... done
Creating peer1.org2.example.com            ... done
# create mychannel......
not ok 1 Failed to create channels Error: create status is SERVICE_UNAVAILABLE at channel.organizations.reduce.then.then.then (/home/fabric/caliper/src/fabric/create-channel.js:145:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/home/fabric/caliper/src/fabric/create-channel.js:159:19)
    stack: |-
      Error: Failed to create channels Error: create status is SERVICE_UNAVAILABLE
          at channel.organizations.reduce.then.then.then (/home/fabric/caliper/src/fabric/create-channel.js:145:43)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/home/fabric/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/fabric/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/fabric/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/fabric/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/home/fabric/caliper/src/fabric/create-channel.js:159:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/fabric/caliper/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/fabric/caliper/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

1..1
# tests 1
# pass  0
# fail  1
``` 
This is the peer logs
```
2018-11-02 01:49:01.576 UTC [nodeCmd] serve -> INFO 001 Starting peer:
 Version: 1.1.0
 Go version: go1.9.2
 OS/Arch: linux/amd64
 Experimental features: false
 Chaincode:
  Base Image Version: 0.4.6
  Base Docker Namespace: hyperledger
  Base Docker Label: org.hyperledger.fabric
  Docker Namespace: hyperledger

2018-11-02 01:49:01.576 UTC [ledgermgmt] initialize -> INFO 002 Initializing ledger mgmt
2018-11-02 01:49:01.576 UTC [kvledger] NewProvider -> INFO 003 Initializing ledger provider
2018-11-02 01:49:01.914 UTC [kvledger] NewProvider -> INFO 004 ledger provider Initialized
2018-11-02 01:49:01.914 UTC [ledgermgmt] initialize -> INFO 005 ledger mgmt initialized
2018-11-02 01:49:01.914 UTC [peer] func1 -> INFO 006 Auto-detected peer address: 192.168.112.9:7051
2018-11-02 01:49:01.914 UTC [peer] func1 -> INFO 007 Returning peer1.org2.example.com:7051
2018-11-02 01:49:01.914 UTC [peer] func1 -> INFO 008 Auto-detected peer address: 192.168.112.9:7051
2018-11-02 01:49:01.914 UTC [peer] func1 -> INFO 009 Returning peer1.org2.example.com:7051
2018-11-02 01:49:01.918 UTC [nodeCmd] serve -> INFO 00a Starting peer with TLS enabled
2018-11-02 01:49:01.920 UTC [eventhub_producer] start -> INFO 00b Event processor started
2018-11-02 01:49:01.921 UTC [nodeCmd] computeChaincodeEndpoint -> INFO 00c Entering computeChaincodeEndpoint with peerHostname: peer1.org2.example.com
2018-11-02 01:49:01.921 UTC [nodeCmd] computeChaincodeEndpoint -> INFO 00d Exit with ccEndpoint: peer1.org2.example.com:7052
2018-11-02 01:49:01.921 UTC [nodeCmd] createChaincodeServer -> WARN 00e peer.chaincodeListenAddress is not set, using peer1.org2.example.com:7052
2018-11-02 01:49:01.924 UTC [chaincode] NewChaincodeSupport -> INFO 00f Chaincode support using peerAddress: peer1.org2.example.com:7052
2018-11-02 01:49:01.924 UTC [sccapi] registerSysCC -> INFO 010 system chaincode cscc(github.com/hyperledger/fabric/core/scc/cscc) registered
2018-11-02 01:49:01.924 UTC [sccapi] registerSysCC -> INFO 011 system chaincode lscc(github.com/hyperledger/fabric/core/scc/lscc) registered
2018-11-02 01:49:01.924 UTC [sccapi] registerSysCC -> INFO 012 system chaincode escc(github.com/hyperledger/fabric/core/scc/escc) registered
2018-11-02 01:49:01.924 UTC [sccapi] registerSysCC -> INFO 013 system chaincode vscc(github.com/hyperledger/fabric/core/scc/vscc) registered
2018-11-02 01:49:01.924 UTC [sccapi] registerSysCC -> INFO 014 system chaincode qscc(github.com/hyperledger/fabric/core/chaincode/qscc) registered
2018-11-02 01:49:01.926 UTC [gossip/service] func1 -> INFO 015 Initialize gossip with endpoint peer1.org2.example.com:7051 and bootstrap set [127.0.0.1:7051]
2018-11-02 01:49:01.928 UTC [msp] DeserializeIdentity -> INFO 016 Obtaining identity
2018-11-02 01:49:01.930 UTC [gossip/discovery] NewDiscoveryService -> INFO 017 Started {peer1.org2.example.com:7051 [] [11 68 119 38 191 58 43 167 239 184 224 155 16 24 189 30 86 123 122 208 19 44 255 163 132 195 78 56 113 245 171 250] peer1.org2.example.com:7051 <nil>} incTime is 1541123341930015909
2018-11-02 01:49:01.930 UTC [gossip/gossip] NewGossipService -> INFO 018 Creating gossip service with self membership of {peer1.org2.example.com:7051 [] [11 68 119 38 191 58 43 167 239 184 224 155 16 24 189 30 86 123 122 208 19 44 255 163 132 195 78 56 113 245 171 250] peer1.org2.example.com:7051 <nil>}
2018-11-02 01:49:01.932 UTC [gossip/gossip] start -> INFO 019 Gossip instance peer1.org2.example.com:7051 started
2018-11-02 01:49:01.933 UTC [cscc] Init -> INFO 01a Init CSCC
2018-11-02 01:49:01.933 UTC [sccapi] deploySysCC -> INFO 01b system chaincode cscc/(github.com/hyperledger/fabric/core/scc/cscc) deployed
2018-11-02 01:49:01.934 UTC [sccapi] deploySysCC -> INFO 01c system chaincode lscc/(github.com/hyperledger/fabric/core/scc/lscc) deployed
2018-11-02 01:49:01.935 UTC [escc] Init -> INFO 01d Successfully initialized ESCC
2018-11-02 01:49:01.935 UTC [sccapi] deploySysCC -> INFO 01e system chaincode escc/(github.com/hyperledger/fabric/core/scc/escc) deployed
2018-11-02 01:49:01.936 UTC [sccapi] deploySysCC -> INFO 01f system chaincode vscc/(github.com/hyperledger/fabric/core/scc/vscc) deployed
2018-11-02 01:49:01.936 UTC [qscc] Init -> INFO 020 Init QSCC
2018-11-02 01:49:01.937 UTC [sccapi] deploySysCC -> INFO 021 system chaincode qscc/(github.com/hyperledger/fabric/core/chaincode/qscc) deployed
2018-11-02 01:49:01.937 UTC [nodeCmd] initSysCCs -> INFO 022 Deployed system chaincodes
2018-11-02 01:49:01.937 UTC [nodeCmd] serve -> INFO 023 Starting peer with ID=[name:"peer1.org2.example.com" ], network ID=[dev], address=[peer1.org2.example.com:7051]
```
This is the orderer logs
```
2018-11-02 01:48:54.910 UTC [orderer/common/server] prettyPrintStruct -> INFO 001 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = true
	General.TLS.PrivateKey = "/etc/hyperledger/msp/orderer/tls/server.key"
	General.TLS.Certificate = "/etc/hyperledger/msp/orderer/tls/server.crt"
	General.TLS.RootCAs = [/etc/hyperledger/msp/orderer/tls/ca.crt /etc/hyperledger/msp/peerOrg1/tls/ca.crt /etc/hyperledger/msp/peerOrg2/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleInsecureSolo"
	General.SystemChannel = "testchainid"
	General.GenesisFile = "/etc/hyperledger/configtx/twoorgs.genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LogLevel = "info"
	General.LogFormat = "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
	General.LocalMSPDir = "/etc/hyperledger/msp/orderer/msp"
	General.LocalMSPID = "OrdererMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/etc/hyperledger/msp/orderer/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.PluginOpts =
	General.BCCSP.Pkcs11Opts =
	General.Authentication.TimeWindow = 15m0s
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
2018-11-02 01:48:54.911 UTC [orderer/common/server] initializeServerConfig -> INFO 002 Starting orderer with TLS enabled
2018-11-02 01:48:55.296 UTC [fsblkstorage] newBlockfileMgr -> INFO 003 Getting block information from block storage
2018-11-02 01:48:55.484 UTC [orderer/consensus/kafka] newChain -> INFO 004 [channel: testchainid] Starting chain with last persisted offset -3 and last recorded block 0
2018-11-02 01:48:55.484 UTC [orderer/commmon/multichannel] NewRegistrar -> INFO 005 Starting system channel 'testchainid' with genesis block hash 61574dbc1a4879f3e74cbb73a4d63e83f9406993ccb19aff3a9bc4681f47a907 and orderer type kafka
2018-11-02 01:48:55.485 UTC [orderer/common/server] Start -> INFO 006 Starting orderer:
 Version: 1.1.0
 Go version: go1.9.2
 OS/Arch: linux/amd64
 Experimental features: false
2018-11-02 01:48:55.485 UTC [orderer/common/server] Start -> INFO 007 Beginning to serve requests
2018-11-02 01:48:55.485 UTC [orderer/consensus/kafka] setupProducerForChannel -> INFO 008 [channel: testchainid] Setting up the producer for this channel...
2018-11-02 01:48:55.493 UTC [orderer/consensus/kafka] startThread -> INFO 009 [channel: testchainid] Producer set up successfully
2018-11-02 01:48:55.493 UTC [orderer/consensus/kafka] sendConnectMessage -> INFO 00a [channel: testchainid] About to post the CONNECT message...
2018-11-02 01:49:01.913 UTC [orderer/common/broadcast] Handle -> WARN 00b [channel: mychannel] Rejecting broadcast of message from 192.168.112.1:43534 with SERVICE_UNAVAILABLE: rejected by Consenter: will not enqueue, consenter for this channel hasn't started yet
```

Thank you for your help;

**Comment by nklincoln** [comment]
@kulics - if you do a `docker ps -a` are any containers showing in a stopped (error) state?

**Comment by kulics** [comment]
@nklincoln emmmmmm I checked it and didn't see anything like it.

**Comment by nklincoln** [comment]
@kulics - any errors showing in the ca container(s)?

**Comment by aklenik** [comment]
@kulics Based on the last log of the orderer, it isn't ready yet to serve requests, such as channel creation. Try the following: remove the start script from the config file, start the docker network manually, wait a few seconds, then start the benchmark.
