### ISSUE TITLE
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: Connect Failed 

### ISSUE THREAD

**Issue by Priyanshi52** [hyperledger/caliper#211]
# create mychannel......
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: Connect Failed\n    at createStatusError (/home/caliper-master/node_modules/grpc/src/client.js:64:15)\n    at ClientDuplexStream._emitStatusIfDone (/home/caliper-master/node_modules/grpc/src/client.js:270:19)\n    at ClientDuplexStream._readsDone (/home/caliper-master/node_modules/grpc/src/client.js:236:8)\n    at readCallback (/home/caliper-master/node_modules/grpc/src/client.js:296:12)"
not ok 1 Failed to create channels Error: SERVICE_UNAVAILABLE at ClientDuplexStream.<anonymous> (/home/caliper-master/node_modules/fabric-client/lib/Orderer.js:136:21) at emitOne (events.js:116:13) at ClientDuplexStream.emit (events.js:211:7) at ClientDuplexStream._emitStatusIfDone (/home/caliper-master/node_modules/grpc/src/client.js:271:12) at ClientDuplexStream._readsDone (/home/caliper-master/node_modules/grpc/src/client.js:236:8) at readCallback (/home/caliper-master/node_modules/grpc/src/client.js:296:12)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/home/caliper-master/src/fabric/create-channel.js:159:19)
    stack: |-
      Error: Failed to create channels Error: SERVICE_UNAVAILABLE
          at ClientDuplexStream.<anonymous> (/home/caliper-master/node_modules/fabric-client/lib/Orderer.js:136:21)
          at emitOne (events.js:116:13)
          at ClientDuplexStream.emit (events.js:211:7)
          at ClientDuplexStream._emitStatusIfDone (/home/caliper-master/node_modules/grpc/src/client.js:271:12)
          at ClientDuplexStream._readsDone (/home/caliper-master/node_modules/grpc/src/client.js:236:8)
          at readCallback (/home/caliper-master/node_modules/grpc/src/client.js:296:12)
          at Test.assert [as _assert] (/home/caliper-master/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/caliper-master/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/caliper-master/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/caliper-master/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/home/caliper-master/src/fabric/create-channel.js:159:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:189:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/caliper-master/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/caliper-master/src/fabric/create-channel.js:160:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
Removing peer1.org1.example.com ... done
Removing peer1.org2.example.com ... done
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca_peerOrg2 ... done
Removing simplenetwork_peer_1 ... done
Removing orderer.example.com ... done
Removing simplenetwork_ca_1 ... done
Removing ca_peerOrg1 ... done
Removing network simplenetwork_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images

1..1
# tests 1
# pass  0
# fail  1

Running caliper on raspberry pi 3 model b.

**Comment by zsh122958** [comment]
Have you solved your problem?I have the same problem

**Comment by Priyanshi52** [comment]
No. Not yet

**Comment by houqinghui** [comment]
the problem is like the issue #109 , 
Please try to stop and remove all fabric containers first, then run the test again.
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)

**Comment by aklenik** [comment]
@Priyanshi52 @zsh122958 Also take a look at Issue #210, it has the same error. Also, can you provide the logs of the orderer node (directly here in a formatted manner, or as a gist)?

**Comment by Priyanshi52** [comment]
@aklenik Thanks for your response, I narrowed down the actual issue may be, the above issue caused because of following issue
on running **docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up**

I got 

Creating network "simplenetwork_default" with the default driver
Creating orderer.example.com
Creating simplenetwork_ca_1
Creating simplenetwork_peer_1
Creating ca_peerOrg2
Creating ca_peerOrg1
Creating peer0.org2.example.com
Creating peer1.org1.example.com
Creating peer0.org1.example.com
Creating peer1.org2.example.com
Attaching to orderer.example.com, simplenetwork_peer_1, simplenetwork_ca_1, ca_peerOrg1, ca_peerOrg2, peer1.org1.example.com, peer0.org2.example.com, peer1.org2.example.com, peer0.org1.example.com
orderer.example.com       | standard_init_linux.go:190: exec user process caused "exec format error"
peer_1                    | standard_init_linux.go:190: exec user process caused "exec format error"
orderer.example.com exited with code 1
ca_peerOrg1               | standard_init_linux.go:190: exec user process caused "exec format error"
simplenetwork_peer_1 exited with code 1
ca_1                      | standard_init_linux.go:190: exec user process caused "exec format error"
ca_peerOrg1 exited with code 1
ca_peerOrg2               | standard_init_linux.go:190: exec user process caused "exec format error"
peer1.org1.example.com    | standard_init_linux.go:190: exec user process caused "exec format error"
peer0.org2.example.com    | standard_init_linux.go:190: exec user process caused "exec format error"
ca_peerOrg2 exited with code 1
simplenetwork_ca_1 exited with code 1
peer0.org1.example.com    | standard_init_linux.go:190: exec user process caused "exec format error"
peer1.org2.example.com    | standard_init_linux.go:190: exec user process caused "exec format error"
peer1.org1.example.com exited with code 1
peer0.org2.example.com exited with code 1
peer1.org2.example.com exited with code 1
peer0.org1.example.com exited with code 1

I am running it on Raspberry Pi which has **Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux** architecture.

**Comment by Priyanshi52** [comment]
@aklenik please see issue #214

**Comment by ShruthieS** [comment]
I have distributed network(1 org 2 peers 1 orderer setup all are running in 3 different VMs). Query test using caliper is successful and I am able to see the report for query but while trying to invoke the existing chaincode or while installing a new chaincode, I am facing the following issue.

error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n at Object.exports.createStatusError (/home/xx/caliper-benchmarks/node_modules/grpc/src/common.js:91:15)\n at ClientDuplexStream._emitStatusIfDone (/home/xx/caliper-benchmarks/node_modules/grpc/src/client.js:233:26)\n at ClientDuplexStream._receiveStatus (/home/xx/caliper-benchmarks/node_modules/grpc/src/client.js:211:8)\n at Object.onReceiveStatus (/home/xx/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:1306:15)\n at InterceptingListener._callNext (/home/xx/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:568:42)\n at InterceptingListener.onReceiveStatus (/home/xx/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:618:8)\n at /home/xx/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:1123:18" 2020.04.29-12:22:12.094 error [caliper] [caliper-engine] Error while performing "install" step: Error: Orderer error for instantiating W1CC@v0 in composerchannelrest: SERVICE_UNAVAILABLE

Do you have any suggestions on how I can resolve this issue?

**Comment by aklenik** [comment]
@ShruthieS The error indicates that the specified endpoint can't be connected to, or the connection is rejected. See the orderer-side logs for more details.
