### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lxb325710** [hyperledger/caliper#235]
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Write failed
    at new createStatusError (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Write failed
    at new createStatusError (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client.js:583:15
error: [join-channel.js]: Failed to join peers: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [join-channel.js]: Failed to join peers: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [join-channel.js]: Failed to join peers: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [fabric.js]: Fabric initialization failed: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [fabric.js]: Fabric initialization failed: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [fabric.js]: Fabric initialization failed: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [bench-flow.js]: Error: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [bench-flow.js]: Error: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>
error: [bench-flow.js]: Error: TypeError: Cannot read property 'stack' of undefined
    at joinChannel (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:162:85)
    at <anonymous>

**Comment by aklenik** [comment]
@lxb325710 Which benchmark are you running on which sample network? And at which part of the test are you getting this error (init phase, TX submitting phase)?

**Comment by panyu4** [comment]
This is an inactive issue for long time. @lxb325710  If you still have the same problem, reopen it.
