### ISSUE TITLE
Hyperleder Fabric configuration of multi peers

### ISSUE THREAD

**Issue by dattajadhav44** [hyperledger/caliper#245]
I have modified the "balance-transfer" example adding total 5 peers and a Org1, removed the Org2. But while creating the channel i am facing the below issue. looks like its time out issue but unable to figure out. Can anyone help me over this please.

  r: <BN: 4debf915c59eeab7e1f12b43ec53dd85d70bb72df0c0178a803b03e3657ee92>,
  s: <BN: cf99377534970474a381e2fedcf92ee92597b2e46df2cb3cb3ced69dea88812>,
  recoveryParam: 0 }
error: [Remote.js]: Error: Failed to connect before the deadline URL:grpcs://localhost:7050
[2018-11-30 15:10:36.047] [ERROR] Join-Channel - Error: Failed to connect before the deadline URL:grpcs://localhost:7050
    at checkState (/home/djadhav/Desktop/new-balance-transfer/ncb-2.0-app/node_modules/grpc/src/client.js:720:16)
[2018-11-30 15:10:36.047] [ERROR] Join-Channel - Failed to join all peers to channel. cause:Error: Failed to connect before the deadline URL:grpcs://localhost:7050
(node:21122) UnhandledPromiseRejectionWarning: Error: Failed to join all peers to channel. cause:Error: Failed to connect before the deadline URL:grpcs://localhost:7050
    at Object.joinChannel (/home/djadhav/Desktop/new-balance-transfer/ncb-2.0-app/app/join-channel.js:101:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:21122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[2018-11-30 15:14:32.976] [DEBUG] SampleWebApp -  ------>>>>>> new request for /chaincodes
[2018-11-30 15:14:32.977] [DEBUG] SampleWebApp - Decoded from JWT token: username - Jim, orgname - Org1
[2018-11-30 15:14:32.977] [DEBUG] SampleWebApp - ==================== INSTALL CHAINCODE ==================
[2018-11-30 15:14:32.977] [DEBUG] SampleWebApp - peers : peer0.org1.example.com,peer1.org1.example.com,peer2.org1.example.com,peer3.org1.example.com,peer4.org1.example.com

**Comment by aklenik** [comment]
@dattajadhav44 Can you provide more details about your network? It looks like a misconfigured endpoint address. What were the exacts steps you did (crypto/channel config modification, docker network, etc.)?

**Comment by dattajadhav44** [comment]
Hi @aklenik . Below are the steps that i followed.
1. removed the Org2,peers and other related stuff.
2. generated the crypto certificate for newly added peers(5 peers, no anchor peer)
    help of this steps. 
     a. ../bin/cryptogen generate --config=./crypto-config.yaml
     b. export FABRIC_CFG_PATH=$PWD
     c. ../bin/configtxgen -profile TwoOrgsOrdererGenesis -outputBlock ./channel-artifacts/genesis.block
     4. export CHANNEL_NAME=mychannel  && ../bin/configtxgen -profile TwoOrgsChannel -outputCreateChannelTx ./channel-artifacts/channel.tx -channelID $CHANNEL_NAME
3. then ran the ./runAPI.sh. no error 
4. then ran ./testAPIs.sh...got error while creating channel

Please let me know if should i provide the file source code.

**Comment by aklenik** [comment]
@dattajadhav44 As I see, you're using the example of the `fabric-samples` repository. How do you exactly use Caliper for testing the `balance-transfer` example?

**Comment by dattajadhav44** [comment]
Hi @aklenik  Yes, i am using fabric-sample, balance transfer. i didnt get your question quite. I have used the steps which are the README.md file.
1. 1st terminal ./runApp.sh
2. 2nd terminal ./testAPI.sh 
Have i answered your question. i am using base of the fabric sample project, just modified it.

**Comment by aklenik** [comment]
@dattajadhav44 Since you raised this issue in the Hyperledger Caliper project, I assumed you use the `balance-transfer` example with Caliper. If that's not the case, please close this issue and ask around at the appropriate channels/lists/repos. But if you use Caliper, then share the related configuration files for the benchmark.

**Comment by dattajadhav44** [comment]
Thanks @aklenik
