### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by zsh122958** [hyperledger/caliper#268]
/home/mpsp/TrustedBench/src/comm/client/local-client.js:129
async function runFixedNumber(msg, cb, context) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
Client exited

**Comment by houqinghui** [comment]
@zsh122958  please check the version of nodejs, and make sure the nodejs is 8.x version. 
the problem is like the issue #73

**Comment by zsh122958** [comment]
@houqinghui  Thanks for upgrading node v11
