### ISSUE TITLE
error: [Peer.js]: sendProposal - timed out after:240000

### ISSUE THREAD

**Issue by YanLIU0822** [hyperledger/caliper#284]
**liuyan@liuyan-hp:~/caliper$ node benchmark/smallbank/main.js** 
info: [bench-flow.js]: ####### Caliper Test ######
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/docker-compose-tls.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating orderer.example.com ... done
Creating ca.org2.example.com    ... done
Creating ca.org1.example.com    ... done
Creating peer0.org1.example.com ... done
Creating peer0.org2.example.com ... done
info: [create-channel.js]: Creating mychannel...
info: [create-channel.js]: Created mychannel successfully
info: [create-channel.js]: Sleeping 5s...
info: [join-channel.js]: Joining channels...
info: [join-channel.js]: Joining mychannel...
info: [join-channel.js]: Successfully joined peerOrg1's peers to mychannel
info: [join-channel.js]: Successfully joined peerOrg2's peers to mychannel
info: [join-channel.js]: Successfully joined mychannel
info: [install-chaincode.js]: Installing chaincodes...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/drm
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/drm
info: [install-chaincode.js]: Installed chaincode drm successfully in all peers
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/marbles-norichquery/go
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/marbles-norichquery/go
info: [install-chaincode.js]: Installed chaincode marbles successfully in all peers
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/simple/go
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/simple/go
info: [install-chaincode.js]: Installed chaincode simple successfully in all peers
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/smallbank
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/smallbank
info: [install-chaincode.js]: Installed chaincode smallbank successfully in all peers
info: [instantiate-chaincode.js]: Instantiating chaincodes...
error: [Peer.js]: sendProposal - timed out after:240000
error: [Peer.js]: sendProposal - timed out after:240000
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/liuyan/caliper/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/liuyan/caliper/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
error: [instantiate-chaincode.js]: Failed to instantiate chaincodes: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200.
    at Object.instantiateChaincode (/home/liuyan/caliper/src/adapters/fabric/e2eUtils.js:353:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error: [fabric.js]: Fabric chaincode install failed: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200.
    at Object.instantiateChaincode (/home/liuyan/caliper/src/adapters/fabric/e2eUtils.js:353:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error: [bench-flow.js]: Error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200.
    at Object.instantiateChaincode (/home/liuyan/caliper/src/adapters/fabric/e2eUtils.js:353:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/docker-compose-tls.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
Stopping peer0.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping ca.org2.example.com    ... done
Stopping orderer.example.com    ... done
Stopping ca.org1.example.com    ... done
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca.org2.example.com    ... done
Removing orderer.example.com    ... done
Removing ca.org1.example.com    ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
error: [bench-flow.js]: Unsuccessful command execution. Error code: 1. Terminating signal: null
error: [benchamark/smallbank/main.js]: Error while executing the benchmark: Error: Command failed: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/docker-compose-tls.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
Stopping peer0.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping ca.org2.example.com    ... done
Stopping orderer.example.com    ... done
Stopping ca.org1.example.com    ... done
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca.org2.example.com    ... done
Removing orderer.example.com    ... done
Removing ca.org1.example.com    ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

## TIMEOUT
**I modify the file caliper/src/fabric/e2eUtils.js request_time
and the file caliper/node_modules/fabric-client/config/default.json**
240000
I tried 720000
So i guess it is not from the request_time

I check the docker logs 

**only peer0.org1.example.com shows a error** the others work well

**liuyan@liuyan-hp:~/caliper$ docker logs peer0.org1.example.com** 
2019-01-17 09:08:44.896 UTC [nodeCmd] serve -> INFO 001 Starting peer:
 Version: 1.1.0
 Go version: go1.9.2
 OS/Arch: linux/amd64
 Experimental features: false
 Chaincode:
  Base Image Version: 0.4.6
  Base Docker Namespace: hyperledger
  Base Docker Label: org.hyperledger.fabric
  Docker Namespace: hyperledger

2019-01-17 09:08:44.896 UTC [ledgermgmt] initialize -> INFO 002 Initializing ledger mgmt
2019-01-17 09:08:44.896 UTC [kvledger] NewProvider -> INFO 003 Initializing ledger provider
2019-01-17 09:08:45.826 UTC [kvledger] NewProvider -> INFO 004 ledger provider Initialized
2019-01-17 09:08:45.826 UTC [ledgermgmt] initialize -> INFO 005 ledger mgmt initialized
2019-01-17 09:08:45.826 UTC [peer] func1 -> INFO 006 Auto-detected peer address: 172.30.0.5:7051
2019-01-17 09:08:45.827 UTC [peer] func1 -> INFO 007 Returning peer0.org1.example.com:7051
2019-01-17 09:08:45.827 UTC [peer] func1 -> INFO 008 Auto-detected peer address: 172.30.0.5:7051
2019-01-17 09:08:45.827 UTC [peer] func1 -> INFO 009 Returning peer0.org1.example.com:7051
2019-01-17 09:08:45.830 UTC [nodeCmd] serve -> INFO 00a Starting peer with TLS enabled
2019-01-17 09:08:45.831 UTC [eventhub_producer] start -> INFO 00b Event processor started
2019-01-17 09:08:45.832 UTC [nodeCmd] computeChaincodeEndpoint -> INFO 00c Entering computeChaincodeEndpoint with peerHostname: peer0.org1.example.com
2019-01-17 09:08:45.832 UTC [nodeCmd] computeChaincodeEndpoint -> INFO 00d Exit with ccEndpoint: peer0.org1.example.com:7052
2019-01-17 09:08:45.832 UTC [nodeCmd] createChaincodeServer -> WARN 00e peer.chaincodeListenAddress is not set, using peer0.org1.example.com:7052
2019-01-17 09:08:45.833 UTC [chaincode] NewChaincodeSupport -> INFO 00f Chaincode support using peerAddress: peer0.org1.example.com:7052
2019-01-17 09:08:45.834 UTC [sccapi] registerSysCC -> INFO 010 system chaincode cscc(github.com/hyperledger/fabric/core/scc/cscc) registered
2019-01-17 09:08:45.834 UTC [sccapi] registerSysCC -> INFO 011 system chaincode lscc(github.com/hyperledger/fabric/core/scc/lscc) registered
2019-01-17 09:08:45.834 UTC [sccapi] registerSysCC -> INFO 012 system chaincode escc(github.com/hyperledger/fabric/core/scc/escc) registered
2019-01-17 09:08:45.834 UTC [sccapi] registerSysCC -> INFO 013 system chaincode vscc(github.com/hyperledger/fabric/core/scc/vscc) registered
2019-01-17 09:08:45.834 UTC [sccapi] registerSysCC -> INFO 014 system chaincode qscc(github.com/hyperledger/fabric/core/chaincode/qscc) registered
2019-01-17 09:08:45.835 UTC [gossip/service] func1 -> INFO 015 Initialize gossip with endpoint peer0.org1.example.com:7051 and bootstrap set [127.0.0.1:7051]
2019-01-17 09:08:45.837 UTC [msp] DeserializeIdentity -> INFO 016 Obtaining identity
2019-01-17 09:08:45.838 UTC [gossip/discovery] NewDiscoveryService -> INFO 017 Started {peer0.org1.example.com:7051 [] [19 86 204 101 33 30 204 125 116 22 3 116 219 124 113 177 125 88 18 145 9 22 27 116 36 193 232 145 140 239 19 208] peer0.org1.example.com:7051 <nil>} incTime is 1547716125838537785
2019-01-17 09:08:45.838 UTC [gossip/gossip] NewGossipService -> INFO 018 Creating gossip service with self membership of {peer0.org1.example.com:7051 [] [19 86 204 101 33 30 204 125 116 22 3 116 219 124 113 177 125 88 18 145 9 22 27 116 36 193 232 145 140 239 19 208] peer0.org1.example.com:7051 <nil>}
2019-01-17 09:08:45.840 UTC [gossip/gossip] start -> INFO 019 Gossip instance peer0.org1.example.com:7051 started
2019-01-17 09:08:45.840 UTC [cscc] Init -> INFO 01a Init CSCC
2019-01-17 09:08:45.840 UTC [sccapi] deploySysCC -> INFO 01b system chaincode cscc/(github.com/hyperledger/fabric/core/scc/cscc) deployed
2019-01-17 09:08:45.841 UTC [sccapi] deploySysCC -> INFO 01c system chaincode lscc/(github.com/hyperledger/fabric/core/scc/lscc) deployed
2019-01-17 09:08:45.842 UTC [escc] Init -> INFO 01d Successfully initialized ESCC
2019-01-17 09:08:45.842 UTC [sccapi] deploySysCC -> INFO 01e system chaincode escc/(github.com/hyperledger/fabric/core/scc/escc) deployed
2019-01-17 09:08:45.843 UTC [sccapi] deploySysCC -> INFO 01f system chaincode vscc/(github.com/hyperledger/fabric/core/scc/vscc) deployed
2019-01-17 09:08:45.843 UTC [qscc] Init -> INFO 020 Init QSCC
2019-01-17 09:08:45.843 UTC [sccapi] deploySysCC -> INFO 021 system chaincode qscc/(github.com/hyperledger/fabric/core/chaincode/qscc) deployed
2019-01-17 09:08:45.843 UTC [nodeCmd] initSysCCs -> INFO 022 Deployed system chaincodes
2019-01-17 09:08:45.844 UTC [nodeCmd] serve -> INFO 023 Starting peer with ID=[name:"peer0.org1.example.com" ], network ID=[dev], address=[peer0.org1.example.com:7051]
2019-01-17 09:08:45.844 UTC [nodeCmd] serve -> INFO 024 Started peer with ID=[name:"peer0.org1.example.com" ], network ID=[dev], address=[peer0.org1.example.com:7051]
2019-01-17 09:08:53.996 UTC [ledgermgmt] CreateLedger -> INFO 025 Creating ledger [mychannel] with genesis block
2019-01-17 09:08:54.042 UTC [fsblkstorage] newBlockfileMgr -> INFO 026 Getting block information from block storage
2019-01-17 09:08:54.300 UTC [kvledger] CommitWithPvtData -> INFO 027 Channel [mychannel]: Committed block [0] with 1 transaction(s)
2019-01-17 09:08:54.451 UTC [ledgermgmt] CreateLedger -> INFO 028 Created ledger [mychannel] with genesis block
2019-01-17 09:08:54.512 UTC [cscc] Init -> INFO 029 Init CSCC
2019-01-17 09:08:54.513 UTC [sccapi] deploySysCC -> INFO 02a system chaincode cscc/mychannel(github.com/hyperledger/fabric/core/scc/cscc) deployed
2019-01-17 09:08:54.514 UTC [sccapi] deploySysCC -> INFO 02b system chaincode lscc/mychannel(github.com/hyperledger/fabric/core/scc/lscc) deployed
2019-01-17 09:08:54.514 UTC [escc] Init -> INFO 02c Successfully initialized ESCC
2019-01-17 09:08:54.514 UTC [sccapi] deploySysCC -> INFO 02d system chaincode escc/mychannel(github.com/hyperledger/fabric/core/scc/escc) deployed
2019-01-17 09:08:54.515 UTC [sccapi] deploySysCC -> INFO 02e system chaincode vscc/mychannel(github.com/hyperledger/fabric/core/scc/vscc) deployed
2019-01-17 09:08:54.515 UTC [qscc] Init -> INFO 02f Init QSCC
2019-01-17 09:08:54.515 UTC [sccapi] deploySysCC -> INFO 030 system chaincode qscc/mychannel(github.com/hyperledger/fabric/core/chaincode/qscc) deployed
2019-01-17 09:08:55.142 UTC [lscc] executeInstall -> INFO 031 Installed Chaincode [drm] Version [v0] to peer
2019-01-17 09:08:55.176 UTC [lscc] executeInstall -> INFO 032 Installed Chaincode [marbles] Version [v1] to peer
2019-01-17 09:08:55.207 UTC [lscc] executeInstall -> INFO 033 Installed Chaincode [simple] Version [v0] to peer
2019-01-17 09:08:55.239 UTC [lscc] executeInstall -> INFO 034 Installed Chaincode [smallbank] Version [v0] to peer
2019-01-17 09:08:55.294 UTC [golang-platform] GenerateDockerBuild -> INFO 035 building chaincode with ldflagsOpt: '-ldflags "-linkmode external -extldflags '-static'"'
2019-01-17 09:08:55.294 UTC [golang-platform] GenerateDockerBuild -> INFO 036 building chaincode with tags: 
**2019-01-17 09:10:17.483 UTC [eventhub_producer] Chat -> ERRO 037 error during Chat, stopping handler: rpc error: code = Canceled desc = context canceled**

 
## Environment
liuyan@liuyan-hp:~/caliper$ npm ls grpc
caliper@0.1.0 /home/liuyan/caliper
├─┬ fabric-client@1.1.0
│ └── grpc@1.10.1  deduped
└── grpc@1.10.1 

liuyan@liuyan-hp:~/caliper$ npm ls fabric-client
caliper@0.1.0 /home/liuyan/caliper
└── fabric-client@1.1.0 

liuyan@liuyan-hp:~/caliper$ npm ls fabric-ca-client
caliper@0.1.0 /home/liuyan/caliper
└── fabric-ca-client@1.1.0 

liuyan@liuyan-hp:~/caliper$ node -v
v8.15.0
liuyan@liuyan-hp:~/caliper$ npm -v
6.5.0
liuyan@liuyan-hp:~/caliper$ node-gyp -v
v3.8.0

I also run npm install

ubuntu 16

**Comment by YanLIU0822** [comment]
@aklenik hey ak, could you help me out thanks

**Comment by YanLIU0822** [comment]
> @aklenik hey ak, could you help me out thanks

hey sorry for bothering you. I modify the require_time to 48000 it works

**Comment by YanLIU0822** [comment]
- [ ]
