### ISSUE TITLE
the troubles with running node benchmark/simple/main.js -c config.json -n fabric.json

### ISSUE THREAD

**Issue by dzyand** [hyperledger/caliper#350]
## Context
not ok 2 Failed to join peers, TypeError: Cannot read property 'getConnectivityState' of undefined at EventHub._checkConnection (/home/dzy/caliper/node_modules/fabric-client/lib/EventHub.js:479:39) at EventHub.registerBlockEvent (/home/dzy/caliper/node_modules/fabric-client/lib/EventHub.js:658:8) at Promise (/home/dzy/caliper/src/fabric/join-channel.js:167:8) at new Promise (<anonymous>) at eventhubs.forEach (/home/dzy/caliper/src/fabric/join-channel.js:164:20) at Array.forEach (<anonymous>) at Client.newDefaultKeyValueStore.then.then.then.then (/home/dzy/caliper/src/fabric/join-channel.js:163:13) at <anonymous>
  ---
    operator: fail
    at: channels.reduce.then.catch (/home/dzy/caliper/src/fabric/join-channel.js:74:15)
    stack: |-
      Error: Failed to join peers, TypeError: Cannot read property 'getConnectivityState' of undefined
          at EventHub._checkConnection (/home/dzy/caliper/node_modules/fabric-client/lib/EventHub.js:479:39)
          at EventHub.registerBlockEvent (/home/dzy/caliper/node_modules/fabric-client/lib/EventHub.js:658:8)
          at Promise (/home/dzy/caliper/src/fabric/join-channel.js:167:8)
          at new Promise (<anonymous>)
          at eventhubs.forEach (/home/dzy/caliper/src/fabric/join-channel.js:164:20)
          at Array.forEach (<anonymous>)
          at Client.newDefaultKeyValueStore.then.then.then.then (/home/dzy/caliper/src/fabric/join-channel.js:163:13)
          at <anonymous>
          at Test.assert [as _assert] (/home/dzy/caliper/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/dzy/caliper/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/home/dzy/caliper/node_modules/tape/lib/test.js:319:10)
          at Test.bound [as fail] (/home/dzy/caliper/node_modules/tape/lib/test.js:77:32)
          at channels.reduce.then.catch (/home/dzy/caliper/src/fabric/join-channel.js:74:15)
          at <anonymous>
  ...
fabric.init() failed, Error: Fabric: Join channel failed
    at channels.reduce.then.catch (/home/dzy/caliper/src/fabric/join-channel.js:75:27)
    at <anonymous>
unexpected error, Error: Fabric: Join channel failed
    at channels.reduce.then.catch (/home/dzy/caliper/src/fabric/join-channel.js:75:27)
    at <anonymous>
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml down;docker rm $(docker ps -aq)
/home/dzy/caliper/node_modules/fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                    ^

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/dzy/caliper/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/dzy/caliper/node_modules/grpc/src/client_interceptors.js:1292:19)
    at InterceptingListener.recvMessageWithContext (/home/dzy/caliper/node_modules/grpc/src/client_interceptors.js:607:19)
    at /home/dzy/caliper/node_modules/grpc/src/client_interceptors.js:706:14

**Comment by dzyand** [comment]
and there is no network.json

**Comment by aklenik** [comment]
@dzyand Based on your logs you use a reaaaallly outdated version of Caliper. The `simplenetwork` network has been removed a long time ago. Please clone the repository again and follow the instructions in the doc page: https://hyperledger.github.io/caliper/docs/1_Getting_Started.html

**Comment by dzyand** [comment]
thank you very much!

**Comment by dzyand** [comment]
@aklenik thank you very much!
