### ISSUE TITLE
error of testing sawtooth

### ISSUE THREAD

**Issue by Arucald** [hyperledger/caliper#351]
**My computer is Mac.
And I have installed docker, docker-compose, node and nvm.
But when I test the sawtooth, I typed:**

npm run bench -- -c benchmark/simple/config-sawtooth.yaml -n network/sawtooth/simplenetwork/sawtooth.json

**Then it begins to run, and the opening round is ok , but the 'query' shows the error like this:**

info: [bench-flow.js]: ------ Passed 'open' testing ------
info: [bench-flow.js]: Waiting 5 seconds for the next round...
info: [demo.js]: [Transaction Info] - Submitted: 10 Succ: 10 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 10 Succ: 10 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 10 Succ: 10 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 10 Succ: 10 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 10 Succ: 10 Fail:0 Unfinished:0
info: [bench-flow.js]: ####### Testing 'query' #######
info: [bench-flow.js]: ------ Test round 2 ------
error: [sawtooth.js]: Query failed, Error: no query responses
at /Users/dada/caliper/src/adapters/sawtooth/sawtooth.js:207:23
    at tryCatcher (/Users/dada/caliper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Connected to tcp://127.0.0.1:4004
info: [demo.js]: [Transaction Info] - Submitted: 10 Succ: 10 Fail:0 Unfinished:0
error: [sawtooth.js]: Query failed, Error: no query responses
    at /Users/dada/caliper/src/adapters/sawtooth/sawtooth.js:207:23
    at tryCatcher (/Users/dada/caliper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
info: [demo.js]: [Transaction Info] - Submitted: 11 Succ: 10 Fail:1 Unfinished:0
error: [sawtooth.js]: Query failed, Error: no query responses
    at /Users/dada/caliper/src/adapters/sawtooth/sawtooth.js:207:23
    at tryCatcher (/Users/dada/caliper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
info: [demo.js]: [Transaction Info] - Submitted: 13 Succ: 10 Fail:2 Unfinished:1
error: [sawtooth.js]: Query failed, Error: no query responses
    at /Users/dada/caliper/src/adapters/sawtooth/sawtooth.js:207:23
    at tryCatcher (/Users/dada/caliper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
info: [demo.js]: [Transaction Info] - Submitted: 14 Succ: 10 Fail:3 Unfinished:1
error: [sawtooth.js]: Query failed, Error: no query responses
    at /Users/dada/caliper/src/adapters/sawtooth/sawtooth.js:207:23
    at tryCatcher (/Users/dada/caliper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dada/caliper/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/dada/caliper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
info: [demo.js]: [Transaction Info] - Submitted: 15 Succ: 10 Fail:4 Unfinished:1
info: [bench-flow.js]: ###test result:###
info: [bench-flow.js]: 
+-------+------+------+-----------+-------------+-------------+-------------+------------+
| Name  | Succ | Fail | Send Rate | Max Latency | Min Latency | Avg Latency | Throughput |
|-------|------|------|-----------|-------------|-------------|-------------|------------|
| query | 0    | 5    | 1.2 tps   | 0.00 s      | 100000.00 s | NaN s       | 0.0 tps    |
+-------+------+------+-----------+-------------+-------------+-------------+------------+

**I am on the hyperledger HK bootcamp, and some guys using mac also face the same problems.**

**Comment by aklenik** [comment]
Also facing the problem on Ubuntu 18.04 LTS. Labeling it as a bug.

**Comment by feihujiang** [comment]
@Arucald @Arucald This was fixed by #361, please have a test.

**Comment by aklenik** [comment]
Fixed the problem for me.
