### ISSUE TITLE
deploy no-sample composer

### ISSUE THREAD

**Issue by hehui0316** [hyperledger/caliper#365]
info: [bench-flow.js]: ####### Testing 'pii4-network' #######
info: [bench-flow.js]: ------ Test round 1 ------
error: [bench-flow.js]: ------ Failed 'pii4-network' testing with the following error ------
Error: Client encountered error:SyntaxError: Missing catch or finally after try
    at ChildProcess.<anonymous> (/home/fz/caliper/src/comm/client/client-util.js:74:36)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
info: [bench-flow.js]: ---------- Finished Test ----------

error: [bench-flow.js]: Error: TypeError: Cannot read property 'unshift' of undefined
    at printResultsByRound (/home/fz/caliper/src/comm/bench-flow.js:136:23)
    at Object.module.exports.run (/home/fz/caliper/src/comm/bench-flow.js:373:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0

**Comment by aklenik** [comment]
@hehui0316 `Missing catch or finally after try.` This is the error one of the client processes encountered. Probably not originating from the Caliper code-base, so make sure your user test callback files are syntactically correct (i.e., there is a `catch` or `finally` block after the `try` blocks).

**Comment by nklincoln** [comment]
closing due to lack of activity
