### ISSUE TITLE
Why debug make error ,while run is ok?

### ISSUE THREAD

**Issue by friends110110** [hyperledger/caliper#39]
```
# ##### testing 'open' ######
----test round 0----
Starting inspector on 127.0.0.1:53951 failed: address already in use
Starting inspector on 127.0.0.1:53951 failed: address already in use
Starting inspector on 127.0.0.1:53951 failed: address already in use
Client exited
Client exited
Starting inspector on 127.0.0.1:53951 failed: address already in use
Starting inspector on 127.0.0.1:53951 failed: address already in use
started monitor successfully
Client exited
Client exited
Client exited
###test result:###
+------+------+------+-----------+-------------+-------------+-------------+----------------+------------+
| Name | Succ | Fail | Send Rate | Max Latency | Min Latency | Avg Latency | 75%ile Latency | Throughput |
+------+------+------+-----------+-------------+-------------+-------------+----------------+------------+

### resource stats ###
+---------+-----------------------------------+-------------+-------------+----------+----------+------------+-------------+
| TYPE    | NAME                              | Memory(max) | Memory(avg) | CPU(max) | CPU(avg) | Traffic In | Traffic Out |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Process | node local-client.js(avg)         | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | dev-peer1.org2.example.co...le-v0 | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | dev-peer1.org1.example.co...le-v0 | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | dev-peer0.org2.example.co...le-v0 | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | dev-peer0.org1.example.co...le-v0 | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | peer1.org1.example.com            | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | peer0.org1.example.com            | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | peer0.org2.example.com            | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | peer1.org2.example.com            | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | couchdb                           | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | orderer.example.com               | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | ca_peerOrg2                       | -           | -           | NaN%     | NaN%     | -          | -           |
|---------|-----------------------------------|-------------|-------------|----------|----------|------------|-------------|
| Docker  | ca_peerOrg1                       | -           | -           | NaN%     | NaN%     | -          | -           |
+---------+-----------------------------------+-------------+-------------+----------+----------+------------+-------------+

ok 5 passed 'open' testing
wait 5 seconds for next round...
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
# ##### testing 'query' ######
----test round 1----
not ok 6 failed 'query' testing, Error: Client encountered unexpected error at ChildProcess.<anonymous> (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client-util.js:71:32) at emitOne (events.js:116:13) at ChildProcess.emit (events.js:211:7) at ChildProcess.target.send (internal/child_process.js:592:12) at Object.startTest (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client-util.js:125:24) at Client._startLocalTest (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client.js:146:27) at Client.startTest (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client.js:80:26) at prev.then (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/bench-flow.js:256:31) at <anonymous>
  ---
    operator: fail
    at: client.startTest.then.then.catch (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/bench-flow.js:275:23)
    stack: |-
      Error: failed 'query' testing, Error: Client encountered unexpected error
          at ChildProcess.<anonymous> (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client-util.js:71:32)
          at emitOne (events.js:116:13)
          at ChildProcess.emit (events.js:211:7)
          at ChildProcess.target.send (internal/child_process.js:592:12)
          at Object.startTest (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client-util.js:125:24)
          at Client._startLocalTest (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client.js:146:27)
          at Client.startTest (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/client/client.js:80:26)
          at prev.then (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/bench-flow.js:256:31)
          at <anonymous>
          at Test.assert [as _assert] (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/node_modules/tape/lib/test.js:318:10)
          at Test.bound [as fail] (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/node_modules/tape/lib/test.js:77:32)
          at client.startTest.then.then.catch (/Users/friends/Documents/VirtualMachine/share/projects/Official_Examples/caliper/src/comm/bench-flow.js:275:23)
          at <anonymous>
  ...
----------finished test----------

```

**Comment by haojun** [comment]
Now there is no way in caliper to define the dependency of test rounds, so we assume each test round is independent, a failure of one round doesn't mean following rounds will fail.

**Comment by haojun** [comment]
That must be a bug. I'll check it later, thanks.

**Comment by friends110110** [comment]
Thank your very much, In fact , I know a littile of nodejs . If the project is written by go or java could satisfy  me

**Comment by panyu4** [comment]
PR 51 has resolve this issue.

**Comment by aklenik** [comment]
Now that the master and worker processes can be started separately, it is possible to use non-conflicting inspect ports, so I'm closing the issue.
