### ISSUE TITLE
Failed to read monitoring data

### ISSUE THREAD

**Issue by gerryyang** [hyperledger/caliper#4]
Hi, I have encountered this issue when run main.js to benchmark, as follow. How to avoid this please?

```
Failed to read monitoring data
TypeError: Cannot read property 'length' of undefined
    at processResult (/root/caliper/src/comm/bench-flow.js:373:26)
    at p.then (/root/caliper/src/comm/client/client.js:89:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
not ok 5 failed 'open' testing, TypeError: Cannot read property 'length' of undefined at processResult (/root/caliper/src/comm/bench-flow.js:373:26) at p.then (/root/caliper/src/comm/client/client.js:89:20) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: client.startTest.then.then.catch (/root/caliper/src/comm/bench-flow.js:275:23)
    stack: |-
      Error: failed 'open' testing, TypeError: Cannot read property 'length' of undefined
          at processResult (/root/caliper/src/comm/bench-flow.js:373:26)
          at p.then (/root/caliper/src/comm/client/client.js:89:20)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/root/caliper/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/root/caliper/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/root/caliper/node_modules/tape/lib/test.js:318:10)
          at Test.bound [as fail] (/root/caliper/node_modules/tape/lib/test.js:77:32)
          at client.startTest.then.then.catch (/root/caliper/src/comm/bench-flow.js:275:23)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
```

**Comment by feihujiang** [comment]
Is there a 'cannot find module xxx(dockerode etc)‘ error? if it is, please install the requested module. 'npm install dockerode'

**Comment by gerryyang** [comment]
yes, that's due to missing systeminformation and dockerode module in node actually. I suggest adding this dependency at Wiki is better because the log is too log to find.

**Comment by gerryyang** [comment]
Here are some node modules need to install firstly.
`npm install systeminformation dockerode mustache ps-node pidusage `

**Comment by haojun** [comment]
@gerryyang , actually those node modules are defined in package.json, so you can run `npm install` to install all dependencies
