### ISSUE TITLE
Fabric 1.4 testing - orderer SERVICE_UNAVAILABLE and query failure during linear run

### ISSUE THREAD

**Issue by hariharan-avs** [hyperledger/caliper#441]
Fabric 1.4 testing - orderer SERVICE_UNAVAILABLE and query failure during linear run

## Context
Running benchmarking in fabric 1.4, created network and docker compose files for 2 orderers config, 3 orderers and 4 orderers

Randomly getting the below errors while transaction open in simple workload and smallbankOperations in smallbank workload:

-----
error: [e2eUtils.js]: Failed to send transaction error: Error: Failed to send transaction successfully to the orderer status:SERVICE_UNAVAILABLE
-----
error: [e2eUtils.js]: Failed to complete transaction [518e8...]:Error: Timeout
    at Timeout.setTimeout [as _onTimeout] (/hyperledger/caliper-r/src/adapters/fabric/e2eUtils.js:870:54)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
------

And the query operations on testing are failing with below error: zero querying transaction successfull

(node:441001) UnhandledPromiseRejectionWarning: Error: {"code":303, "reason": "abnormal account"}
    at self._endorserClient.processProposal (/hyperledger/caliper/node_modules/fabric-client/lib/Peer.js:140:36)
    at Object.onReceiveStatus (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1191:9)
    at InterceptingListener._callNext (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:841:24)
(node:441001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 80001)
(node:441001) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:441015) UnhandledPromiseRejectionWarning: Error: {"code":303, "reason": "abnormal account"}
    at self._endorserClient.processProposal (/hyperledger/caliper/node_modules/fabric-client/lib/Peer.js:140:36)
    at Object.onReceiveStatus (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1191:9)
    at InterceptingListener._callNext (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:841:24)
(node:441015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 80001)
(node:441015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:441025) UnhandledPromiseRejectionWarning: Error: {"code":303, "reason": "abnormal account"}
    at self._endorserClient.processProposal (/hyperledger/caliper/node_modules/fabric-client/lib/Peer.js:140:36)
    at Object.onReceiveStatus (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1191:9)
    at InterceptingListener._callNext (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:614:8)

## Expected Behavior
Querying should go through without errors and open transaction should not get orderer SERVICE_UNAVAILABLE error

## Possible Fix
Would like to know the cause of these errors so can change the network config accordingly

**Comment by houqinghui** [comment]
@hariharan-avs  Do you use the raft consensus in your own fabric network?

**Comment by aklenik** [comment]
@hariharan-avs Since you experience this error randomly, my guess is that the issue originates from the Fabric network side. Make sure you have enough resource on the Fabric side, so transient issues like this do not occur. 
(Also, could you replicate this using the [Fabric-CCP adapter](https://hyperledger.github.io/caliper/docs/Fabric_Ccp_Configuration.html)?)

**Comment by trinayanbhatt** [comment]
I am facing a similiar issue while using Raft consensus protocol in which i have setup 5 orderers(1 in 1st server, 2 each and other 2 servers) namely orderer1 to orderer5.
Everything works fine in the setup and all the orderers are participating in the orderer election process but while i am trying to invoke a transaction then i facing an error like this:

[ERROR] invoke-chaincode - Failed to order the transaction. Error code: SERVICE_UNAVAILABLE

This error comes only when i try to invoke using orderer2 but works well with any other orderer. Please help to resolve the issue.

**Comment by adarshaJha** [comment]
hi i am also facing the same issue :- 
I am facing a similiar issue while using Raft consensus protocol in which i have setup 5 orderers(1 in 1st server, 2 each in other 2 servers) namely orderer1 to orderer5.
Everything works fine with the setup and all the orderers are participating in the orderer election process but while I'm trying to invoke a transaction then I'm facing an error like this:

[ERROR] invoke-chaincode - Failed to order the transaction. Error code: SERVICE_UNAVAILABLE

**Comment by aklenik** [comment]
@trinayanbhatt @adarshaJha This error is returned by Fabric, not Caliper. Check the logs of the orderer nodes for additional information, maybe they run into some error.
