### ISSUE TITLE
error: [caliper-flow]: Error: Error: Invalid endorsement for simple@v0 in mychannel from peer0.org1.example.com: chaincode registration failed: container exited with 254

### ISSUE THREAD

**Issue by lotty02cho** [hyperledger/caliper#613]
When I start to run caliper to test my network performance, the error came out.

## Context
I don't know exactly why it doesn't work. but I guess it will be peer sections.
I just edited the `networks/fabric/fabric-v1.4/3org2peercouchdb/fabric-node-tls.yaml` to run my network.

`npx caliper benchmark run --caliper-workspace . --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig networks/fabric/fabric-honeybee-v1.4.3/3org2peercouchdb/fabric-node-tls.yaml`

```
Benchmark for target Blockchain type fabric about to start
info: [caliper-flow]: ####### Caliper Test #######
info: [adapters/fabric]: Fabric SDK version: 1.4.3; TLS: server
warn: [adapters/fabric]: org1's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org2's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org3's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org4's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org5's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org6's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org1's admin's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org2's admin's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org3's admin's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org4's admin's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org5's admin's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: org6's admin's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: client0.org1.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: client0.org2.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: client0.org3.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: client0.org4.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: client0.org5.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
warn: [adapters/fabric]: client0.org6.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
info: [adapters/fabric]: Channel 'mychannel' is configured as created, skipping creation
info: [adapters/fabric]: peer0.org1.example.com has already joined mychannel
info: [adapters/fabric]: peer1.org1.example.com has already joined mychannel
info: [adapters/fabric]: peer0.org2.example.com has already joined mychannel
info: [adapters/fabric]: peer1.org2.example.com has already joined mychannel
info: [adapters/fabric]: peer0.org3.example.com has already joined mychannel
info: [adapters/fabric]: peer1.org3.example.com has already joined mychannel
info: [adapters/fabric]: peer0.org4.example.com has already joined mychannel
info: [adapters/fabric]: peer1.org4.example.com has already joined mychannel
info: [adapters/fabric]: peer0.org5.example.com has already joined mychannel
info: [adapters/fabric]: peer1.org5.example.com has already joined mychannel
info: [adapters/fabric]: peer0.org6.example.com has already joined mychannel
info: [adapters/fabric]: peer1.org6.example.com has already joined mychannel
info: [adapters/fabric]: Installing chaincodes for mychannel...
info: [adapters/fabric]: simple@v0 is already installed on peer0.org1.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer1.org1.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer0.org2.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer1.org2.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer0.org3.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer1.org3.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer0.org4.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer1.org4.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer0.org5.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer1.org5.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer0.org6.example.com
info: [adapters/fabric]: simple@v0 is already installed on peer1.org6.example.com
info: [adapters/fabric]: Instantiating simple@v0 in mychannel. This might take some time...
error: [caliper-flow]: Error: Error: Invalid endorsement for simple@v0 in mychannelfrom peer0.org1.example.com: chaincode registration failed: container exited with 254
    at proposalResponses.forEach (/opt/gopath/src/github.com/hyperledger/caliper-benchmarks/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:1342:31)
    at Array.forEach (<anonymous>)
    at Fabric._instantiateChaincodes (/opt/gopath/src/github.com/hyperledger/caliper-benchmarks/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:1338:35)
    at <anonymous>
Benchmark failure
Error: Benchmark failure
Command failed
```

## Expected Behavior
It should be work well.
install - instantiated - query - invoke.
but when caliper starts instantiate section, errors comes out.

## Actual Behavior

when I enter `peer logs peer0.org1.example.com -f --tail -100`. 
it throws log like this.
```
2019-10-21 16:58:53.449 KST [endorser] SimulateProposal -> ERRO 4aaf [smarthaccp][7ef6dd83] failed to invoke chaincode name:"lscc" , error: container exited with 254
github.com/hyperledger/fabric/core/chaincode.(*RuntimeLauncher).Launch.func1
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/runtime_launcher.go:63
runtime.goexit
        /opt/go/src/runtime/asm_amd64.s:1333
chaincode registration failed
```

## Steps to Reproduce

1. rm -rf caliper-benchmarks
2. git clone caliper-benchmarks
3. cd caliper-benchmarks
4. node -v --> version is 8.16.0
5. npm init -y
6. npm i @hyperledger/caliper-cli
7. npx caliper bind --caliper-bind-sut fabric --caliper-bind-sdk 1.4.3
8. cd /opt/gopath/src/github.com/hyperledger/caliper-benchmarks
9. vi networks/fabric/fabric-v1.4.3/3org2peercouchdb/fabric-node-tls.yaml
10. npx caliper benchmark run --caliper-workspace . --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig networks/fabric/fabric-v1.4.3/3org2peercouchdb/fabric-node-tls.yaml

## Existing issues
When I googled, I found some kind of related error.
https://github.com/IBM/blockchain-network-on-kubernetes/issues/41
however, it doesn't help to me.

## Your Environment

* Version used: fabric version 1.4.3
* Environment name and version node.js 8.16
* Operating System and version (desktop or mobile): Ubuntu 64 bit
* Link to your project: I don't have link because of security policy.

**Comment by aklenik** [comment]
Looks like you already have some artifacts present in your network. Does the CC container (dev-*) exist for a brief time before the peer logs the error? You can monitor it with `watch docker ps -a --filter "name=dev"`
The Docker daemon should provide additional information about the container events/failures.

**Comment by lotty02cho** [comment]
I start to run `npx caliper benchmark run ~` command in cli, and at the same time I monitor containers by using `watch docker ps -a --filter "name=dev"`.

here is my containers.
```
Every 2.0s: docker ps -a --filter name=dev                                                                                                                                                              hyperledger: Mon Oct 28 10:13:54 2019

CONTAINER ID        IMAGE                                                                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
d31f7ec21ccf        dev-peer0.org1.honeybee.com-haccp_public_action-1.0-36f7777f97e04305afeb8d766c7fdd42b40447fcfb8ceb9badfdcb54973d3601   "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_public_action-1.0
343d56f7597d        dev-peer0.org1.honeybee.com-haccp_common-1.0-24112ce65a4e5f0cd6a1d2c7dd53c4fabb14ac532adb202f3e0ce1fb9ca06b4a          "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_common-1.0
162155ee6966        dev-peer0.org1.honeybee.com-haccp_service-1.0-a9cc877d02f36d25165a3586474dbcce4e89690d7ccf5291f59a37a6181ba123         "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_service-1.0
139b5294161e        dev-peer0.org1.honeybee.com-haccp_certification-1.0-4b869900d1d52f711b0bf9737a294ea427d8a52635aefbcab813b5d16ff749f7   "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_certification-1.0
d59a069f1881        dev-peer0.org1.honeybee.com-haccp_ipfs-1.0-376b6eade28eaf57c34a77c945afeee69be546ee11c36c9ececc216e7e3fb545            "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_ipfs-1.0
30cc4996ae70        dev-peer0.org1.honeybee.com-haccp_file-1.0-3d1eda296f90d16b25ceb712a5fdad032d6f6069cca344d26d27d1aba4be040e            "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_file-1.0
ef20822cc1cc        dev-peer0.org1.honeybee.com-haccp_private-1.0-0d294ba8b29f7c4620374a88334ea00dbd0df459d488b55f05bfdf58dc5cb7b5         "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_private-1.0
a97d60d37fcc        dev-peer0.org1.honeybee.com-haccp_monitoring-1.0-68925c664637d4378630046629757d764b026014b81daf4fa774a6bd821d1938      "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-haccp_monitoring-1.0
6dbdc3548e9e        dev-peer0.org1.honeybee.com-tracecc-1.0-e0449f9fb6dfb6fb5a51622931c75796ea0532e08275c8751cd35ad5e84ecc7f               "/bin/sh -c 'cd /usr…"   3 days ago          Up 3 days                               dev-peer0.org
1.honeybee.com-tracecc-1.0
```
when start to run npx~, monitor shows `dev-peer0.org1.honeybee.com-marbles-1.0...` container. but it disappear rapidly. and error shows like below.
```
info: [adapters/fabric]: Instantiating marbles@v0 in honeybeechannel. This might take some time...
error: [caliper-flow]: Error: Error: Invalid endorsement for marbles@v0 in honeybeechannel from peer0.org1.honeybee.com: chaincode registration failed: container exited with 254
```

**Comment by aklenik** [comment]
If the container exists, then it generates some log (probably). Try to grab its output with Docker logs, or if it disappears too fast, then use some Docker log collector, like logspout. Or look around the Docker daemon logs manually, it should be there.
(I don't think it's a caliper issue, and fabric is not really verbose with its messages, so you need to dig into the fabric-side logs)

**Comment by lotty02cho** [comment]
when chaincode container had destroyed, I tried to get this log like below.

```
hyper@blockchain-001:~$ docker logs dev-peer1.org1.honeybee.com-marbles-v0 -f
npm ERR! path /usr/local/src/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/src/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-04T06_47_18_343Z-debug.log
```
I think it might be problem of path, but I don't know exactly why it happens.

**Comment by aklenik** [comment]
That looks like a nodejs chaincode deploy issue. Since you're using custom config files, make sure the following things are set correctly:
1. The chaincode to deploy has its `language` set to `node` (this is probably set, since the peer is looking for a package.json file)
2. Its directory path is set correctly, either an absolute path or relative to the workspace directory: https://github.com/hyperledger/caliper-benchmarks/blob/master/networks/fabric/fabric-v1.4.0/2org1peercouchdb/fabric-node-tls.yaml#L80-L83
3. The chaincode dir (that will be installed) contains a `package.json` file: https://github.com/hyperledger/caliper-benchmarks/tree/master/src/fabric/scenario/simple/node
4. The chaincode version is set correctly

**Comment by sroopsai** [comment]
I got a similar error.
`Error while performing "install" step: Error: Invalid endorsement for marbles@v0 in mychannel from peer0.org1.example.com: 2 UNKNOWN: Stream removed`
