### ISSUE TITLE
Cannot find module './api.js'

### ISSUE THREAD

**Issue by Hatuw** [hyperledger/caliper#65]
Hello, I updated the project but meet the error  "`Cannot find module './api.js'`". Then I try to reinstall the `tape-promise` package but it doesn't work. How could I fix this problem? Tks~

Btw, I think that create a new branch for developing is better.

Here is the details of the error:
``` 
# #######Caliper Test######
not ok 1 Error: Cannot find module './api.js'
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [Error: Cannot find module './api.js'] code: 'MODULE_NOT_FOUND' }
    at: Test.onetime [as end] (/home/hatuw/Documents/deployBC/hyperledger/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      Error: Cannot find module './api.js'
          at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
          at Function.Module._load (internal/modules/cjs/loader.js:475:25)
          at Module.require (internal/modules/cjs/loader.js:598:17)
          at require (internal/modules/cjs/helpers.js:11:18)
          at Object.<anonymous> (/home/hatuw/Documents/deployBC/hyperledger/caliper/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:19:11)
          at Module._compile (internal/modules/cjs/loader.js:654:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
          at Module.load (internal/modules/cjs/loader.js:566:32)
          at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
          at Function.Module._load (internal/modules/cjs/loader.js:498:3)
  ...

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by AnwinAshok** [comment]
or else you can Reinstall node report module inside the composer-cli

1.  Change directory into the composer-cli:
> cd /usr/lib/node_modules/composer-cli

 2. Reinstall node report  locally inside the composer-cli:
> sudo npm install node-report --unsafe-perm

Note : Don't put -g param in sudo npm install. Make the installation local to the composer-cli itself.

The node-report will run make with g++ to compile something (which for some reason was not run during composer-cli installation) and it just works...

**Comment by AnwinAshok** [comment]
or else you can Reinstall node report module inside the tape-promise

 1.Change directory into the tape-promise:

    cd /usr/lib/node_modules/tape-promise

2.Reinstall node report locally inside the tape-promise:

    sudo npm install node-report --unsafe-perm

Note : Don't put -g param in sudo npm install. Make the installation local to the tape-promise itself.

The node-report will run make with g++ to compile something (which for some reason was not run during tape-promise installation) and it just works...
