### ISSUE TITLE
Unable to test `basic-sample-network` or anything

### ISSUE THREAD

**Issue by technowar** [hyperledger/caliper#67]
I wish to check the Composer's performance using Caliper on `basic-sample-network` project. I have already installed

```
 "composer-admin": "0.19.0",
 "composer-client": "0.19.0",
 "composer-common": "0.19.0",
 "fabric-ca-client": "1.1.0",
 "fabric-client": "1.1.0",
```

and ran `npm install` to the root folder.  I am getting the error below.

```
$ node benchmark/composer/main.js
TAP version 13
# #######Caliper Test######
Creating orderer.example.com ... done
Creating network "2org1peer_default" with the default driver
Creating peer0.org1.example.com ... done
Creating ca.org2.example.com ...
Creating couchdb.org2.example.com ...
Creating ca.org1.example.com ...
Creating orderer.example.com ...
Creating peer0.org2.example.com ...
Creating peer0.org1.example.com ...
Initializing target platform configuration
✔ Creating channels mychannel
✔ Attempting to join peer peer0.org1.example.com to channel mychannel (attempt 2/5)
✔ Attempting to join peer peer0.org2.example.com to channel mychannel (attempt 1/5)
Deploying Composer
✔ Performing Composer runtime install for network basic-sample-network with card PerfPeerAdmin@Org1
⠋ Performing Composer runtime install for network basic-sample-network with card PerfPeerAdmin@Org2Composer runtime install failed, Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: access denied: channel [] creator org [Org2MSP]
    at HLFConnection.install (/Users/jahm/Documents/JavaScript/caliper/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:515:30)
    at <anonymous>
✖ Performing Composer runtime install for network basic-sample-network with card PerfPeerAdmin@Org2
composer.installSmartContract() failed,  Error: Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: access denied: channel [] creator org [Org2MSP]
    at Object.runtimeInstall (/Users/jahm/Documents/JavaScript/caliper/src/composer/composer_utils.js:380:15)
    at <anonymous>                        
unexpected error, Error: Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: access denied: channel [] creator org [Org2MSP]
    at Object.runtimeInstall (/Users/jahm/Documents/JavaScript/caliper/src/composer/composer_utils.js:380:15)
    at <anonymous>
docker-compose -f network/fabric-v11/2-org-1-peer/docker-compose.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev-* -q)
Stopping peer0.org2.example.com   ... done
Stopping peer0.org1.example.com   ... done
Stopping orderer.example.com      ... done
Stopping ca.org1.example.com      ... done
Stopping couchdb.org2.example.com ... done
Stopping ca.org2.example.com      ... done
Stopping couchdb.org1.example.com ... done
Removing peer0.org2.example.com   ... done
Removing peer0.org1.example.com   ... done
Removing orderer.example.com      ... done
Removing ca.org1.example.com      ... done
Removing couchdb.org2.example.com ... done
Removing ca.org2.example.com      ... done
Removing couchdb.org1.example.com ... done
Removing network 2org1peer_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...] [flags]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...] [flags]

Remove one or more images

1..0
# tests 0
# pass  0

# ok
```

Any help is greatly appreciated.

**Comment by nklincoln** [comment]
Hi,
i'd recommend upping the Composer version in the package to 0.19.5 and re-installing.

It would be worth inspecting the peer logs, as it looks like the channel is not being created - there has been a change in Docker with regards to the naming of the host config ... which has changed to being hyphen delimited. If that is the case the docker-compose.yaml file will need a slight tweak
