### ISSUE TITLE
Error: Cannot find module '@hyperledger/caliper-core'

### ISSUE THREAD

**Issue by Tallminsome** [hyperledger/caliper#771]
When I tired to test my own demo,which could be tested successfully on another PC,this problem came out.I looked through the solution in #549 ,but it doesn't work in my case

## Context

Handled unsuccessful "prepare" message for worker 0 and test round 2 with error Error: Cannot find module '@hyperledger/caliper-core'
2020.03.16-20:36:37.375 error [caliper] [round-orchestrator] 	Failed round 3 (query): Error: Error: Cannot find module '@hyperledger/caliper-core'
    at WorkerOrchestrator.updateWorkerPhase (/home/george/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/master/orchestrators/worker-orchestrator.js:211:61)
    at WorkerOrchestrator.processWorkerUpdate (/home/george/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/master/orchestrators/worker-orchestrator.js:124:18)
    at ChildProcess.<anonymous> (/home/george/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/common/messaging/process-master.js:51:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Your Environment

* Version used:caliper-cli@v0.3.0
* Environment name and version:nodejsv8.10.0 npmv5.6.0
* Operating System and version:Ubuntu 16.0.4
* Link to your project:

**Comment by aklenik** [comment]
@Tallminsome Could you please provide more information on what you were executing and how?

**Comment by Tallminsome** [comment]
@aklenik sorry,my bad.My friend just told me where is going wrong.Thanks for your reply.

**Comment by aklenik** [comment]
@Tallminsome Could you share what was the solution? In case anyone else runs into similar problems.

**Comment by Tallminsome** [comment]
@aklenik Sure,sorry for reply so late.
I was running this command:
npx caliper launch master \
--caliper-workspace ~/fabric-sample/solo-network \
--caliper-benchconfig benchmarks/config.yaml \ 
--caliper-networkconfig benchmarks/network.yaml

then,this err came out:
error [caliper] [round-orchestrator] 	Failed round 3 (query): Error: Error: Cannot find module '@hyperledger/caliper-core'
    at WorkerOrchestrator.updateWorkerPhase (/home/george/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/master/orchestrators/worker-orchestrator.js:211:61)
    at WorkerOrchestrator.processWorkerUpdate (/home/george/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/master/orchestrators/worker-orchestrator.js:124:18)
    at ChildProcess.<anonymous> (/home/george/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/common/messaging/process-master.js:51:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

my friend told me it's because the caliper-core couldn't find the js files,you should install caliper in where the  js files are.So I installed caliper in chaincode/demo/callback.Then it just works.

**Comment by aklenik** [comment]
@Tallminsome Yes, since the `@hyperledger/caliper-core` package is only installed as a dependency of other Caliper packages (CLI, SUT adapters), your workload module can't see it (it's buried under another package). In this case, you have to install the core package as a dependency of your workload module, just like you would do in any Node.JS project.
