### ISSUE TITLE
 failed 'open' testing, Error: Client encountered unexpected error

### ISSUE THREAD

**Issue by GiveMeSunShine** [hyperledger/caliper#78]
When I was in the directory caliper，execute the following command：

> node benchmark/simple/main.js

reported the following error information：

> not ok 6 failed 'open' testing, Error: Client encountered unexpected error at ChildProcess.<anonymous> (/root/caliper/src/comm/client/client-util.js:81:32) at emitOne (events.js:116:13) at ChildProcess.emit (events.js:211:7) at ChildProcess.target.send (internal/child_process.js:592:12) at Object.startTest (/root/caliper/src/comm/client/client-util.js:146:24) at Client._startLocalTest (/root/caliper/src/comm/client/client.js:223:27) at Client.startTest (/root/caliper/src/comm/client/client.js:146:22) at prev.then (/root/caliper/src/comm/bench-flow.js:238:31) at <anonymous>

---
    operator: fail
    at: client.startTest.then.then.catch (/root/caliper/src/comm/bench-flow.js:254:23)
    stack: |-
      Error: failed 'open' testing, Error: Client encountered unexpected error
          at ChildProcess.<anonymous> (/root/caliper/src/comm/client/client-util.js:81:32)
          at emitOne (events.js:116:13)
          at ChildProcess.emit (events.js:211:7)
          at ChildProcess.target.send (internal/child_process.js:592:12)
          at Object.startTest (/root/caliper/src/comm/client/client-util.js:146:24)
          at Client._startLocalTest (/root/caliper/src/comm/client/client.js:223:27)
          at Client.startTest (/root/caliper/src/comm/client/client.js:146:22)
          at prev.then (/root/caliper/src/comm/bench-flow.js:238:31)
          at <anonymous>
          at Test.assert [as _assert] (/root/caliper/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/root/caliper/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/root/caliper/node_modules/tape/lib/test.js:318:10)
          at Test.bound [as fail] (/root/caliper/node_modules/tape/lib/test.js:77:32)
          at client.startTest.then.then.catch (/root/caliper/src/comm/bench-flow.js:254:23)
          at <anonymous>
  ...

I  don't understand what “**Client encountered unexpected error**” means and how to deal with it.

**Comment by GiveMeSunShine** [comment]
Please click here to get a complete error log：
[https://github.com/GiveMeSunShine/caliper-ErroLog/blob/master/errlog.log](url)

**Comment by feihujiang** [comment]
Did you encounter this error again? If you did, could you please post your operation?

**Comment by nklincoln** [comment]
closing due to lack of activity
