### ISSUE TITLE
TypeError: Blockchain is not a constructor

### ISSUE THREAD

**Issue by HelmiTrabelsi** [hyperledger/caliper#800]
I tried to use caliper GUI, when I run a sample test I get this error 

TypeError: Blockchain is not a constructor
    at Object.module.exports.run (/home/helmi/caliper/packages/caliper-gui-server/src/gui-caliper-flow.js:67:25)
    at runBenchmark (/home/helmi/caliper/packages/caliper-gui-server/src/api/api1.js:259:40)
    at startTest (/home/helmi/caliper/packages/caliper-gui-server/src/api/api1.js:296:28)
    at api.get (/home/helmi/caliper/packages/caliper-gui-server/src/api/api1.js:324:24)
    at Layer.handle [as handle_request] (/home/helmi/caliper/packages/caliper-gui-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/helmi/caliper/packages/caliper-gui-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/helmi/caliper/packages/caliper-gui-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/helmi/caliper/packages/caliper-gui-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/helmi/caliper/packages/caliper-gui-server/node_modules/express/lib/router/index.js:281:22
    at param (/home/helmi/caliper/packages/caliper-gui-server/node_modules/express/lib/router/index.js:354:14)
[DEBUG] req.params.useSample: true

**Comment by aklenik** [comment]
@HelmiTrabelsi The GUI components are highly experimental right now. We're working out the details of the proper integration with the core Caliper code-base. As it requires a fair amount of changes, my guess is that the GUI component won't be functional before the v0.5.0 release :/
