### ISSUE TITLE
 Failed to create channels Error: create status is BAD_REQUEST

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#81]
root@vm10-210-0-10:~/caliper# node benchmark/simple/main.js -c config-fabric.json -n fabric.json
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d
ca_peerOrg1 is up-to-date
orderer.example.com is up-to-date
couchdb is up-to-date
ca_peerOrg2 is up-to-date
peer0.org2.example.com is up-to-date
peer1.org2.example.com is up-to-date
peer0.org1.example.com is up-to-date
peer1.org1.example.com is up-to-date
# create mychannel......
not ok 1 Failed to create channels Error: create status is BAD_REQUEST at channel.organizations.reduce.then.then.then (/root/caliper/src/fabric/create-channel.js:146:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/root/caliper/src/fabric/create-channel.js:160:19)
    stack: |-
      Error: Failed to create channels Error: create status is BAD_REQUEST
          at channel.organizations.reduce.then.then.then (/root/caliper/src/fabric/create-channel.js:146:43)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/root/caliper/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/root/caliper/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/root/caliper/node_modules/tape/lib/test.js:318:10)
          at Test.bound [as fail] (/root/caliper/node_modules/tape/lib/test.js:77:32)
          at channels.reduce.then.then.catch (/root/caliper/src/fabric/create-channel.js:160:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/root/caliper/src/fabric/create-channel.js:161:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
not ok 2 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/root/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/root/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/root/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/root/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...

1..2
# tests 2
# pass  0
# fail  2

root@vm10-210-0-10:~/caliper#

**Comment by JulienGuo** [comment]
solved :
stop old containers

**Comment by tingdai** [comment]
I encounter the same problem.
I have stopped the old containers but the same error still popped out.

**Comment by starrycheng** [comment]
I have met the same problem. Do you mean 'stop old containers' by using the command `doker container prune`? If not, would you like to provide a more specific solution to your issue?

**Comment by jamievaravara** [comment]
I also have this error, closing the old containers did not solve this. @JulienGuo
