### ISSUE TITLE
Caliper works with hurley

### ISSUE THREAD

**Issue by levanthanh3005** [hyperledger/caliper#812]
Hello,
I am using hurley:
https://github.com/worldsibu/hurley
And convector:
https://github.com/hyperledger-labs/convector
To build a test network with a smart contract, my fabric config is here:
[fabric.yaml.zip](https://github.com/hyperledger/caliper/files/4511957/fabric.yaml.zip)
but when I try to integrate caliper with hurley network, it makes an error:
Error: Fabric 1.0 compatibility mode is detected, but SDK version 1.4.0 is used
at new Fabric (/hyperledger/caliper/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:198:19)
at Function.handler (/hyperledger/caliper/node_modules/@hyperledger/caliper-cli/lib/benchmark/lib/runBenchmark.js:61:33)
at Object.module.exports.handler (/hyperledger/caliper/node_modules/@hyperledger/caliper-cli/lib/benchmark/runBenchmarkCommand.js:52:43)
at Object.runCommand (/hyperledger/caliper/node_modules/yargs/lib/command.js:228:22)
at Object.parseArgs [as _parseArgs] (/hyperledger/caliper/node_modules/yargs/yargs.js:1013:30)
at Object.runCommand (/hyperledger/caliper/node_modules/yargs/lib/command.js:194:45)
at Object.parseArgs [as _parseArgs] (/hyperledger/caliper/node_modules/yargs/yargs.js:1013:30)
at Object.get [as argv] (/hyperledger/caliper/node_modules/yargs/yargs.js:957:21)
at Object. (/hyperledger/caliper/node_modules/@hyperledger/caliper-cli/caliper.js:35:5)
at Module._compile (module.js:635:30)

Could you please take a look and check if I did any mistakes
Thank you

**Comment by aklenik** [comment]
@levanthanh3005 The network configuration file you supplied is for Fabric 1.0 (contains the `eventUrl` for peers), while the bound SDK version is 1.4. You probably want to test a 1.4 network, so assemble your network configuration file accordingly: https://hyperledger.github.io/caliper/v0.3/fabric-config/

**Comment by levanthanh3005** [comment]
Hi,
Thank you, the problem solved, but there is another issue, could you see the error:
2020.05.09-13:04:58.187 info  [caliper] [adapters/fabric] 	Channel 'ch1' is configured as created, skipping creation
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: access denied: channel [] creator org [org1MSP]
    at new createStatusError (/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /hyperledger/caliper/node_modules/grpc/src/client.js:583:15
error: [Client.js]: Failed Channels Query. Error: Error: 2 UNKNOWN: access denied: channel [] creator org [org1MSP]
    at new createStatusError (/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /hyperledger/caliper/node_modules/grpc/src/client.js:583:15
2020.05.09-13:04:58.215 error [caliper] [adapters/fabric] 	The following errors occurred while querying ch1 information from org1MSP's peers:
	- Couldn't query ch1 information from peer0.org1.hurley.lab: 2 UNKNOWN: access denied: channel [] creator org [org1MSP]
2020.05.09-13:04:58.215 error [caliper] [caliper-flow] 	Error: Error: Couldn't query ch1 information from org1MSP's peers
    at Fabric._joinChannels (/hyperledger/caliper/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:1495:27)
    at <anonymous>
