### ISSUE TITLE
 Failed to connect before the deadline  when join channel?

### ISSUE THREAD

**Issue by conquerorAlex** [hyperledger/caliper#815]
Failed to connect before the deadline  when join channel?

one of peers joined channel successfully, but another one doesn't. The error log shows: failed to connect before the deadline.

Can the deadline be set much bigger? And where is it?

logs as follow:
`2020.04.22-14:02:12.533 info  [caliper] [cli-launch-master]     Set workspace path: /root/caliper-tools/caliper-benchmarks
2020.04.22-14:02:12.535 info  [caliper] [cli-launch-master]     Set benchmark configuration path: /root/caliper-tools/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2020.04.22-14:02:12.535 info  [caliper] [cli-launch-master]     Set network configuration path: /root/caliper-tools/caliper-benchmarks/networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go-tls.yaml
2020.04.22-14:02:12.536 info  [caliper] [cli-launch-master]     Set SUT type: fabric
2020.04.22-14:02:12.539 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2020.04.22-14:02:12.539 info  [caliper] [caliper-engine]        Starting benchmark flow
2020.04.22-14:02:12.543 info  [caliper] [adapters/fabric]       Initializing standard adaptor compatible with installed SDK: 1.4.0
2020.04.22-14:02:13.166 info  [caliper] [caliper-utils]         Executing command: cd ./caliper-benchmarks/; export FABRIC_VERSION=1.4.1;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose-tls.yaml up -d;sleep 3s
Starting orderer.example.com ...
ca.org2.example.com is up-to-date
Starting orderer.example.com ... done
peer0.org2.example.com is up-to-date
peer0.org1.example.com is up-to-date
2020.04.22-14:02:19.000 info  [caliper] [caliper-engine]        Executed start command in 5.834 seconds
2020.04.22-14:02:19.001 info  [caliper] [adapters/fabric]       Fabric SDK version: 1.4.0; TLS: server
2020.04.22-14:02:19.323 warn  [caliper] [adapters/fabric]       6fdf7c12-8008-46e3-8617-98879a21477d's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
2020.04.22-14:02:19.335 warn  [caliper] [adapters/fabric]       cf7760ce-ec5b-4fd7-9634-7cd6c5bf7205's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
2020.04.22-14:02:19.349 info  [caliper] [adapters/fabric]       6fdf7c12-8008-46e3-8617-98879a21477d's admin's materials are successfully loaded
2020.04.22-14:02:19.357 info  [caliper] [adapters/fabric]       cf7760ce-ec5b-4fd7-9634-7cd6c5bf7205's admin's materials are successfully loaded
2020.04.22-14:02:19.365 info  [caliper] [adapters/fabric]       client0.org1.example.com's materials are successfully loaded
2020.04.22-14:02:19.371 info  [caliper] [adapters/fabric]       client0.org2.example.com's materials are successfully loaded
2020.04.22-14:02:19.373 info  [caliper] [adapters/fabric]       Channel 'mychannel001' definiton being retrieved from file
2020.04.22-14:02:19.451 info  [caliper] [adapters/fabric]       Channel 'mychannel001' successfully created
2020.04.22-14:02:19.452 info  [caliper] [adapters/fabric]       Sleeping 5s...
2020.04.22-14:02:24.716 info  [caliper] [adapters/fabric]       cf7760ce-ec5b-4fd7-9634-7cd6c5bf7205's **peers successfully joined** mychannel001: cf7760ce-ec5b-4fd7-9634-7cd6c5bf7205.peer0org1

**2020-04-22T06:02:27.724Z - error: [Remote.js]: Error: Failed to connect before the deadline URL:grpcs://10.233.38.212:7051
2020.04.22-14:02:27.725 error [caliper] [adapters/fabric]       The following errors occurred while querying mychannel001 information from 6fdf7c12-8008-46e3-8617-98879a21477d's peers:
        - Couldn't query mychannel001 information from 6fdf7c12-8008-46e3-8617-98879a21477d.peer0org2: Failed to connect before the deadline URL:grpcs://10.233.38.212:7051
2020.04.22-14:02:27.725 error [caliper] [caliper-engine]        Error while performing "init" step: Error: Couldn't query mychannel001 information from 6fdf7c12-8008-46e3-8617-98879a21477d's peers
2020.04.22-14:02:27.725 info  [caliper] [caliper-engine]        Executed "init" step in 8.725 seconds**
2020.04.22-14:02:27.726 info  [caliper] [caliper-engine]        Network configuration attribute "caliper.command.end" is not present, skipping end command
2020.04.22-14:02:27.726 error [caliper] [cli-launch-master]     Benchmark failed with error code 4
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 4
    at Function.handler (/root/caliper-tools/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:70:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by conquerorAlex** [comment]
already checked peer is running, and the ip: 10.233.38.212:7051 can be reached. telnet is ok.
