### ISSUE TITLE
TypeError: testFn is not a function

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#82]
guolidong:~/Documents/GitHub/caliper$ sudo node benchmark/simple/main.js -c config-fabric.json -n fabric.json
Password:
TAP version 13
# (anonymous)
not ok 1 TypeError: testFn is not a function
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: testFn is not a function]
    at: Test.onetime [as end] (/Users/guolidong/Documents/GitHub/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: testFn is not a function
          at Test.<anonymous> (/Users/guolidong/Documents/GitHub/caliper/node_modules/tape-promise/index.es5.js:21:13)
          at Test.bound [as _cb] (/Users/guolidong/Documents/GitHub/caliper/node_modules/tape/lib/test.js:77:32)
          at Test.run (/Users/guolidong/Documents/GitHub/caliper/node_modules/tape/lib/test.js:96:10)
          at Test.bound [as run] (/Users/guolidong/Documents/GitHub/caliper/node_modules/tape/lib/test.js:77:32)
          at Immediate.next (/Users/guolidong/Documents/GitHub/caliper/node_modules/tape/lib/results.js:71:15)
          at runCallback (timers.js:789:20)
          at tryOnImmediate (timers.js:751:5)
          at processImmediate [as _immediateCallback] (timers.js:722:5)
  ...

1..1
# tests 1
# pass  0
# fail  1

**Comment by JulienGuo** [comment]
never reproduce
