### ISSUE TITLE
Hyperledger Fabric performance

### ISSUE THREAD

**Issue by neewy** [hyperledger/caliper#9]
Hi! I would like to know what is the problem with my use of Caliper tool, as I was examining its work with other blockchain platforms than Iroha, and it seems like I have troubles with Fabric:

```
[Transaction Info] - Submitted: 15000 Succ: 268 Fail:14729 Unfinished:3
###test result:###
+------+------+------+-----------+-------------+-------------+-------------+----------------+------------+
| Name | Succ | Fail | Send Rate | Max Latency | Min Latency | Avg Latency | 75%ile Latency | Throughput |
|------|------|------|-----------|-------------|-------------|-------------|----------------|------------|
| open | 240  | 4760 | 242 tps   | 85.05 s     | 51.12 s     | 72.82 s     | 77.68 s        | 2 tps      |
+------+------+------+-----------+-------------+-------------+-------------+----------------+------------+
```

In the log, following messages are produced:
```
WARNING: timeout is too small, default value is used instead
Invoke chaincode failed, Error: Failed to send Proposal or receive valid response. Response null or status is not 200. exiting...
    at channel.sendTransactionProposal.then (/Users/neewy/Developer/caliper/src/fabric/e2eUtils.js:614:10)
    at <anonymous>
```

and 

```
Invoke chaincode failed, Error: Failed to get valid event notification
    at channel.sendTransaction.then.then (/Users/neewy/Developer/caliper/src/fabric/e2eUtils.js:611:14)
    at <anonymous>
```

In the end of log, before the docker network is being shut down:
```
ok 7 passed 'open' testing
wait 5 seconds for next round...
[Transaction Info] - Submitted: 15000 Succ: 268 Fail:14732 Unfinished:0
[Transaction Info] - Submitted: 15000 Succ: 268 Fail:14732 Unfinished:0
[Transaction Info] - Submitted: 15000 Succ: 268 Fail:14732 Unfinished:0
[Transaction Info] - Submitted: 15000 Succ: 268 Fail:14732 Unfinished:0
[Transaction Info] - Submitted: 15000 Succ: 268 Fail:14732 Unfinished:0
# ##### testing 'query' ######
[Transaction Info] - Submitted: 15000 Succ: 268 Fail:14732 Unfinished:0
unexpected error, TypeError: Cannot read property 'length' of undefined
    at /Users/neewy/Developer/caliper/src/comm/bench-flow.js:226:40
    at new Promise (<anonymous>)
    at defaultTest (/Users/neewy/Developer/caliper/src/comm/bench-flow.js:219:12)
    at prev.then (/Users/neewy/Developer/caliper/src/comm/bench-flow.js:129:28)
    at <anonymous>
```

What might be wrong?

I used `node main.js -c config-fabric.json`to run the benchmark against master branch

**Comment by haojun** [comment]
1. The reason of high failures may be due to the configured transaction rate exceeding the processing capacity of fabric and caliper itself. You can check the cpu usage of peers or bench-clients (it should be printed after each test round) to see if it is too high. You can lower the tps value in 'config-fabric.json' and run the test again to find out the maximum performance your SUT can reach.

2 The error in the end is a bug, the config-fabric.json uses an old property 'txNumbAndTps' which is not used now. You can change it to 'txNumber'. I will update caliper later to fix it, thanks.

**Comment by neewy** [comment]
Okay, thank you for clarification, I will try running it once again

**Comment by haojun** [comment]
Closes since no more comments
