### ISSUE TITLE
Malformed argument properties cause error message to be unnecessarily repeated

### ISSUE THREAD

**Issue by aldredb** [hyperledger/caliper#908]
I found that improper `args` structure e.g. not putting the chaincode function:

```
  let args = {
    chaincodeArguments: [params]
  };

  return bc.invokeSmartContract(contx, 'protocc', '0.0.1', args, 30);
```

Causes the number of error messages to be generated much more than it should. I used the following config with low number of transactions

```
test:
  workers:
    type: local
    number: 1
  rounds:
  - label: Invoke protobuf strings
    txDuration: 1
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
```

But the number of error message generated is (by my estimation) around 80, Sorry for the error message dump below. It's to illustrate the number of unnecessary repetitions

```
(node:35890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 160)
2020-07-06T09:47:38.347Z - error: [Contract]: verifyTransactionName: Transaction name must be a non-empty string: undefined
(node:35890) UnhandledPromiseRejectionWarning: Error: Transaction name must be a non-empty string: undefined
    at verifyTransactionName (/Users/aldred/Workspace/personal/protocc/caliper/node_modules/fabric-network/lib/contract.js:22:15)
    at Contract.createTransaction (/Users/aldred/Workspace/personal/protocc/caliper/node_modules/fabric-network/lib/contract.js:81:9)
    at Fabric._performGatewayTransaction (/Users/aldred/Workspace/personal/protocc/caliper/node_modules/@hyperledger/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js:444:43)
(node:35890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 161)
2020-07-06T09:47:38.353Z - error: [Contract]: verifyTransactionName: Transaction name must be a non-empty string: undefined
(node:35890) UnhandledPromiseRejectionWarning: Error: Transaction name must be a non-empty string: undefined
    at verifyTransactionName (/Users/aldred/Workspace/personal/protocc/caliper/node_modules/fabric-network/lib/contract.js:22:15)
    at Contract.createTransaction (/Users/aldred/Workspace/personal/protocc/caliper/node_modules/fabric-network/lib/contract.js:81:9)
    at Fabric._performGatewayTransaction (/Users/aldred/Workspace/personal/protocc/caliper/node_modules/@hyperledger/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js:444:43)
...MORE ERROR MESSAGES...
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 101)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 102)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 103)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 104)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 105)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 106)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 107)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 108)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 109)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 110)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 111)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 112)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 113)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 114)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 115)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 116)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 117)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 118)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 119)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 120)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 121)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 122)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 123)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 124)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 125)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 126)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 127)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 128)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 129)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 130)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 131)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 132)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 133)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 134)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 135)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 136)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 137)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 138)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 139)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 140)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 141)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 142)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 143)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 144)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 145)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 146)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 147)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 148)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 149)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 150)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 151)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 152)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 153)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 154)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 155)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 156)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 157)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 158)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 159)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 160)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 161)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 162)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 163)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 164)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 165)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 166)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 167)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 168)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 169)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 70)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 71)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 72)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 73)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 74)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 75)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 76)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 77)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 78)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 79)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 80)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 81)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 82)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 83)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 84)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 85)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 86)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 87)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 88)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 89)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 90)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 91)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 92)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 93)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 94)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 95)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 96)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 97)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 98)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 99)
(node:35890) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 100)
```

## Your Environment

* Version used: 0.3.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): NodeJS 10.12.1
* Operating System and version (desktop or mobile): MacOS Catalina
* Link to your project: None

**Comment by aklenik** [comment]
@aldredb Can you try with `txNumber: 1` instead of `txDuration: 1`? It looks like multiple TXs are submitted for some reason.
