### ISSUE TITLE
fabric1.1.0 Cannot read property 'getConnectivityState' of undefined Join channel failed

### ISSUE THREAD

**Issue by BeanChan1987** [hyperledger/caliper#91]
beans-MacBook-Pro:caliper bean$ npm install fabric-ca-client@1.1.0 fabric-client@1.1.0
fabric-client@1.1.0
fabric-ca-client@1.1.0
updated 2 packages in 5.893s
beans-MacBook-Pro:caliper bean$ cd benchmark/simple/
beans-MacBook-Pro:simple bean$ ls
config-composite-rate.json	config-sawtooth.json		fabric-remote.json		main.js				sawtooth.json
config-fabric.json		config-zookeeper.json		fabric.json			open.js
config-iroha.json		config.json			iroha.json			query.js
beans-MacBook-Pro:simple bean$ node main.js -c config-fabric.json -n fabric.json 
TAP version 13
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d
Creating orderer.example.com ... done
Creating ca_peerOrg1         ... done
Creating ca_peerOrg2         ... done
Creating couchdb             ... done
Creating peer0.org1.example.com ... done
Creating peer0.org2.example.com ... done
Creating peer1.org2.example.com ... done
Creating peer1.org1.example.com ... done
create mychannel......
ok 1 created mychannel successfully
Sleep 5s......
Join channel......
join mychannel
not ok 2 Failed to join peers, TypeError: Cannot read property 'getConnectivityState' of undefined at EventHub._checkConnection (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/EventHub.js:479:39) at EventHub.registerBlockEvent (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/EventHub.js:658:8) at Promise (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:140:20) at new Promise (<anonymous>) at eventhubs.forEach (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:137:29) at Array.forEach (<anonymous>) at Client.newDefaultKeyValueStore.then.then.then.then (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:136:19) at <anonymous>
    operator: fail
    at: channels.reduce.then.catch (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:216:19)
    stack: |-
      Error: Failed to join peers, TypeError: Cannot read property 'getConnectivityState' of undefined
          at EventHub._checkConnection (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/EventHub.js:479:39)
          at EventHub.registerBlockEvent (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/EventHub.js:658:8)
          at Promise (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:140:20)
          at new Promise (<anonymous>)
          at eventhubs.forEach (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:137:29)
          at Array.forEach (<anonymous>)
          at Client.newDefaultKeyValueStore.then.then.then.then (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:136:19)
          at <anonymous>
          at Test.assert [as _assert] (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.catch (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:216:19)
          at <anonymous>
fabric.init() failed, Error: Fabric: Join channel failed
    at channels.reduce.then.catch (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/fabric/join-channel.js:217:31)
    at <anonymous>
not ok 3 TypeError: Cannot read property 'getUpdates' of undefined
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                   
TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client_interceptors.js:629:19)
    at /Users/bean/Developer/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/client_interceptors.js:728:14

**Comment by haojun** [comment]
It's a problem caused by the newest grpc library.
You can  install grpc@1.10.1 manually (using npm install grpc@1.10.1) and try again.
