### ISSUE TITLE
Caliper does not have correct config file for Sawtooth

### ISSUE THREAD

**Issue by mamunbond07** [hyperledger/caliper#914]
## Context
Dear good people, I tried to benchmark the Sawtooth following the caliper documentation: https://hyperledger.github.io/caliper/v0.3.2/installing-caliper/#pre-requisites. Unfortunately the caliper codebase seems does not have proper config file for Sawtooth. I tried the following and get the error. 
>sudo npx caliper launch master \
>     --caliper-bind-sut sawtooth:1.0.0 \
>     --caliper-workspace . \
>     --caliper-benchconfig benchmarks/scenario/simple/config.yaml \
>     --caliper-networkconfig networks/sawtooth/smallbank/sawtooth-smallbank-go.yaml

## Output
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Network configuration file "/home/bc/caliper/caliper-benchmarks/networks/sawtooth/smallbank/sawtooth-smallbank-go.yaml" is missing its "caliper.blockchain" string attribute
    at Function.assertConfigurationFilePaths (/home/bc/caliper/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/common/utils/caliper-utils.js:75:19)
    at Function.handler (/home/bc/caliper/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:32:22)
    at Object.module.exports.handler (/home/bc/caliper/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/launchMasterCommand.js:46:43)
    at Object.runCommand (/home/bc/caliper/caliper-benchmarks/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/bc/caliper/caliper-benchmarks/node_modules/yargs/yargs.js:1154:41)
    at Object.runCommand (/home/bc/caliper/caliper-benchmarks/node_modules/yargs/lib/command.js:198:30)
    at Object.parseArgs [as _parseArgs] (/home/bc/caliper/caliper-benchmarks/node_modules/yargs/yargs.js:1154:41)
    at Object.get [as argv] (/home/bc/caliper/caliper-benchmarks/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/home/bc/caliper/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/caliper.js:39:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

## My Environment

* Version used: Sawtooth 1.0.0, Caliper 0.3.2
* Environment name and version: NodeJS 10.21.0,  npm 6.14.4,
* Operating System and version (desktop ): Ubuntu 16.x

Please kindly guide me to resolve this.

**Comment by aklenik** [comment]
@mamunbond07 What you set as network config file is actually a Docker-compose file. The correct network config file is `networks/sawtooth/smallbank/sawtooth.json`
