### ISSUE TITLE
TypeError: Cannot read property 'calculateTransactionId' of null

### ISSUE THREAD

**Issue by rtang03** [hyperledger/caliper#926]
I deployed a Fabric 2.1.0 network and install a lifecycle chaincode, with docker-compose. And, then run the benchmarks on host machine. 

**Any clue of "TypeError: Cannot read property 'calculateTransactionId' of null"??**

```
2020.07.17-00:01:36.176 info  [caliper] [cli-launch-master] 	Set workspace path: /Users/tangross/dev/2020/fabric-es/packages/caliper
2020.07.17-00:01:36.177 info  [caliper] [cli-launch-master] 	Set benchmark configuration path: /Users/tangross/dev/2020/fabric-es/packages/caliper/benchmarks/base.yaml
2020.07.17-00:01:36.178 info  [caliper] [cli-launch-master] 	Set network configuration path: /Users/tangross/dev/2020/fabric-es/packages/caliper/caliper.yaml
2020.07.17-00:01:36.178 info  [caliper] [cli-launch-master] 	Set SUT type: fabric
2020.07.17-00:01:36.184 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2020.07.17-00:01:36.184 info  [caliper] [caliper-engine] 	Starting benchmark flow
2020.07.17-00:01:36.670 info  [caliper] [adapters/fabric] 	Initializing gateway adaptor compatible with installed SDK: 2.1.0
2020.07.17-00:01:36.821 info  [caliper] [caliper-engine] 	Skipping start commands due to benchmark flow conditioning
2020.07.17-00:01:36.821 info  [caliper] [caliper-engine] 	Skipping initialization phase due to benchmark flow conditioning
2020.07.17-00:01:36.822 info  [caliper] [caliper-engine] 	Skipping install smart contract phase due to benchmark flow conditioning
2020.07.17-00:01:36.822 info  [caliper] [messenger.js] 	Creating messenger of type "process-master"
2020.07.17-00:01:36.825 info  [caliper] [null-observer] 	Configured "null" observer
2020.07.17-00:01:36.828 info  [caliper] [round-orchestrator] 	Monitors successfully started
2020.07.17-00:01:36.828 info  [caliper] [round-orchestrator] 	Started round 1 (createCommit - 100)
2020.07.17-00:01:36.829 info  [caliper] [worker-orchestrator] 	Launching worker 1 of 1
2020.07.17-00:01:36.833 info  [caliper] [worker-orchestrator] 	Messenger not configured, entering configure phase...
2020.07.17-00:01:36.834 info  [caliper] [worker-orchestrator] 	No existing workers detected, entering worker launch phase...
2020.07.17-00:01:36.834 info  [caliper] [worker-orchestrator] 	Waiting for 1 workers to be connected...
2020.07.17-00:01:37.160 info  [caliper] [cli-launch-worker] 	Set workspace path: /Users/tangross/dev/2020/fabric-es/packages/caliper
2020.07.17-00:01:37.161 info  [caliper] [cli-launch-worker] 	Set benchmark configuration path: /Users/tangross/dev/2020/fabric-es/packages/caliper/benchmarks/base.yaml
2020.07.17-00:01:37.162 info  [caliper] [cli-launch-worker] 	Set network configuration path: /Users/tangross/dev/2020/fabric-es/packages/caliper/caliper.yaml
2020.07.17-00:01:37.162 info  [caliper] [cli-launch-worker] 	Set SUT type: fabric
2020.07.17-00:01:37.164 info  [caliper] [messenger.js] 	Creating messenger of type "process-worker"  for SUT fabric
2020.07.17-00:01:41.840 info  [caliper] [worker-orchestrator] 	1 workers connected, progressing to worker assignment phase.
2020.07.17-00:01:41.840 info  [caliper] [worker-orchestrator] 	Workers currently unassigned, awaiting index assignment...
2020.07.17-00:01:41.841 info  [caliper] [worker-orchestrator] 	Waiting for 1 workers to be assigned...
2020.07.17-00:01:41.843 info  [caliper] [worker-orchestrator] 	1 workers assigned, progressing to worker initialization phase.
2020.07.17-00:01:41.843 info  [caliper] [worker-orchestrator] 	Waiting for 1 workers to be ready...
2020.07.17-00:01:41.844 info  [caliper] [message-handler] 	Handling "init" message
2020.07.17-00:01:42.160 info  [caliper] [adapters/fabric] 	Initializing gateway adaptor compatible with installed SDK: 2.1.0
2020.07.17-00:01:42.269 info  [caliper] [adapters/fabric] 	Fabric SDK version: 2.1.0; TLS: server
2020.07.17-00:01:42.270 warn  [caliper] [adapters/fabric] 	Administrative actions are not possible with Fabric SDK version: 2.1.0
2020.07.17-00:01:42.270 info  [caliper] [adapters/fabric] 	Fabric SDK version: 2.1.0; TLS: server
2020.07.17-00:01:42.270 info  [caliper] [adapters/fabric] 	Using defined file wallet path /Users/tangross/dev/2020/fabric-es/packages/caliper/assets/wallet
2020.07.17-00:01:42.272 info  [caliper] [adapters/fabric] 	Initializing administrators
2020.07.17-00:01:42.272 info  [caliper] [adapters/fabric] 	No admin.Org1MSP found in caliper configuration file - unable to perform admin options
2020.07.17-00:01:42.755 info  [caliper] [adapters/fabric] 	Initializing users
2020.07.17-00:01:42.758 info  [caliper] [adapters/fabric] 	Client admin-org1.net present in wallet: skipping client enrollment
2020.07.17-00:01:42.759 info  [caliper] [adapters/fabric] 	Client rca-org1-admin present in wallet: skipping client enrollment
2020.07.17-00:01:42.759 info  [caliper] [message-handler] 	Handled successful "init" message for worker 0
2020.07.17-00:01:42.760 info  [caliper] [worker-orchestrator] 	1 workers ready, progressing to test preparation phase.
2020.07.17-00:01:42.760 info  [caliper] [message-handler] 	Handling "prepare" message
2020.07.17-00:01:42.763 info  [caliper] [adapters/fabric] 	Retrieving and persisting contract map for identity admin-org1.net
2020.07.17-00:01:42.763 info  [caliper] [adapters/fabric] 	Connecting user admin-org1.net to a Network Gateway
2020.07.17-00:01:42.765 error [caliper] [adapters/fabric] 	Connecting user admin-org1.net to a Network Gateway failed with error: TypeError: cryptoSuite.createKeyFromRaw is not a function
2020.07.17-00:01:42.765 info  [caliper] [adapters/fabric] 	Generating contract map for user admin-org1.net
2020.07.17-00:01:42.766 info  [caliper] [adapters/fabric] 	Retrieving and persisting contract map for identity rca-org1-admin
2020.07.17-00:01:42.767 info  [caliper] [adapters/fabric] 	Connecting user rca-org1-admin to a Network Gateway
2020.07.17-00:01:42.767 error [caliper] [adapters/fabric] 	Connecting user rca-org1-admin to a Network Gateway failed with error: TypeError: cryptoSuite.createKeyFromRaw is not a function
2020.07.17-00:01:42.767 info  [caliper] [adapters/fabric] 	Generating contract map for user rca-org1-admin
2020.07.17-00:01:42.768 info  [caliper] [caliper-local-client] 	Info: client 0 prepare test :Querying By EntityNamephase starting...
2020.07.17-00:01:47.764 info  [caliper] [caliper-local-client] 	Initialization ongoing...
2020.07.17-00:01:47.768 info  [caliper] [caliper-local-client] 	Info: client 0 prepare test :Querying By EntityNamephase complete
2020.07.17-00:01:47.769 info  [caliper] [message-handler] 	Handled successful "prepare" message for worker 0 and test round 0
2020.07.17-00:01:47.769 info  [caliper] [worker-orchestrator] 	1 workers prepared, progressing to test phase.
2020.07.17-00:01:47.770 info  [caliper] [message-handler] 	Handling "test" message
2020.07.17-00:01:47.772 info  [caliper] [caliper-local-client] 	txUpdateTime: 5000
2020.07.17-00:01:47.779 info  [caliper] [caliper-local-client] 	Info: client 0 start test runDuration():Querying By EntityName
2020.07.17-00:01:47.781 error [caliper] [adapters/fabric] 	Failed to perform query transaction [queryByEntityName] using arguments [dev_entity],  with error: TypeError: Cannot read property 'calculateTransactionId' of null
    at Query.build (/Users/tangross/dev/2020/fabric-es/node_modules/fabric-common/lib/Proposal.js:181:42)
    at Transaction.evaluate (/Users/tangross/dev/2020/fabric-es/node_modules/fabric-network/lib/transaction.js:281:23)
    at Fabric._performGatewayTransaction (/Users/tangross/dev/2020/fabric-es/node_modules/@hyperledger/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js:487:44)
    at async Promise.all (index 0)
    at async Fabric.querySmartContract (/Users/tangross/dev/2020/fabric-es/node_modules/@hyperledger/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js:677:16)
    at async Fabric.querySmartContract (/Users/tangross/dev/2020/fabric-es/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:143:16)
    at async Blockchain.querySmartContract (/Users/tangross/dev/2020/fabric-es/node_modules/@hyperledger/caliper-core/lib/common/core/blockchain.js:144:16)
```

**Comment by aklenik** [comment]
@rtang03 It'd be useful to see what parameters you passed to `querySmartContract`. I assume you're not running an example from the benchmark repo.

**Comment by rtang03** [comment]
I am noting use benchmark repo. I create a "hello-world" smart contract with Fabric 2.1.0 Contract api. The callback is written in Typescript.

The chaincode name is "evenstore". 
The contractId is also "eventstore".

Here is the callback function. 

```
let bc;
let contx;

const callback = {
  info: 'Querying By EntityName',
  init: async (blockchain, context, args) => {
    bc = blockchain;
    contx = context;
    return true;
  },
  run: async () => {
    return await bc.querySmartContract(
      contx,
      'eventstore',
      undefined,
      {
        chaincodeFunction: 'queryByEntityName',
        chaincodeArguments: ['abcd'],
        invokerIdentity: 'admin-org1.net',
      },
  },
  end: async () => true,
};

export = callback;
```

**Comment by rtang03** [comment]
```yaml
name: first-network-org1
version: '1.0'
mutual-tls: false

caliper:
  blockchain: fabric

wallet: assets/wallet

info:
  Version: 2.1.0
  Size: 2 Orgs with 1 Peer
  Orderer: Raft,
  Distribution: Single Host
  StateDB: GoLevelDB

clients:
  admin-org1.net:
    client:
      organization: Org1MSP
  rca-org1-admin:
    client:
      organization: Org1MSP

channels:
  loanapp:
#    configBinary: ../../deployments/dev-net/artifacts/crypto-config/Org1MSP/peer0.org1.net/assets/channel.tx
    created: true
    orderers:
      - orderer0-org0
    peers:
      peer0-org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - id: eventstore
        contractID: eventstore
        version: v1.0
```

**Comment by aklenik** [comment]
@rtang03 Make sure that you use a compatible benchmark repo tag for your Caliper version. The `workload.module` structure is for the upcoming v0.4.0 release. You can checkout the `v0.3.2` tag of the benchmark repo if you're using Caliper v0.3.2

**Comment by rtang03** [comment]
Thank you for your clarification
