### ISSUE TITLE
running main.js and BAD REQUEST encountered

### ISSUE THREAD

**Issue by starrycheng** [hyperledger/caliper#93]
I have installed the caliper package and dependencies are installed.
I did not modify anything either in the config.json file or in the fabric.json file.
Then I simply run 

`node benchmark/simple/main.js -c config.json`
 and I met the following error:

```
# create mychannel......
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: EOF\n    at createStatusError (/Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)\n    at Client
DuplexStream._emitStatusIfDone (/Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:270:19)\n    at ClientDuplexStream._receiveStatus (/Users/starry/caliper/node_modules/fabri
c-client/node_modules/grpc/src/client.js:248:8)\n    at /Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:804:12"
not ok 1 Failed to create channels Error: SERVICE_UNAVAILABLE at ClientDuplexStream.<anonymous> (/Users/starry/caliper/node_modules/fabric-client/lib/Orderer.js:138:21) at emitOne (events.js:116:13) at Cl
ientDuplexStream.emit (events.js:211:7) at ClientDuplexStream._emitStatusIfDone (/Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:271:12) at ClientDuplexStream._receiveStat
us (/Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:248:8) at /Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:804:12
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/Users/starry/caliper/src/fabric/create-channel.js:160:19)
    stack: |-
      Error: Failed to create channels Error: SERVICE_UNAVAILABLE
          at ClientDuplexStream.<anonymous> (/Users/starry/caliper/node_modules/fabric-client/lib/Orderer.js:138:21)
          at emitOne (events.js:116:13)
          at ClientDuplexStream.emit (events.js:211:7)
          at ClientDuplexStream._emitStatusIfDone (/Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:271:12)
          at ClientDuplexStream._receiveStatus (/Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:248:8)
          at /Users/starry/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:804:12
          at Test.assert [as _assert] (/Users/starry/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/Users/starry/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/Users/starry/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/Users/starry/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/Users/starry/caliper/src/fabric/create-channel.js:160:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/Users/starry/caliper/src/fabric/create-channel.js:161:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
not ok 2 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/Users/starry/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/Users/starry/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/Users/starry/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/Users/starry/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
```
I have seen a closed issue mentioned the **BAD REQUEST** problem, which has feedback that the problem might be caused by the version of fabric.
However, since i did not modify the fabric.json file, and it is configured as network/fabric/simplenetwork/cryto-config

I am wondering whether this configure is ok, if it is not ok why it occurs in the default version of the config files. If it is ok, then what causes the aforementioned error?

**Comment by EG-easy** [comment]
i have a same error

**Comment by jamievaravara** [comment]
I also have the same error. The channel does not start up and I get the BAD_REQUEST.

**Comment by Miraczpp** [comment]
same error...
# create mychannel......
not ok 1 Failed to create channels Error: create status is BAD_REQUEST at channel.organizations.reduce.then.then.then (/opt/caliper/src/fabric/create-channel.js:146:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/opt/caliper/src/fabric/create-channel.js:160:19)
    stack: |-
      Error: Failed to create channels Error: create status is BAD_REQUEST
          at channel.organizations.reduce.then.then.then (/opt/caliper/src/fabric/create-channel.js:146:43)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/opt/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/opt/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/opt/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/opt/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/opt/caliper/src/fabric/create-channel.js:160:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/opt/caliper/src/fabric/create-channel.js:161:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
not ok 2 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/opt/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/opt/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/opt/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/opt/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...

1..2
# tests 2
# pass  0
# fail  2

**Comment by lotty02cho** [comment]
i have a same error too

**Comment by aklenik** [comment]
@starrycheng @lotty02cho @zsh122958 @EG-easy @Miraczpp @Ryan-Ouyang @jamievaravara 
Can you please provide the logs of the orderer node after you encountered the error? (as a GitHub gist preferably)

It is possible, that the orderer is not ready yet to serve the request. In this case, remove the start script from the config, start the network manually, wait a few more seconds, then execute the benchmark.

**Comment by lotty02cho** [comment]
Here is my orderer logs.
```
$ docker container logs orderer.example.com 
2018-12-03 01:54:50.138 UTC [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2018-12-03 01:54:50.160 UTC [orderer/common/server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = true
	General.TLS.PrivateKey = "/var/hyperledger/orderer/tls/server.key"
	General.TLS.Certificate = "/var/hyperledger/orderer/tls/server.crt"
	General.TLS.RootCAs = [/var/hyperledger/orderer/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleInsecureSolo"
	General.SystemChannel = "test-system-channel-name"
	General.GenesisFile = "/var/hyperledger/orderer/orderer.genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LogLevel = "INFO"
	General.LogFormat = "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
	General.LocalMSPDir = "/var/hyperledger/orderer/msp"
	General.LocalMSPID = "OrdererMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/var/hyperledger/orderer/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.PluginOpts =
	General.Authentication.TimeWindow = 15m0s
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
2018-12-03 01:54:50.160 UTC [orderer/common/server] initializeServerConfig -> INFO 003 Starting orderer with TLS enabled
2018-12-03 01:54:50.181 UTC [fsblkstorage] newBlockfileMgr -> INFO 004 Getting block information from block storage
2018-12-03 01:54:50.221 UTC [orderer/commmon/multichannel] NewRegistrar -> INFO 005 Starting system channel 'testchainid' with genesis block hash 82312e773f3d76e71927b33d85d25f42596fc5ce113390e1d34666df2151c9f7 and orderer type solo
2018-12-03 01:54:50.222 UTC [orderer/common/server] Start -> INFO 006 Starting orderer:
 Version: 1.2.0
 Commit SHA: cae2ad4
 Go version: go1.10
 OS/Arch: linux/amd64
 Experimental features: false
2018-12-03 01:54:50.222 UTC [orderer/common/server] Start -> INFO 007 Beginning to serve requests
2018-12-03 01:54:52.788 UTC [msp] DeserializeIdentity -> INFO 008 Obtaining identity
2018-12-03 01:54:52.790 UTC [msp] DeserializeIdentity -> INFO 009 Obtaining identity
2018-12-03 01:54:52.795 UTC [msp] DeserializeIdentity -> INFO 00a Obtaining identity
2018-12-03 01:54:52.810 UTC [fsblkstorage] newBlockfileMgr -> INFO 00b Getting block information from block storage
2018-12-03 01:54:52.845 UTC [orderer/commmon/multichannel] newChain -> INFO 00c Created and starting new chain mychannel
2018-12-03 01:54:53.016 UTC [msp] DeserializeIdentity -> INFO 00d Obtaining identity
2018-12-03 01:54:59.254 UTC [msp] DeserializeIdentity -> INFO 00e Obtaining identity
2018-12-03 01:55:06.133 UTC [msp] DeserializeIdentity -> INFO 00f Obtaining identity
2018-12-03 01:55:06.148 UTC [orderer/common/broadcast] Handle -> WARN 010 Error reading from 172.18.0.7:35334: rpc error: code = Canceled desc = context canceled
2018-12-03 01:55:06.151 UTC [common/deliver] Handle -> WARN 011 Error reading from 172.18.0.7:35332: rpc error: code = Canceled desc = context canceled
2018-12-03 01:55:06.167 UTC [msp] DeserializeIdentity -> INFO 012 Obtaining identity
2018-12-03 01:55:09.001 UTC [msp] DeserializeIdentity -> INFO 013 Obtaining identity
2018-12-03 01:55:09.254 UTC [msp] DeserializeIdentity -> INFO 014 Obtaining identity
2018-12-03 01:55:09.263 UTC [msp] DeserializeIdentity -> INFO 015 Obtaining identity
2018-12-03 01:55:09.267 UTC [orderer/common/broadcast] Handle -> WARN 016 Error reading from 172.18.0.7:35376: rpc error: code = Canceled desc = context canceled
2018-12-03 01:55:09.267 UTC [common/deliver] Handle -> WARN 017 Error reading from 172.18.0.7:35374: rpc error: code = Canceled desc = context canceled
2018-12-03 01:55:09.288 UTC [msp] DeserializeIdentity -> INFO 018 Obtaining identity
2018-12-03 01:55:09.288 UTC [msp] DeserializeIdentity -> INFO 019 Obtaining identity
2018-12-03 01:55:14.887 UTC [msp] DeserializeIdentity -> INFO 01a Obtaining identity
2018-12-03 01:55:14.890 UTC [orderer/common/broadcast] Handle -> WARN 01b Error reading from 172.18.0.7:35438: rpc error: code = Canceled desc = context canceled
```

**Comment by aklenik** [comment]
@lotty02cho What kind of error do you get? (Since you don't create the channel, I guess it's not a "can't create mychannel" error)

Could you also provide the following information:
* Version of the Fabric SDK you use (the backend is v1.2 as I see)
* Versions of additional packages, like grpc, node
* Where is your network (local docker containers, remotely, etc)
* Anything you think is relevant

Also note, that Caliper provides some network examples that are much easier to deploy in my opinion :)
