### ISSUE TITLE
Rejecting broadcast of message from 172.20.0.1:51068 with SERVICE_UNAVAILABLE: 

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#97]
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$  node benchmark/simple/main.js -c config-fabric-kafka.json -n fabric-kafka.json
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric/kafka/docker-compose.yaml up -d
Creating ca_peerOrg2 ... done
Creating zookeeper2  ... done
Creating zookeeper1  ... done
Creating ca_peerOrg1 ... done
Creating kafka_ca_1  ... done
Creating zookeeper0  ... done
Creating kafka0      ... done
Creating kafka2      ... done
Creating kafka1      ... done
Creating kafka3      ... done
Creating orderer.example.com ... done
Creating peer1.org2.example.com ... done
Creating peer0.org1.example.com ... done
Creating peer1.org1.example.com ... done
Creating peer0.org2.example.com ... done
# create mychannel......
not ok 1 Failed to create channels Error: create status is SERVICE_UNAVAILABLE at channel.organizations.reduce.then.then.then (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:146:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:160:19)
    stack: |-
      Error: Failed to create channels Error: create status is SERVICE_UNAVAILABLE
          at channel.organizations.reduce.then.then.then (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:146:43)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Test.assert [as _assert] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:160:19)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/fabric/create-channel.js:161:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
not ok 2 TypeError: Cannot read property 'getUpdates' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'getUpdates' of undefined]
    at: process.onetime (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'getUpdates' of undefined
          at update (/opt/gopath/src/github.com/hyperledger/caliper/src/gui/src/demo.js:145:26)
          at Object.demoStopWatch [as stopWatch] (/opt/gopath/src/github.com/hyperledger/caliper/src/gui/src/demo.js:185:5)
          at startPromise.then.then.then.then.then.then.catch (/opt/gopath/src/github.com/hyperledger/caliper/src/comm/bench-flow.js:347:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
  ...

1..2
# tests 2
# pass  0
# fail  2

guolidong:/opt/gopath/src/github.com/hyperledger/caliper$ 
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$ 
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$ docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                                                                       NAMES
ae73b773cb8a        hyperledger/fabric-peer:x86_64-1.1.0        "peer node start"        7 seconds ago       Up 8 seconds        0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp                              peer0.org2.example.com
30585812b9aa        hyperledger/fabric-peer:x86_64-1.1.0        "peer node start"        7 seconds ago       Up 8 seconds        0.0.0.0:8057->7051/tcp, 0.0.0.0:8059->7053/tcp                              peer1.org2.example.com
c96a34a8d5b2        hyperledger/fabric-peer:x86_64-1.1.0        "peer node start"        7 seconds ago       Up 7 seconds        0.0.0.0:7057->7051/tcp, 0.0.0.0:7059->7053/tcp                              peer1.org1.example.com
1e6e84cc6d24        hyperledger/fabric-peer:x86_64-1.1.0        "peer node start"        7 seconds ago       Up 8 seconds        0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp                              peer0.org1.example.com
ddfb6e1ca2a2        hyperledger/fabric-orderer:x86_64-1.1.0     "sh -c 'ln -snf /usr…"   8 seconds ago       Up 9 seconds        0.0.0.0:7050->7050/tcp                                                      orderer.example.com
54baca95c792        hyperledger/fabric-kafka:x86_64-0.4.6       "/docker-entrypoint.…"   10 seconds ago      Up 11 seconds       9093/tcp, 0.0.0.0:32818->9092/tcp                                           kafka1
aa4fb4832103        hyperledger/fabric-kafka:x86_64-0.4.6       "/docker-entrypoint.…"   10 seconds ago      Up 11 seconds       9093/tcp, 0.0.0.0:32819->9092/tcp                                           kafka3
7ffb9ae6b731        hyperledger/fabric-kafka:x86_64-0.4.6       "/docker-entrypoint.…"   10 seconds ago      Up 10 seconds       9093/tcp, 0.0.0.0:32817->9092/tcp                                           kafka2
b51d01ee9ea3        hyperledger/fabric-kafka:x86_64-0.4.6       "/docker-entrypoint.…"   10 seconds ago      Up 11 seconds       9093/tcp, 0.0.0.0:32816->9092/tcp                                           kafka0
aaebe3094b2c        hyperledger/fabric-ca:x86_64-1.1.0          "sh -c 'fabric-ca-se…"   12 seconds ago      Up 14 seconds       7054/tcp                                                                    kafka_ca_1
d0d8faa266cb        hyperledger/fabric-zookeeper:x86_64-0.4.6   "/docker-entrypoint.…"   12 seconds ago      Up 12 seconds       0.0.0.0:32815->2181/tcp, 0.0.0.0:32813->2888/tcp, 0.0.0.0:32810->3888/tcp   zookeeper0
92a8eb907d87        hyperledger/fabric-ca:x86_64-1.1.0          "sh -c 'fabric-ca-se…"   12 seconds ago      Up 12 seconds       0.0.0.0:7054->7054/tcp                                                      ca_peerOrg1
92de8fa0243f        hyperledger/fabric-zookeeper:x86_64-0.4.6   "/docker-entrypoint.…"   12 seconds ago      Up 12 seconds       0.0.0.0:32814->2181/tcp, 0.0.0.0:32812->2888/tcp, 0.0.0.0:32809->3888/tcp   zookeeper2
0b9abb4a6ea7        hyperledger/fabric-zookeeper:x86_64-0.4.6   "/docker-entrypoint.…"   12 seconds ago      Up 14 seconds       0.0.0.0:32811->2181/tcp, 0.0.0.0:32808->2888/tcp, 0.0.0.0:32807->3888/tcp   zookeeper1
2dce9cd07c4d        hyperledger/fabric-ca:x86_64-1.1.0          "sh -c 'fabric-ca-se…"   12 seconds ago      Up 13 seconds       0.0.0.0:8054->7054/tcp                                                      ca_peerOrg2
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$ docker logs orderer.example.com
2018-06-15 20:35:37.553 CST [orderer/common/server] prettyPrintStruct -> INFO 001 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = true
	General.TLS.PrivateKey = "/etc/hyperledger/msp/orderer/tls/server.key"
	General.TLS.Certificate = "/etc/hyperledger/msp/orderer/tls/server.crt"
	General.TLS.RootCAs = [/etc/hyperledger/msp/orderer/tls/ca.crt /etc/hyperledger/msp/peerOrg1/tls/ca.crt /etc/hyperledger/msp/peerOrg2/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleInsecureSolo"
	General.SystemChannel = "testchainid"
	General.GenesisFile = "/etc/hyperledger/configtx/twoorgs.genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LogLevel = "info"
	General.LogFormat = "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
	General.LocalMSPDir = "/etc/hyperledger/msp/orderer/msp"
	General.LocalMSPID = "OrdererMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/etc/hyperledger/msp/orderer/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.PluginOpts =
	General.BCCSP.Pkcs11Opts =
	General.Authentication.TimeWindow = 15m0s
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
2018-06-15 20:35:37.570 CST [orderer/common/server] initializeServerConfig -> INFO 002 Starting orderer with TLS enabled
2018-06-15 20:35:37.596 CST [fsblkstorage] newBlockfileMgr -> INFO 003 Getting block information from block storage
2018-06-15 20:35:37.609 CST [orderer/consensus/kafka] newChain -> INFO 004 [channel: testchainid] Starting chain with last persisted offset -3 and last recorded block 0
2018-06-15 20:35:37.616 CST [orderer/commmon/multichannel] NewRegistrar -> INFO 005 Starting system channel 'testchainid' with genesis block hash 23705eeb5f884bf067ce8c1a561c06eae4d4d7556880b517b1bc9ef02e87ccf4 and orderer type kafka
2018-06-15 20:35:37.617 CST [orderer/common/server] Start -> INFO 006 Starting orderer:
 Version: 1.1.0
 Go version: go1.9.2
 OS/Arch: linux/amd64
 Experimental features: false
2018-06-15 20:35:37.617 CST [orderer/consensus/kafka] setupProducerForChannel -> INFO 008 [channel: testchainid] Setting up the producer for this channel...
2018-06-15 20:35:37.617 CST [orderer/common/server] Start -> INFO 007 Beginning to serve requests
2018-06-15 20:35:40.005 CST [orderer/common/broadcast] Handle -> WARN 009 [channel: mychannel] Rejecting broadcast of message from 172.20.0.1:51068 with SERVICE_UNAVAILABLE: rejected by Consenter: will not enqueue, consenter for this channel hasn't started yet
2018-06-15 20:35:43.399 CST [orderer/consensus/kafka] startThread -> INFO 00a [channel: testchainid] Producer set up successfully
2018-06-15 20:35:43.399 CST [orderer/consensus/kafka] sendConnectMessage -> INFO 00b [channel: testchainid] About to post the CONNECT message...
2018-06-15 20:35:43.916 CST [orderer/consensus/kafka] startThread -> INFO 00c [channel: testchainid] CONNECT message posted successfully
2018-06-15 20:35:43.916 CST [orderer/consensus/kafka] setupParentConsumerForChannel -> INFO 00d [channel: testchainid] Setting up the parent consumer for this channel...
2018-06-15 20:35:43.920 CST [orderer/consensus/kafka] startThread -> INFO 00e [channel: testchainid] Parent consumer set up successfully
2018-06-15 20:35:43.920 CST [orderer/consensus/kafka] setupChannelConsumerForChannel -> INFO 00f [channel: testchainid] Setting up the channel consumer for this channel (start offset: -2)...
2018-06-15 20:35:43.931 CST [orderer/consensus/kafka] startThread -> INFO 010 [channel: testchainid] Channel consumer set up successfully
2018-06-15 20:35:43.931 CST [orderer/consensus/kafka] startThread -> INFO 011 [channel: testchainid] Start phase completed successfully
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$

**Comment by JulienGuo** [comment]
2018-06-15 20:35:40.005 CST [orderer/common/broadcast] Handle -> WARN 009 [channel: mychannel] Rejecting broadcast of message from 172.20.0.1:51068 with SERVICE_UNAVAILABLE: rejected by Consenter: will not enqueue, consenter for this channel hasn't started yet

**Comment by JulienGuo** [comment]
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$ docker logs zookeeper0
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
2018-06-15 13:37:43,415 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /conf/zoo.cfg
2018-06-15 13:37:43,518 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper2 to address: zookeeper2/172.20.0.5
2018-06-15 13:37:43,522 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper1 to address: zookeeper1/172.20.0.6
2018-06-15 13:37:43,523 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper0 to address: zookeeper0/172.20.0.4
2018-06-15 13:37:43,524 [myid:] - INFO  [main:QuorumPeerConfig@352] - Defaulting to majority quorums
2018-06-15 13:37:43,534 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2018-06-15 13:37:43,534 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 1
2018-06-15 13:37:43,548 [myid:1] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@138] - Purge task started.
2018-06-15 13:37:43,577 [myid:1] - INFO  [main:QuorumPeerMain@127] - Starting quorum peer
2018-06-15 13:37:43,586 [myid:1] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@144] - Purge task completed.
2018-06-15 13:37:43,651 [myid:1] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2018-06-15 13:37:43,661 [myid:1] - INFO  [main:QuorumPeer@1019] - tickTime set to 2000
2018-06-15 13:37:43,661 [myid:1] - INFO  [main:QuorumPeer@1039] - minSessionTimeout set to -1
2018-06-15 13:37:43,662 [myid:1] - INFO  [main:QuorumPeer@1050] - maxSessionTimeout set to -1
2018-06-15 13:37:43,662 [myid:1] - INFO  [main:QuorumPeer@1065] - initLimit set to 5
2018-06-15 13:37:43,691 [myid:1] - INFO  [main:QuorumPeer@533] - currentEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
2018-06-15 13:37:43,702 [myid:1] - INFO  [main:QuorumPeer@548] - acceptedEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
2018-06-15 13:37:43,713 [myid:1] - INFO  [ListenerThread:QuorumCnxManager$Listener@534] - My election bind port: zookeeper0/172.20.0.4:3888
2018-06-15 13:37:43,735 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer@774] - LOOKING
2018-06-15 13:37:43,742 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:FastLeaderElection@818] - New election. My id =  1, proposed zxid=0x0
2018-06-15 13:37:43,743 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@600] - Notification: 1 (message format version), 1 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
2018-06-15 13:37:43,764 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@400] - Cannot open channel to 2 at election address zookeeper1/172.20.0.6:3888
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:381)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:354)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
	at java.lang.Thread.run(Thread.java:748)
2018-06-15 13:37:43,771 [myid:1] - INFO  [WorkerSender[myid=1]:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper1 to address: zookeeper1/172.20.0.6
2018-06-15 13:37:43,772 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@400] - Cannot open channel to 3 at election address zookeeper2/172.20.0.5:3888
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:381)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:354)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
	at java.lang.Thread.run(Thread.java:748)
2018-06-15 13:37:43,772 [myid:1] - INFO  [WorkerSender[myid=1]:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper2 to address: zookeeper2/172.20.0.5
2018-06-15 13:37:43,860 [myid:1] - INFO  [zookeeper0/172.20.0.4:3888:QuorumCnxManager$Listener@541] - Received connection request /172.20.0.5:48192
2018-06-15 13:37:43,878 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@600] - Notification: 1 (message format version), 3 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
2018-06-15 13:37:43,878 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@600] - Notification: 1 (message format version), 3 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
2018-06-15 13:37:43,879 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@400] - Cannot open channel to 2 at election address zookeeper1/172.20.0.6:3888
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:381)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:354)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
	at java.lang.Thread.run(Thread.java:748)
2018-06-15 13:37:43,879 [myid:1] - INFO  [WorkerSender[myid=1]:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper1 to address: zookeeper1/172.20.0.6
2018-06-15 13:37:44,080 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer@844] - FOLLOWING
2018-06-15 13:37:44,083 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Learner@86] - TCP NoDelay set to: true
2018-06-15 13:37:44,104 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:zookeeper.version=3.4.9-1757313, built on 08/23/2016 06:50 GMT
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:host.name=zookeeper0
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.version=1.8.0_151
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.vendor=Oracle Corporation
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.class.path=/zookeeper-3.4.9/bin/../build/classes:/zookeeper-3.4.9/bin/../build/lib/*.jar:/zookeeper-3.4.9/bin/../lib/slf4j-log4j12-1.6.1.jar:/zookeeper-3.4.9/bin/../lib/slf4j-api-1.6.1.jar:/zookeeper-3.4.9/bin/../lib/netty-3.10.5.Final.jar:/zookeeper-3.4.9/bin/../lib/log4j-1.2.16.jar:/zookeeper-3.4.9/bin/../lib/jline-0.9.94.jar:/zookeeper-3.4.9/bin/../zookeeper-3.4.9.jar:/zookeeper-3.4.9/bin/../src/java/lib/*.jar:/conf:
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.io.tmpdir=/tmp
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.compiler=<NA>
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:os.name=Linux
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:os.arch=amd64
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:os.version=4.9.87-linuxkit-aufs
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:user.name=zookeeper
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:user.home=/home/zookeeper
2018-06-15 13:37:44,105 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:user.dir=/zookeeper-3.4.9
2018-06-15 13:37:44,106 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:ZooKeeperServer@173] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /datalog/version-2 snapdir /data/version-2
2018-06-15 13:37:44,107 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Follower@61] - FOLLOWING - LEADER ELECTION TOOK - 365
2018-06-15 13:37:44,111 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper2 to address: zookeeper2/172.20.0.5
2018-06-15 13:37:44,161 [myid:1] - INFO  [zookeeper0/172.20.0.4:3888:QuorumCnxManager$Listener@541] - Received connection request /172.20.0.6:39628
2018-06-15 13:37:44,172 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@600] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 2 (n.sid), 0x0 (n.peerEpoch) FOLLOWING (my state)
2018-06-15 13:37:44,173 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@600] - Notification: 1 (message format version), 3 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 2 (n.sid), 0x0 (n.peerEpoch) FOLLOWING (my state)
2018-06-15 13:37:44,183 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Learner@326] - Getting a diff from the leader 0x0
2018-06-15 13:37:44,185 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:FileTxnSnapLog@240] - Snapshotting: 0x0 to /data/version-2/snapshot.0
2018-06-15 13:37:47,043 [myid:1] - WARN  [QuorumPeer[myid=1]/0.0.0.0:2181:Follower@116] - Got zxid 0x100000001 expected 0x1
2018-06-15 13:37:47,044 [myid:1] - INFO  [SyncThread:1:FileTxnLog@203] - Creating new log file: log.100000001
2018-06-15 13:37:47,302 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /172.20.0.9:48164
2018-06-15 13:37:47,328 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@928] - Client attempting to establish new session at /172.20.0.9:48164
2018-06-15 13:37:47,390 [myid:1] - INFO  [CommitProcessor:1:ZooKeeperServer@673] - Established session 0x16403aa84f90000 with negotiated timeout 6000 for client /172.20.0.9:48164
guolidong:/opt/gopath/src/github.com/hyperledger/caliper$

**Comment by JulienGuo** [comment]
the request port is wrong

**Comment by JulienGuo** [comment]
> Hi JulienGuo! I am facing the same issue with message: SERVICE_UNAVAILABLE consenter for this channal hasn't start yet. Please clarify your case.

hi , @pyraman  The reason for my problem is " my request port of order is wrong" , the ports config in json config files and yaml config files .

**Comment by pyraman** [comment]
hi @jiangyaoguo here is my problem:

from CLI: ./peer.sh channel create -o orderer0.trade.com:7050 -c tradechannel -f ./tradechannel.tx --cafile tlsca.trade.com-cert.pem

--> Error: got unexpected status: SERVICE_UNAVAILABLE -- will not enqueue, consenter for this channel hasn't started yet.

from Orderer:

--> 2018-10-10 09:52:52.147 ICT [orderer/common/server] Deliver -> DEBU 74a Starting new Deliver handler

2018-10-10 09:52:52.147 ICT [common/deliver] Handle -> DEBU 74b Starting new deliver loop for 192.168.171.146:49401

2018-10-10 09:52:52.148 ICT [common/deliver] Handle -> DEBU 74c Attempting to read seek info message from 192.168.171.146:49401

2018-10-10 09:52:52.149 ICT [orderer/common/server] Broadcast -> DEBU 74d Starting new Broadcast handler

2018-10-10 09:52:52.149 ICT [orderer/common/broadcast] Handle -> DEBU 74e Starting new broadcast loop for 192.168.171.146:49402

2018-10-10 09:52:52.149 ICT [orderer/common/broadcast] Handle -> WARN 74f [channel: tradechannel] Rejecting broadcast of message from 192.168.171.146:49402 with SERVICE_UNAVAILABLE: rejected by Consenter: will not enqueue, consenter for this channel hasn't started yet

2018-10-10 09:52:52.149 ICT [orderer/common/server] func1 -> DEBU 750 Closing Broadcast stream

2018-10-10 09:52:52.153 ICT [grpc] Printf -> DEBU 751 transport: http2Server.HandleStreams failed to read frame: read tcp 192.168.171.33:7050->192.168.171.146:49402: read: connection reset by peer

2018-10-10 09:52:52.153 ICT [common/deliver] Handle -> WARN 752 Error reading from 192.168.171.146:49401: rpc error: code = Canceled desc = context canceled

2018-10-10 09:52:52.154 ICT [orderer/common/server] func1 -> DEBU 753 Closing Deliver stream.

do you have any ideas for my case?

**Comment by JulienGuo** [comment]
@pyraman can you try this solution：
1、add depend_on in yaml , such as zookeeper is depend by kafka , kafka is depend by orderer ,orderer is depend by peer
2、start fabric network by command ： docker-compose docker-compose.yaml up ....
3、delete start command in config.json ( about start network)
4、wait some seconds , more than 20s, then exec node command

**Comment by pyraman** [comment]
@JulienGuo thanks for supporting but I deploy the network manually without docker on different physical machines. 3 zookeepers, 4 brokers, 3 orderers, 4 orgs (one peer peer org).
https://jira.hyperledger.org/plugins/servlet/mobile#issue/FAB-11088/comment/52064

**Comment by cao0507** [comment]
@pyraman Hello, have you tried the caliper with multiple orderer nodes with kafka and zookeeper cluster?

**Comment by pyraman** [comment]
@cao0507 I've not try with Caliper but I found the reason that the kafka/zookeeper has been configured incorrectly.
